### ISSUE TITLE
Create example of replacing logo

### ISSUE THREAD

**Issue by brotzky** [narative/gatsby-theme-novela#1]

**Comment by mabasic** [comment]
I've read [this](https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/) and the official documentation on component shadowing, but when I create this in my project:

```
gatsby-theme-novela
    components
        Logo
            Logo.tsx
```

and modify the `Logo.tsx` file, nothing changes.

Any idea what am I doing wrong?

**Comment by brotzky** [comment]
you have to make sure you have it nested wthin @narative

https://github.com/narative/gatsby-theme-novela#adding-your-logo
