### ISSUE TITLE
[Bug] CopyToClipboard button next to theme toggle button

### ISSUE THREAD

**Issue by gagan0723** [narative/gatsby-theme-novela#10]
Clicking on CopyToClipboard button next to theme toggle button scrolls the page to very end on mobile devices. Both tested on Chrome and Safari for mobile.

![ScreenRecording_08-02-2019 09-44-33](https://user-images.githubusercontent.com/6944095/62353397-e05cf680-b50a-11e9-89cd-3a2614e7c6ac.gif)

**Comment by brotzky** [comment]
Thanks @gagan0723, will take a look asap!

**Comment by brotzky** [comment]
@gagan0723 could you let me know what shows in the logs?
I can't reproduce this on iOS Safari or Chrome (Pixel 3, iPhone 7 and iPhone X)

**Comment by gagan0723** [comment]
I don't think its possible to access console on mobile devices. It works fine on all mobile viewports when tested from within `devtools`.

I just gave it a shot once again on iphone 6, 7 and X and same issue.

Here's a gif from iphone X.

![RPReplay_Final1564956074](https://user-images.githubusercontent.com/6944095/62429853-92b3da00-b714-11e9-8e43-ed05653714f3.gif)

**Comment by brotzky** [comment]
You get access to devtools if you're using Safari on iOS and plugin your phone into your Apple laptop and open desktop Safari.
https://medium.com/@mattcroak718/debugging-your-iphone-mobile-web-app-using-safari-development-tools-71240657c487

As we can't reproduce the error it's lower priority for us right now. If you can get some more debugging details we'll be able to resolve it. No rush and no worries if you want.

**Comment by gagan0723** [comment]
I have tried connecting to the devtools using Safarin on iOS.
When clicking the button nothing logs to the console. Same issue though.

**Comment by brotzky** [comment]
Hmmmmmm, really weird. I'll keep this one top of mind but it's going to be hard to fix it. Really appreciate checking the logs.
