### ISSUE TITLE
Brainstorm: localization / multi-language

### ISSUE THREAD

**Issue by jpvalery** [narative/gatsby-theme-novela#102]
Hey everyone,

I'd like to brainstorm about the best way to implement localization with Novela. 

I'm working on a refactoring of the website of the Montréal Photo Club, and Montréal being a bilingual city I'd like to get the website to be bilingual.

I've thought of the following options: 

1/ Use Contentful localization features (with the caveat that the homepage isn't populated with Contentful data)

2/ Make one version the master and use it as a plugin for the localized versions with component shadowing to do the localization (not even sure if possible or if I make any sense)

3/ have two separate repo `site.en` and `site.fr` and double the work (aka the meh solution)

Would love to hear some more experienced thoughts on all that :) 

Thanks!

**Comment by freddydumont** [comment]
Localization in Gatsby is still a pain point, as there's no standard way to do it. At least there wasn't 6 months ago, things might have changed since I last had to deal with intl.

Last time I used a solution based on this: https://medium.com/significa/i18n-with-gatsby-528607b4da81.

It requires you to duplicate pages in `gatsby-node.js`, but the blog post explains it all. I haven't researched how you'd do this using a theme like Novela though. It might make things a bit more complex.

**Comment by jpvalery** [comment]
@freddydumont thanks for chipping in! I took a quick look at the great article you shared but I'm not sure that using `react-intl` would work that well (as it seems tailored for UI microcopy rather than blog content). 

Found this https://github.com/LekoArts/gatsby-starter-prismic-i18n that used localization with Prismic (so should be pretty similar to Contentful)

**Comment by brotzky** [comment]
@freddydumont that's more or less how I've handled in the paster. Hopper.com uses a similar pattern but we used react-intl instead (probably the dated lib now). That project used a mix of Contentful (easy setup) and strings stored in JS objects locally.

**Comment by jpvalery** [comment]
@brotzky would you advise to do the same for Novela then? Contentful for the posts and strings for homepage and UI?

**Comment by brotzky** [comment]
If you're doing it for yourself then yes. But for this theme and majority of users I would guess they're using MDX.

Im struggling to think of a way to keep the simplicity of the theme for everyone and add in localization as an option.

**Comment by jpvalery** [comment]
No worries, I was really asking for a personal use case rather than a feature :) 

At this point, I'm thinking that building twice might be the easiest actually since the content is pretty light and not updated on a daily basis.

Leaving this issue open if anybody else wants to chip in

**Comment by brotzky** [comment]
Going to close this for now as there haven't been any chip ins for a bit now. I don't see us handling localization within Novela in the near future unless it's done by the community <3.
