### ISSUE TITLE
Customize mailchimp subscription text with config

### ISSUE THREAD

**Issue by slorber** [narative/gatsby-theme-novela#104]
Currently when you use the mailchimp feature, you have a lorem ipsum text, and doc recommends to shadow the subscription component.

That's unfornunate because I'm perfectly fine with your subscription component, I just want to modify the text in it :)

I think it would be better to provide an option to configure text through config rather than using shadowing and having to copy-paste your component for shadowing it

https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/src/components/Subscription/Subscription.tsx#L48

**Comment by mabasic** [comment]
Even though I use component shadowing for it because of gdpr, I see a benefit in doing this, but just having a more general text for it instead of lorem ipsum should solve 90% of use cases for changing the text.

**Comment by brotzky** [comment]
@slorber want to propose some default copy for that section around the same length as the lorem?
I think that could be a solid solution as well for 90% as @mabasic pointed out.

**Comment by brotzky** [comment]
added generic text instead of lorem. Will solve for now. Shadowing is the correct way moving forward.

**Comment by slorber** [comment]
Great
Just wonder if for those cases it's not worth to make a comp just for the text. Shadowing a big file just to modify a tiny part works but feels a bit weird to me.

**Comment by brotzky** [comment]
I definitely get what you mean. Shadowing is a strange moving target and often components are made in a way that it's not always simple to shadow.
Agreed that configuration may be the way to go.
Maybe as the project gets bigger we can create a JSON object for all the custom copy instead of placing it in siteMetadata.
Even moving the subscription box copy into YAML like Authors could work.

**Comment by slorber** [comment]
Yeah that would be great to be able to change all text

Not so fan of shadowing. It's just an official patch package actually. Pretty sure it will lead to annoying upgrades and breaking changes as all the theme becomes an API surface somehow

**Comment by brotzky** [comment]
I share a similar sentiment. It turns the entire codebase into your API which... is really hard to maintain and has proven hard for people using the theme to keep up with. In theory any file renaming or moving right now would be a major version bump in semver.

We'll add some configurable text for that component.

**Comment by muinmomin** [comment]
I haven't been able to shadow the subscription component. Does anyone have an example?

**Comment by brotzky** [comment]
It's the same as shadowing the logo: https://github.com/narative/gatsby-theme-novela#adding-your-logo
