### ISSUE TITLE
Suggestion: adopt the contributor covenant code of conduct

### ISSUE THREAD

**Issue by bravo-kernel** [narative/gatsby-theme-novela#107]
There is currently a hot debate going on in the React world about code of conduct in OSS projects. The majority suggests adopting https://www.contributor-covenant.org/ which boils down to 2 changes:

1. add a badge on the readme
2. point users to the online COC in CONTRIBUTING.md or similar file/place

**Comment by jpvalery** [comment]
There's actually a way to automatically add it through Github in **Insights** > **Community**
![image](https://user-images.githubusercontent.com/4112343/63969693-63bd2980-ca70-11e9-9ca2-c4efd667db9b.png)
and then
![image](https://user-images.githubusercontent.com/4112343/63969713-70418200-ca70-11e9-9eda-95ff5df02548.png)

Not sure if it's needed as of now but I support the idea

**Comment by bravo-kernel** [comment]
That's nice

**Comment by bravo-kernel** [comment]
To motivate further:

- I did not suggest this as a current necessity. Most people will never turn nasty. In case someone does, this pretty much beats them to it, simply point them to the coc
- my main driver is the fact that companies (like Narative or mine for that matter) could benefit from adopting it as well. It can be a strong asset to incorporate in a company identity. Imagine a talk with a client, this can easily be brought up as a (very strong) non-tech positive

**Comment by brotzky** [comment]
https://github.com/narative/gatsby-theme-novela/pull/108

added
