### ISSUE TITLE
Use "prefers-color-scheme" to init color mode

### ISSUE THREAD

**Issue by dennismorello** [narative/gatsby-theme-novela#111]
**Is your feature request related to a problem? Please describe.**
Bootstrapping the site with the system's color scheme improves the user experience.

**Describe the solution you'd like**
Since more and more browsers support the `prefers-color-scheme` media query ([see here](https://caniuse.com/#search=prefers-color-scheme)), use it to set the initial color mode of the theme.

**Describe alternatives you've considered**
None.

**Additional context**
[https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme)

**Comment by brotzky** [comment]
I believe this is already done through theme-ui
https://theme-ui.com/color-modes/ (scroll to bottom)

**Comment by dennismorello** [comment]
You are right, I'm closing this feature request.

**Comment by brotzky** [comment]
Related to this, I need to fix the transition flash when you're on dark mode and visit Novela and it automatically switches to dark mode. There's already an issue open for that.
