### ISSUE TITLE
Component shadowing

### ISSUE THREAD

**Issue by mabasic** [narative/gatsby-theme-novela#115]
**Describe the bug**
Component shadowing does not work for files with a `.` inside the filename.

**Additional context**
More details in PR https://github.com/narative/gatsby-theme-novela/pull/97

Follow the progress of this to resolve: https://github.com/gatsbyjs/gatsby/pull/16424

Just wanted to open this issue for easier following of the progress of this issue.

**Comment by jpvalery** [comment]
Looking forward to the fix from Gatsby as my project is currently at a standstill without this feature 😅

**Comment by mabasic** [comment]
@jpvalery I've managed to work around this issue by using component shadowing on files that do not have a dot in the filename but are parent files and then inside those files import my own shadowed files without a dot in the filename.

**Comment by jpvalery** [comment]
Hmmm not sure to understand. How would that work for `Articles.Hero.tsx` for instance?

**Comment by mabasic** [comment]
You can't shadow `Articles.Hero.tsx` with this approach because it is imported in `articles.template.tsx` which also has a dot in the filename. If you go one step above that; `articles.template.tsx` is imported in `gatsby-theme-novela/gatsby/node/createPages.js` which I think can't be shadowed.

**Comment by brotzky** [comment]
Nice share, that would definitely work.

Really hope we're able to get shadowing working soon from Gatsby core. Seems be a reoccurring issue amongst Novela users. Unfortunate how our filenames cause it to break -- wish I realized when we started!

**Comment by jpvalery** [comment]
@mabasic Yeah, my use case being on the Articles.Hero.tsx, I think I'm better to just wait for the fix from Gatsby :/ 
Although your example for Navigation.Footer.tsx could work for the other use case, I'm just unsure about doing the effort to do the workaround vs wait for the global fix :) 

@brotzky no worries man, it's just an unfortunate edge case :)

**Comment by ChristopherBiscardi** [comment]
The fix has been merged. waiting for a release.

**Comment by jpvalery** [comment]
Amazing news @ChristopherBiscardi ! Thanks for updating us :)

**Comment by brotzky** [comment]
Thank you, @ChristopherBiscardi!

**Comment by jpvalery** [comment]
This has been published in `gatsby@2.15.7. Whenever Novela updates to this dep this issue can be closed

**Comment by brotzky** [comment]
fantastic. will update today

**Comment by brotzky** [comment]
Fix is published. Shadowing should work now 🙆‍♂!

v0.6.2
