### ISSUE TITLE
Wrong tags on GitHub

### ISSUE THREAD

**Issue by mabasic** [narative/gatsby-theme-novela#116]
This is just sugar on top, but here it goes.

You have got tags on GitHub in this order:
- v0.0.7
- v0.0.8
- v0.0.11
- v0.1.0
- v0.2.0
- 5.0.0
- 0.6.0

Notice the inconsistency here. Maybe just leave the 0.6.0 tag, go from there and delete the others?

**Comment by brotzky** [comment]
Fixed
