### ISSUE TITLE
Horizontal scroll is back on Large images

### ISSUE THREAD

**Issue by mabasic** [narative/gatsby-theme-novela#117]
**Version of Novela you are using**
0.6.0

**Number of posts you have and which data source**
Local
https://novela.narative.co/understanding-the-gatsby-lifecycle-with-narative

**Describe the bug**
Horizontal scroll bar appears on article show.

**To Reproduce**
1. Go to https://novela.narative.co/understanding-the-gatsby-lifecycle-with-narative
2. View horizontal scroll bar

**Expected behavior**
No horizontal scroll bar.

**Browser**
 - Chrome
- Firefox

**Additional context**
Was solved in https://github.com/narative/gatsby-theme-novela/pull/100.
Was attempted to be solved in https://github.com/narative/gatsby-theme-novela/pull/112
It was maybe reintroduced in the meantime.

**Comment by brotzky** [comment]
Seems this was fixed indirectly (doesn't scroll horizontally or have scrollbars on Chrome and Firefox).
