### ISSUE TITLE
How to add authors

### ISSUE THREAD

**Issue by michelem09** [narative/gatsby-theme-novela#12]
I'm not sure how to add authors, what kind of file should it be? yaml?

```
- name: Dennis Brotzky
  bio: |
    Written by Dennis Brotzky who lives and works in Vancouver building useful things.
    You should follow him on Twitter.
  avatar: ./avatars/dennis-brotzky.jpg
  featured: true
```

**Comment by johnletey** [comment]
@michelem09 Yes, it would be in YAML. Look at how they do it for the demo site: [`content/authors/authors.yml`](https://github.com/narative/gatsby-theme-novela-example/blob/master/content/authors/authors.yml)

**Comment by michelem09** [comment]
Cool, I didn't see the example, I will try with that for my other errors too.
