### ISSUE TITLE
yarn build is failing

### ISSUE THREAD

**Issue by smakosh** [narative/gatsby-theme-novela#123]
**Version of Novela you are using**
`^0.*`

**Number of posts you have and which data source**
2, Contentful

**Describe the bug**
`yarn build` fails
> Logs
```bash
"gatsby-plugin-feed" threw an error while running the onPostBuild lifecycle:

Cannot query field "secret" on type "Article".

GraphQL request:11:23
10 |                       author
11 |                       secret
   |                       ^
12 |                     }
```

**Expected behavior**
Should build successfully

**Browser**
 - Chrome

**Comment by brotzky** [comment]
Is it related to https://github.com/narative/gatsby-theme-novela/issues/122?

**Comment by smakosh** [comment]
Nope, `yarn dev` works fine, but `yarn build` is failing

**Comment by mabasic** [comment]
It think that it has something to do with Contentful because when using local it works. Maybe double check `secret` field on contentful. I don't know how it works, but I would look there.

**Comment by brotzky** [comment]
@smakosh it could be out contentful export is out of date. I've exported latest.

make sure on Secret field in Contentful you select yes or no.

**Comment by smakosh** [comment]
Yup it is selected but the build still fails
<img width="351" alt="Screen Shot 2019-09-06 at 9 01 33 AM" src="https://user-images.githubusercontent.com/20082141/64411383-f703e980-d084-11e9-9d4c-5885e4619f49.png">

**Comment by smakosh** [comment]
Removing this https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/gatsby-config.js#L79 fixes my issue

**Comment by smakosh** [comment]
somehow that schema doesn't contain `secret` field
<img width="561" alt="Screen Shot 2019-09-06 at 9 11 32 AM" src="https://user-images.githubusercontent.com/20082141/64411988-5a424b80-d086-11e9-8048-18280da5dbd9.png">

**Comment by smakosh** [comment]
You should check if the user wants to use `local` or `contentful` as source of content and then use the right query, so here you should query `allContentfulPost` instead, I'll open a PR to handle this

**Comment by mabasic** [comment]
@smakosh We need that field for the RSS feed to not include secret posts. The issue seems to be with contentful and `secret`, not with the query for the RSS

**Comment by smakosh** [comment]
check https://github.com/narative/gatsby-theme-novela/issues/123#issuecomment-528759188

**Comment by mabasic** [comment]
I did.

**Comment by mabasic** [comment]
Even if you change the query, you would still need the `secret` field meaning the query remains the same.

**Comment by smakosh** [comment]
changing the query works fine 👌

**Comment by mabasic** [comment]
With `secret` field inside ?

**Comment by smakosh** [comment]
<img width="538" alt="Screen Shot 2019-09-06 at 9 19 39 AM" src="https://user-images.githubusercontent.com/20082141/64412539-7b576c00-d087-11e9-9543-b840bb46ab82.png">

**Comment by mabasic** [comment]
Hmm.. but shouldn't the original query be the same for local and contentful. I still think that the issue lies somewhere else. Maybe @brotzky can shed some light on this, since I don't know about how contentful is implemented in this theme.

**Comment by smakosh** [comment]
I'm trying to access `themeOptions` from `gatsby-config.js` but fail miserably, can you advice if I can actually access it as you did on `gatsby-node.js`?

**Comment by smakosh** [comment]
https://github.com/narative/gatsby-theme-novela/pull/126 👀 cc @brotzky @mabasic

**Comment by brotzky** [comment]
Great PR

we do have different queries for Contentful and Local data

https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/gatsby/data/data.query.js#L96

**Comment by smakosh** [comment]
Yup that's where I come up with the idea of the solution 👍
