### ISSUE TITLE
Customize hero.heading using a react component

### ISSUE THREAD

**Issue by brunogalliez** [narative/gatsby-theme-novela#125]
I wish to add a link in `hero.heading`, but only accepts string.

**Comment by brunogalliez** [comment]
![image](https://user-images.githubusercontent.com/13022409/64387803-680ab900-d013-11e9-8917-567d456dcdee.png)

**Comment by brotzky** [comment]
In theory we could dangerouslySetInnerHTML and quickly resolve this.

Will give it a thought and see if that's the best approach.

**Comment by brotzky** [comment]
@brunogalliez you can now add links in v0.6.4
