### ISSUE TITLE
Unparsed structure in google search for Author

### ISSUE THREAD

**Issue by jcaguirre89** [narative/gatsby-theme-novela#127]
I'm getting an issue with google search, that says there is an "unparsable data structure". The author entry in articles isn't being "turned" into the author's name, but instead is uploaded as an object. Here's the output from the google search console error:

![image](https://user-images.githubusercontent.com/34848638/64444210-7646ec80-d088-11e9-826e-bcf168e473cc.png)

This is a sample from the same thing happening in the demo site:
![image](https://user-images.githubusercontent.com/34848638/64444124-48fa3e80-d088-11e9-86a1-120daaa591bf.png)

To reproduce, just go to any article and view source -> search for "author" or [objectObject].

**Comment by brotzky** [comment]
Oh shoot! Nice catch. will get try to fix that one asap.

**Comment by mabasic** [comment]
Should description be without spaces ?

**Comment by mabasic** [comment]
I'll send a PR for this.

**Comment by brotzky** [comment]
Published v0.6.5

Thanks to @mabasic.
