### ISSUE TITLE
netlifyCMS guide or intergration 

### ISSUE THREAD

**Issue by panosmakris** [narative/gatsby-theme-novela#129]
**Is your feature request related to a problem? Please describe.**
I am trying to post from the netlifycms and i get an error
"@narative/gatsby-theme-novela" threw an error while running the createPages lifecycle:
6:34:04 PM:     You must have at least one Author and Post.

**Describe the solution you'd like**
a guide or integration

**Describe alternatives you've considered**
Integration

**Additional context**

**Comment by brotzky** [comment]
I started on this but found Netlify CMS too cumbersome to setup for Novela. I'm not very familiar with the project so this was my first go. Using it in a monorepo was the main issue i ran into.

There was a WIP PR for this. 
https://github.com/narative/gatsby-theme-novela/pull/56

Would love a PR if you're able to add Netlify CMS!

**Comment by brotzky** [comment]
unfortunately, I can't help you debug your Netlify integration. I'd recommend googling around or reaching out to the Netlify CMS team.
Sorry!
