### ISSUE TITLE
custom articlePermalinkFormat

### ISSUE THREAD

**Issue by ch4nd4n** [narative/gatsby-theme-novela#130]
**Version of Novela you are using**
0.0.8

**Number of posts you have and which data source**
5

**Describe the bug**

I want to customize `articlePermalinkFormat` to :year/:month/:day/:slug it defaults to `:slug` right now
Eg. from http://localhost:8000/why-narative-loves-gatsby to http://localhost:8000/2019/01/01/why-narative-loves-gatsby

I've tried

```
plugins: [
    {
      resolve: "@narative/gatsby-theme-novela",
      options: {
        contentPosts: "content/posts",
        contentAuthors: "content/authors",
        basePath: "/",
        articlePermalinkFormat: ":year/:month/:day/:slug"
      }
    }
```

above does not work

**To Reproduce**
1. update `gatsby-config.js` with above changeset
2. yarn develop
3. open in browser, post links default to :slug

**Comment by ch4nd4n** [comment]
No it does not. I am trying `0.7.0` will follow up, but so far running into multiple issues due to version change.

**Comment by samleez** [comment]
same issue here .. any update about this? @brotzky

**Comment by brotzky** [comment]
I tested this on latest and it works.

```
  {
    resolve: "@narative/gatsby-theme-novela",
    options: {
      contentPosts: "content/posts",
      contentAuthors: "content/authors",
      rootPath: "/",
      basePath: "/",
      articlePermalinkFormat: ":year/:month/:day/:slug",
      authorsPage: true,
      mailchimp: true,
      sources: {
        local: true,
        contentful: false,
      },
    },
  },
```

<img width="1046" alt="Screen Shot 2020-01-04 at 8 11 38 PM" src="https://user-images.githubusercontent.com/8007686/71775025-7075f080-2f2e-11ea-8d89-9ff535986053.png">

If you're still having issue please let me know!
