### ISSUE TITLE
spaceid is incorrect

### ISSUE THREAD

**Issue by panosmakris** [narative/gatsby-theme-novela#131]
Hello
I am trying pass data from contentful in novela hosted on gatbsy but i get the following error

2:01:55 PM: Starting to fetch data from Contentful
2:01:55 PM: Fetching default locale
2:01:55 PM: error
2:01:55 PM: failed during stage 'building site': Build script returned non-zero exit code: 1
2:01:55 PM: Accessing your Contentful space failed.
2:01:55 PM: Try setting GATSBY_CONTENTFUL_OFFLINE=true to see if we can serve from cache.
2:01:55 PM: Endpoint not found. Check if host and spaceId settings are correct
2:01:55 PM: Used options:
2:01:55 PM: spaceId: "*********rk" - Check if setting is correct
2:01:55 PM: accessToken: "***************************************tUw8"

**Comment by panosmakris** [comment]
https://github.com/panosmakris/gatsby-starter-novela

I am sure I pretty much did everything. I even hardcoded them. It just won't pass work.

**Comment by brotzky** [comment]
You have to name the file `.env` and put in the variables there. You also have to add it to Netlify.

`.env`
```
CONTENTFUL_SPACE_ID=XXXXXXXX
CONTENTFUL_ACCESS_TOKEN=XXXXXXXXXX

```

and it Netlify add it as well.
http://d.ntve.co/cjANwR

**Comment by panosmakris** [comment]
thank you for the inputs but I can see the screenshots

**Comment by brotzky** [comment]
<img width="818" alt="Screen Shot 2019-09-13 at 9 40 39 AM" src="https://user-images.githubusercontent.com/8007686/64879323-920f3d00-d60a-11e9-82c7-52ae6a0bc7f8.png">


Here's a better image.
Make sure the variables are also defined in Netlify.

Docs: https://www.netlify.com/docs/continuous-deployment/#environment-variables

**Comment by panosmakris** [comment]
I have done that, 
I seem to fail at the gatbsy-config.js

**Comment by brotzky** [comment]
I can't help too much beyond that. I don't believe it's a bug in Novela. I think there's something wrong with how you're setting the variables locally or on Netlify.
Double check you have the right values set and double check they're being set correctly.

**Comment by panosmakris** [comment]
You are probably correct since I now get a different error

7:44:41 PM: Build ready to start
7:44:43 PM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
7:44:43 PM: build-image tag: v3.3.2
7:44:43 PM: buildbot version: 38cc4984170575781fef71bee035f0855939acb8
7:44:44 PM: Fetching cached dependencies
7:44:44 PM: Starting to download cache of 199.4MB
7:44:45 PM: Finished downloading cache in 1.233741139s
7:44:45 PM: Starting to extract cache
7:44:56 PM: Finished extracting cache in 10.465425747s
7:44:56 PM: Finished fetching cache in 11.773381032s
7:44:56 PM: Starting to prepare the repo for build
7:44:56 PM: Preparing Git Reference refs/heads/master
7:44:57 PM: Starting build script
7:44:57 PM: Installing dependencies
7:44:58 PM: Started restoring cached node version
7:45:01 PM: Finished restoring cached node version
7:45:02 PM: v10.16.3 is already installed.
7:45:03 PM: Now using node v10.16.3 (npm v6.9.0)
7:45:03 PM: Attempting ruby version 2.6.2, read from environment
7:45:04 PM: Using ruby version 2.6.2
7:45:05 PM: Using PHP version 5.6
7:45:05 PM: Started restoring cached node modules
7:45:05 PM: Finished restoring cached node modules
7:45:05 PM: Installing NPM modules using NPM version 6.9.0
7:45:30 PM: npm
7:45:30 PM:  WARN eslint-config-react-app@4.0.1 requires a peer of eslint-plugin-flowtype@2.x but none is installed. You must install peer dependencies yourself.
7:45:30 PM: npm WARN gatsby-remark-prismjs@3.3.13 requires a peer of prismjs@^1.15.0 but none is installed. You must install peer dependencies yourself.
7:45:30 PM: npm WARN react-redux@4.4.10 requires a peer of redux@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
7:45:30 PM: npm WARN slate-edit-list@0.11.3 requires a peer of slate@^0.32.0 but none is installed. You must install peer dependencies yourself.
7:45:30 PM: npm WARN slate-edit-table@0.15.2 requires a peer of slate@^0.33.3 but none is installed. You must install peer dependencies yourself.
7:45:30 PM: npm WARN ts-pnp@1.1.4 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.
7:45:30 PM: npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.
7:45:30 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/gatsby/node_modules/fsevents):
7:45:30 PM: npm
7:45:30 PM: WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:45:30 PM: npm
7:45:30 PM: WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/gatsby-source-filesystem/node_modules/fsevents):
7:45:30 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:45:30 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.0.7 (node_modules/gatsby-page-utils/node_modules/fsevents):
7:45:30 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:45:30 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
7:45:30 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
7:45:30 PM: added 100 packages from 44 contributors, removed 65 packages, updated 29 packages and audited 59429 packages in 22.757s
7:45:30 PM: found 1 moderate severity vulnerability
7:45:30 PM:   run `npm audit fix` to fix them, or `npm audit` for details
7:45:30 PM: NPM modules installed
7:45:30 PM: Started restoring cached go cache
7:45:30 PM: Finished restoring cached go cache
7:45:30 PM: unset GOOS;
7:45:30 PM: unset GOARCH;
7:45:30 PM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
7:45:30 PM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
7:45:30 PM: go version >&2;
7:45:30 PM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
7:45:30 PM: go version go1.12 linux/amd64
7:45:30 PM: Installing missing commands
7:45:30 PM: Verify run directory
7:45:30 PM: Executing user command: gatsby build
7:45:34 PM: success open and validate gatsby-configs — 0.159
7:45:36 PM: success load plugins — 2.051
7:45:36 PM: success onPreInit — 0.024
7:45:36 PM: success delete html and css files from previous builds — 0.028
7:45:36 PM: success initialize cache — 0.026
7:45:36 PM: success copy gatsby files — 0.048
7:45:36 PM: success onPreBootstrap — 0.050
7:45:36 PM: Starting to fetch data from Contentful
7:45:36 PM: Fetching default locale
7:45:36 PM: default locale is : en-US
7:45:37 PM: contentTypes fetched 13
7:45:37 PM: Updated entries  41
7:45:37 PM: Deleted entries  0
7:45:37 PM: Updated assets  1
7:45:37 PM: Deleted assets  0
7:45:37 PM: Fetch Contentful data: 644.595ms
7:45:39 PM: error #11321 PLUGIN unknown: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):
7:45:39 PM: > 1 | export CPA_TOKEN='<cpa_token>';
7:45:39 PM:     |        ^
7:45:39 PM:   2 | export SPACE_ID='<space_id>';
7:45:39 PM: Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.undefined: unknown: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):
7:45:39 PM: > 1 | export CPA_TOKEN='<cpa_token>';
7:45:39 PM:     |        ^
7:45:39 PM:   2 | export SPACE_ID='<space_id>';
7:45:39 PM: Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
7:45:39 PM: "gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:
7:45:39 PM: unknown: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):
7:45:39 PM: > 1 | export CPA_TOKEN='<cpa_token>';
7:45:39 PM:     |        ^
7:45:39 PM:   2 | export SPACE_ID='<space_id>';
7:45:39 PM: Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.undefined: unknown: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):
7:45:39 PM: > 1 | export CPA_TOKEN='<cpa_token>';
7:45:39 PM:     |        ^
7:45:39 PM:   2 | export SPACE_ID='<space_id>';
7:45:39 PM: Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.
7:45:39 PM: See our docs page for more info on this error: https://gatsby.dev/issue-how-to
7:45:39 PM: 
7:45:39 PM:   SyntaxError: unknown: Support for the experimental syntax 'exportDefaultFrom'   isn't currently enabled (1:8):
7:45:39 PM:   > 1 | export CPA_TOKEN='<cpa_token>';
7:45:39 PM:       |        ^
7:45:39 PM:     2 | export SPACE_ID='<space_id>';
7:45:39 PM:   Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the '  plugins' section of your Babel config to enable transformation.undefined: unkn  own: Support for the experimental syntax 'exportDefaultFrom' isn't currently e  nabled (1:8):
7:45:39 PM:   > 1 | export CPA_TOKEN='<cpa_token>';
7:45:39 PM:       |        ^
7:45:39 PM:     2 | export SPACE_ID='<space_id>';
7:45:39 PM:   Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the '  plugins' section of your Babel config to enable transformation.
7:45:39 PM:   
7:45:39 PM:   - index.js:6387 Object.raise
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:6387:17
7:45:39 PM:   
7:45:39 PM:   - index.js:7709 Object.expectPlugin
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:7709:18
7:45:39 PM:   
7:45:39 PM:   - index.js:10990 Object.maybeParseExportDefaultSpecifier
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:10990:12
7:45:39 PM:   
7:45:39 PM:   - index.js:10942 Object.parseExport
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:10942:29
7:45:39 PM:   
7:45:39 PM:   - index.js:10004 Object.parseStatementContent
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:10004:27
7:45:39 PM:   
7:45:39 PM:   - index.js:9900 Object.parseStatement
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:9900:17
7:45:39 PM:   
7:45:39 PM:   - index.js:10476 Object.parseBlockOrModuleBlockBody
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:10476:25
7:45:39 PM:   
7:45:39 PM:   - index.js:10463 Object.parseBlockBody
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:10463:10
7:45:39 PM:   
7:45:39 PM:   - index.js:9829 Object.parseTopLevel
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:9829:10
7:45:39 PM:   
7:45:39 PM:   - index.js:11341 Object.parse
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:11341:17
7:45:39 PM:   
7:45:39 PM:   - index.js:11377 parse
7:45:39 PM:     [repo]/[@babel]/parser/lib/index.js:11377:38
7:45:39 PM:   
7:45:39 PM:   - normalize-file.js:166 parser
7:45:39 PM:     [repo]/[@babel]/core/lib/transformation/normalize-file.js:166:34
7:45:39 PM:   
7:45:39 PM:   - normalize-file.js:100 normalizeFile
7:45:39 PM:     [repo]/[@babel]/core/lib/transformation/normalize-file.js:100:11
7:45:39 PM:   
7:45:39 PM:   - index.js:44 runSync
7:45:39 PM:     [repo]/[@babel]/core/lib/transformation/index.js:44:43
7:45:39 PM:   
7:45:39 PM:   - transform.js:43 transformSync
7:45:39 PM:     [repo]/[@babel]/core/lib/transform.js:43:38
7:45:39 PM:   
7:45:39 PM:   - extract-imports-and-exports.js:51 module.exports
7:45:39 PM:     [repo]/[remark-mdx]/extract-imports-and-exports.js:51:3
7:45:39 PM:   
7:45:39 PM: 
7:45:39 PM: Skipping functions preparation step: no functions directory set
7:45:39 PM: Caching artifacts
7:45:39 PM: Started saving node modules
7:45:39 PM: Finished saving node modules
7:45:39 PM: Started saving pip cache
7:45:39 PM: Finished saving pip cache
7:45:39 PM: Started saving emacs cask dependencies
7:45:39 PM: Finished saving emacs cask dependencies
7:45:39 PM: Started saving maven dependencies
7:45:39 PM: Finished saving maven dependencies
7:45:39 PM: Started saving boot dependencies
7:45:39 PM: Finished saving boot dependencies
7:45:39 PM: Started saving go dependencies
7:45:39 PM: Finished saving go dependencies
7:45:39 PM: Error running command: Build script returned non-zero exit code: 1
7:45:39 PM: Failing build: Failed to build site

**Comment by brotzky** [comment]
Ah strange, check out this
```
7:45:39 PM: error #11321 PLUGIN unknown: Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (1:8):
```

I'd google around to see what that means. I've never run into that before.
