### ISSUE TITLE
Add Support for Behance object in `social` array of gatsby-config.js

### ISSUE THREAD

**Issue by ismailElazizi** [narative/gatsby-theme-novela#134]
As a designer, I want to be able to add my Behance portfolio as a Social Icon to Navigation Footer.

so user can add

{
  name: `behance`,
  url: `https://www.behance.net/ismailelazizi`,
},
to gatsby-config.js and a Behance Social Icon will display on the Navigation Footer.

**Comment by brotzky** [comment]
https://github.com/narative/gatsby-theme-novela/pull/135

Upgrade to latest and you can now use behance. by the way, the "name" is not required anymore and as it checks the domain name instead.
