### ISSUE TITLE
How do I modify html of author page?

### ISSUE THREAD

**Issue by sabbiu** [narative/gatsby-theme-novela#136]
Which file do I need to edit? I want to make few changes to author page.

**Comment by nnnkit** [comment]
You can use [Gatsby shadowing](https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/) to overwrite the existing layout or component.

You need to shadow this component https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/src/templates/author.template.tsx

**Comment by brotzky** [comment]
@sabbiu which section of the author's page?

**Comment by sabbiu** [comment]
@brotzky top part of the author page
![image](https://user-images.githubusercontent.com/19733021/65120593-9920bb80-da0d-11e9-8a8b-22070e44ff77.png)
I wanted to add more details about author (and maybe remove the blogs written by him)

**Comment by brotzky** [comment]
I'd recommend cloning down this repo and learning which components make up which section.

Adding details about the author are added in the author data
and removing the blogs written by them would be done by removing the articles list in the author.template.tsx
