### ISSUE TITLE
Add Title and Description meta-data to author page?

### ISSUE THREAD

**Issue by soumikcv** [narative/gatsby-theme-novela#139]
Does passing the author name as title and bio as description on SEO component in author Template make more sense? 
From SEO perspective as well, it should make more sense right?

Or is it something you want to keep open for customisation using component shadowing?

**Comment by brotzky** [comment]
Yes, you're right. That does make more sense.

I think it's a solid default we can use instead of the current implementation.

**Comment by soumikcv** [comment]
That's awesome! Can I send a PR? My beginner brain has been trying to get into more open source.
