### ISSUE TITLE
[Bug] Mobile scrolling on on article post jumps

### ISSUE THREAD

**Issue by brotzky** [narative/gatsby-theme-novela#14]
When scrolling on mobile in some browsers it jumps unexpectedly.

Specifically on Firefox Focus iOS

**Comment by sw-yx** [comment]
😅 i wouldnt call this high priority, i thought this was a more general mobile issue until i tried on other browsers and found it was fine.

**Comment by brotzky** [comment]
I can’t seem to recreate it.
iPhone 7s, Firefox focus latest.

Could you confirm it’s still jumping?
https://novela.narrative.co

**Comment by sw-yx** [comment]
yes, still jumping. iphone xr, firefox focus latest (8.1.2)

low priority i guess but weird one!

**Comment by brotzky** [comment]
low priority. Shawn, just use a better browser 🤣. I don't have a device that can reproduce so going to close for now..
