### ISSUE TITLE
TypeError: Cannot destructure property `local` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#141]
**Version of Novela you are using**
0.7.0
**Number of posts you have and which data source**
Ten local posts.

**Describe the bug**
The `sources` object in `gatsby-theme-novela` in `gatsby-config.js` is required. This would normally be fine but this is not described in the [documentation](https://github.com/narative/gatsby-theme-novela#step-3-using-narativegatsby-theme-novela).

A better fix may be to default `options.sources.local` to true with it only getting overwritten if `options.sources.contentful` is `true`.

**To Reproduce**
1. Follow the documentation for installation.
2. Run `gatsby develop`
3. Get error:

```
$ gatsby develop

 ERROR 

UNHANDLED REJECTION Cannot destructure property `local` of 'undefined' or 'null'.

  TypeError: Cannot destructure property `local` of 'undefined' or 'null'.
  
  - gatsby-config.js:6 module.exports
    [webdev-coach-blog]/[@narative]/gatsby-theme-novela/gatsby-config.js:6:12
  
  - index.js:38 resolveTheme
    [webdev-coach-blog]/[gatsby]/dist/bootstrap/load-themes/index.js:38:19
  
  - index.js:97 
    [webdev-coach-blog]/[gatsby]/dist/bootstrap/load-themes/index.js:97:22
```

**Expected behavior**
Better documentation or `sources.local` to be `true` by default

**Comment by brotzky** [comment]
The solution you described should be the intended behaviour. Will give this one a fix. Thanks for the report!

**Comment by brotzky** [comment]
Thanks so much for the fix
