### ISSUE TITLE
Document commitlint requirements in .CONTRIBUTING.md

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#146]
**Is your feature request related to a problem? Please describe.**
I love the addition of commitlint! It'll standardize commits (plus it's a fun toy to play with). However, it may be frustrating for some devs to a) find where the rules for committing are (`.commitlintrc.yml`) and understand how to parse those rules.

**Describe the solution you'd like**
I'd like `CONTRIBUTING.md` to describe the rules set forth my `commitlintrc.yml`

**Additional context**
I think this'd be a great first issue for those looking to get started with open-source contributions.

**Comment by brotzky** [comment]
When you write an incorrect commit it should link you to the docs in the CLI?
But we can also add better documentation or a direct link to their docs.
Thanks for the feedback.

**Comment by AryanJ-NYC** [comment]
@brotzky I can confirm that it does lead me to their docs. I meant more of the specific rules that Narative set forth. Just an idea. It may be overkill and is definitely a low priority ticket.

Hacktoberfest is coming. 🤔🤔

**Comment by jpvalery** [comment]
@AryanJ-NYC No particular rules - we added commitlint to ensure lerna would publish the right number version more than anything else :) 

Let me know if I can help with anything related to that!
