### ISSUE TITLE
If I add a new field in frontmatter of the blog posts how to add it to the `Article` schema

### ISSUE THREAD

**Issue by nnnkit** [narative/gatsby-theme-novela#149]
I am trying to implement a category page for this theme and added a new field in the markdown file. How can I add that field in the `Article` schema using child theme.

**Comment by brotzky** [comment]
That's a solid question and I'm not entirely sure how a child theme would handle this.
You'd have to modify Novela in order to do this, but don't quote me on that.

**Comment by nnnkit** [comment]
@brotzky I was able to figure this out. I did it by querying the parent element of `Article` i.e `Mdx` and using `onCreateNode` to add a field using `createNodeField`. Example:

```js
exports.onCreateNode = async ({ node, actions, getNode }) => {
  const { createNodeField } = actions;
  function isPosts(path) {
    return path.includes('posts');
  }
  if (node.internal.type === `Article`) {
    const parentNode = getNode(node.parent);
    if (
      parentNode &&
      parentNode.internal.type === 'Mdx' &&
      isPosts(parentNode.fileAbsolutePath)
    ) {
      createNodeField({
        node,
        name: `tags`,
        value: parentNode.frontmatter.tags || [],
      });
    }
  }
};
```

**Comment by brotzky** [comment]
That's awesome @nnnkit. Glad you were able to figure it out!
