### ISSUE TITLE
[Error][Docs] Default column mismatch under Data Model

### ISSUE THREAD

**Issue by mehtavishwa30** [narative/gatsby-theme-novela#15]
# Description

Noticed a small error in documentation and would like to make a PR to help correct it.

## Note

Under the `Data Model` section, the Default column values for `contentAuthors` and `contentPosts` have been swapped as seen in the screenshot below:

## Current 

![Screen Shot 2019-08-04 at 2 15 31 PM](https://user-images.githubusercontent.com/32997409/62421653-e72e6980-b6c2-11e9-9928-7d89791031b9.png)

## Expected 

contentAuthors: content/authors
contentPosts: content/posts

**Comment by brotzky** [comment]
It has been fixed!
