### ISSUE TITLE
Use IntersectionObserver API in Progress Component

### ISSUE THREAD

**Issue by dennismorello** [narative/gatsby-theme-novela#150]
**Is your feature request related to a problem? Please describe.**
At the moment, the Progress component uses two event listeners (one for the `scroll` event and one for the `resize` one) on the `window` object to get information about the amount the user has scrolled the page. This works fine, but this is a synchronous solution.

**Describe the solution you'd like**
It would be nice if the Progress component used the IntersectionObserver API, which is now supported by all major web browsers. This would not require using two distinct event handlers, and this is an asynchronous way to handle the problem.

**Describe alternatives you've considered**
None.

**Additional context**
[MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) for reference. There is also a [React package](https://www.npmjs.com/package/react-intersection-observer) that makes it easier to use this API.

**Comment by brotzky** [comment]
Agreed. IO is the right tool for this job now. Would love some help on this one :)

**Comment by brotzky** [comment]
Actually, reviewing the IO API there might not be a good way to find the _progress_ of scroll over an element? For example we can detect which percentage is being viewed, but not the percent from hte top of the content. 
For now I think the 20ms throttle is handling it nicely :)
