### ISSUE TITLE
Hero is missing for [post] ─ Netlify CMS integration

### ISSUE THREAD

**Issue by betodasilva** [narative/gatsby-theme-novela#151]
Hi guys,
I'm trying to integrate with netlify CMS and everything works fine right now except the hero image.

I use the [image widget](https://www.netlifycms.org/docs/widgets/image/) to select the hero image, and it gives me an absolut path to `/static/assets/[file-name.extension]` where the file is stored.

When I try to build the console says the _hero field is missing._

Could you help me solve this?

*Note that as I'm using netlify cms it's not possible to create subfolders for posts.
So the current structure is shown below:
```
novela-site
    ├── content
    │ └── posts
    │     └── 2020-01-01-my-first-novela-post.md
    ├── node_modules
    ├── gatsby-config.js
    └── package.json
    ├── static
    │     └── assets
    │         └── file-name.extension
```

**I use the same widget to attach images to the article body and it works fine. The problem is the image transformation doesn't occur.

**Comment by brotzky** [comment]
Have you tried removing the `local` source? It's on by default.
It might not be related to Netlify.

**Comment by betodasilva** [comment]
Yeah, tried right now but it shows more errors than before :cry:

**Comment by betodasilva** [comment]
**To Reproduce**
Steps to reproduce the behavior:
1. Move the hero image to any folder inside static. i.e /static/assets
2. Add that path to the hero field. i.e `hero: /assets/hero.jpg`

**Comment by brotzky** [comment]
I believe the path should be relative from the file to the asset. So your `hero` path is incorrect?
Could you try updating it to something like '.../../static/assets/file-name.extension`?
Any reason you're putting the hero files in a different folder than the post? Is this a Netlify CMS thing?

**Comment by betodasilva** [comment]
> Could you try updating it to something like .../../static/assets/file-name.extension?
I've already tried

> Is this a Netlify CMS thing?
Yeah, definitely.

[https://github.com/netlify/netlify-cms/issues/513](https://github.com/netlify/netlify-cms/issues/513)

**Comment by brotzky** [comment]
Ahhhh, that's too bad. Not sure I can help beyond that as it seems to be out of scope of Novela. Sorry, @betodasilva.

**Comment by betodasilva** [comment]
No problem mate @brotzky 
I'll see if I can do some workaround.

Thanks for this amazing theme.

**Comment by mostafachatillon** [comment]
@betodasilva hi, did you solve this issue? Does it work for you now?
