### ISSUE TITLE
How to display pages fetched from Drupal

### ISSUE THREAD

**Issue by Vacilando** [narative/gatsby-theme-novela#152]
This is one of the best Gatsby themes to date!

Our content however is neither in local files or in Contentful, but in Drupal 8. We can easily write GraphQL queries to get the pages from Drupal. 

The question is how do we get the Novela theme to display the content we got from Drupal?

**Comment by brotzky** [comment]
Thanks, Vaciland <3!

We'd need to setup Drupal as a data source within the theme similarly to Contentful. Personally, I have no experience with Drupal so won't be much use.
If you'd like to attempt it, you can check out how Contentful is setup and then do something similar for Drupial.
