### ISSUE TITLE
[Help] Helmet SEO / Twitter card metadata not updating on build

### ISSUE THREAD

**Issue by duncanjbain** [narative/gatsby-theme-novela#154]
Hi guys, I'm pretty new to both React and Gatsby. I've got a demo site up and running, but the SEO and Twitter metadata seems to still be using images and text from novela.narative.co. 

A link to the post https://cranky-carson-a05f00.netlify.com/my-first-post-using-novela-by-narative and an example of the metadata below:

`<meta data-react-helmet="true" name="twitter:image" content="https://novela.narative.co/static/1b61637f12a98a58b5a2fc6bbd48a064/86173/hero.jpg"/>`

I've looked through the theme SEO component files, but can't seem to find anything obvious! My site repo is https://github.com/duncanjbain/duncanbain.io.

Any help appreciated!

**Comment by brotzky** [comment]
Check out the `www` repo as an example of how to set the preview image.
https://github.com/narative/gatsby-theme-novela/tree/master/www/static

You'd have to replace that, I believe. Let me know if it's still unclear.

**Comment by duncanjbain** [comment]
Hi @brotzky, thanks for the response!

I think for the Twitter card preview, the header tags are generated and use the hero image specific to each post, rather than a static single image.

For example, have a look at the Twitter tags on https://novela.narative.co/understanding-the-gatsby-lifecycle-with-narative, they use the hero image as the preview image.

My site seems to be generating preview tags that link to novela.narative.co/static, rather than my own site images.

**Comment by duncanjbain** [comment]
Looks like it's working now, might have just needed another build!
