### ISSUE TITLE
Social Stackoverflow / custom value

### ISSUE THREAD

**Issue by MatthewTrout** [narative/gatsby-theme-novela#156]
Would be useful to have **stackoverflow** as a social option, but perhaps more pertienent, is there any simple way the social behaviour could be adapted to accept custom social configuration as part of the `gatsby-config.js` for example, such as icon / colours etc?

Just wanted to add that this is a stunning theme, and a really great piece of work!

**Comment by brotzky** [comment]
Thanks Matthew!

We can add stackoverflow! Agreed on the custom icons... just need to find the time to build something to handle that.

Do you happen to have their icon?

**Comment by MatthewTrout** [comment]
Yeah that's fair! I'll take a look at doing a PR tomorrow, or I'll link an appropriate icon here.

**Comment by brotzky** [comment]
Thanks a ton, @MatthewTrout! Merged.
