### ISSUE TITLE
Safari 12.1 macOS unresponsive

### ISSUE THREAD

**Issue by MatthewTrout** [narative/gatsby-theme-novela#158]
**Version of Novela you are using**
0.8.2

**Number of posts you have and which data source**
Local, 1 post

**Describe the bug**
On Safari 12.1, macOS 10.13.6, 
<img width="245" alt="Screen Shot 2019-10-01 at 21 12 46" src="https://user-images.githubusercontent.com/4378253/65997652-a6b85580-e491-11e9-853e-497eefb2d404.png">
When on any page (home, an individual post, etc) the cpu of my machine spikes, the page becomes eventually unresponsive, and safari reports that the page is using significant energy.  Using Safari dev tools, it becomes clear that there's a dom patch happening constantly, perhaps due to change detection of a specific component, where a bug exists specifically in Safari?  I can't identify the component but the following image should illustrate the problem:
![safari](https://user-images.githubusercontent.com/4378253/65997881-1e868000-e492-11e9-98f3-ad2414762806.gif)

To confirm, this happens for the demo instance linked to by this repo also.

**Comment by brotzky** [comment]
This is wild. Thanks for bring it up. Definitely need to look this up. Does the same occur on novela.narative.co for you?

**Comment by MatthewTrout** [comment]
Looks like that's a yes!  I made sure all plugins were disabled also, just in case something was getting a bit excited with dom manipulation.

![safari2](https://user-images.githubusercontent.com/4378253/66112949-b3d56180-e5c3-11e9-8fab-b6f8740a101f.gif)

**Comment by brotzky** [comment]
Thanks for the gif! Appreciate it. Will have to dive into this one. Damn Safari..

**Comment by MatthewTrout** [comment]
No worries! Agreed, Safari is a pain.  To be honest I deliberately hold back on macOS Safari updates, just to purposefully find issues with it in development, so that I know it's probably the worst situation a page can appear 😂

**Comment by brotzky** [comment]
Seems to have fixed itself on latest Safari: https://novela.narative.co
I can't reproduce it on Version 13.0.4 (15608.4.9.1.3).
