### ISSUE TITLE
Support for custom links in the header

### ISSUE THREAD

**Issue by vikingmute** [narative/gatsby-theme-novela#159]
Hey everyone,
Does this theme support custom links (eg, About, Contact ...) in the header besides the dark/light mode switcher?

Thank you.

**Comment by brotzky** [comment]
No, not right now. Are you looking to build around this theme or integrate it with some Other Gatsby themes?

**Comment by vikingmute** [comment]
@brotzky I just started using Gatsby and try to do some customization around this theme.

**Comment by brotzky** [comment]
I'd recommend forking this theme and building a site around it if you want. There's no ability to add custom links to the header right now.

**Comment by vikingmute** [comment]
Thx @brotzky, I'll close this issue for now.

**Comment by vikingmute** [comment]
@brotzky Today I tried to make component shadowing work from your document ,https://github.com/narative/gatsby-theme-novela#component-shadowing 
My custom logo works like a charm, so I tried to do the same thing for the links part.
 I found this area in **/components/Navigation/Navigation-header.tsx**
So I created a file here: **src/@narative/gatsby-theme-novela/components/Navigation/index.js**, but it seems shadowing is not working, could you help me check what's the issue?

**Comment by jpvalery** [comment]
@vikingmute check https://github.com/MontrealPhotoClub/montrealphotoclub.en/blob/master/src/%40narative/gatsby-theme-novela/components/Navigation/Navigation.Header.tsx - I added an icon there and you could add links at L70 with a `<Link to >` thingy.

**Comment by vikingmute** [comment]
@jpvalery  thanks so much, I found my file name is incorrect, I have to name it exactly the same with the original file: Navigation.Header.tsx. Now it works fine.

**Comment by brotzky** [comment]
Thanks @jpvalery
