### ISSUE TITLE
Not able to use shadowing on data.query.js file

### ISSUE THREAD

**Issue by nnnkit** [narative/gatsby-theme-novela#160]
I am trying to shadow the `data.query.js` file to get the desired output. But it's not working. Can you please help @ChristopherBiscardi

**Comment by brotzky** [comment]
@nnnkit could you link me to the repo you're working in? It's possible you have an incorrect path that's causing shadowing to fail.

**Comment by wilmanbarrios** [comment]
Hi @brotzky, I have the same problem, can you check my src folder to see if I am doing right the shadowing of the data.query.js file?

![Screenshot from 2019-10-10 10-37-52](https://user-images.githubusercontent.com/20175215/66580122-e1825380-eb4b-11e9-98b3-c91742b359ef.png)

**Comment by brotzky** [comment]
That looks like the correct shadowing. This might actually be a bug within Gatsby Theme's Component Shadowing itself.

I am assuming you're exporting correcting from `data.query.js`?

Correct path:
http://d.ntve.co/JI4fM0

**Comment by wilmanbarrios** [comment]
Sorry for the late response.

Yes @brotzky, i just copy the `data.query.js` file from the source, and just did my modification, and  then run `yarn clean && yarn dev`. 

But I don't get it to work, do you have any idea way?

Here is the export part.

![Screenshot from 2019-10-15 12-47-35](https://user-images.githubusercontent.com/20175215/66852052-1b879700-ef4a-11e9-85b5-23a766371d52.png)

**Comment by wilmanbarrios** [comment]
@brotzky I was reading about shadowing, and it sames that we only can shadow files in the `src` folder, and since the `data.query.js` file is outside of the `src` its no going to work.

Is there another way to modify the `data.query.js` file or a way to change the format and locale of the published date of the articles?

That's my end goal, change the format and locale of the published date of the articles.

**Comment by brotzky** [comment]
I can move it into the `src` file if that's an easy win.

I think that's a better approach then somehow making it configurable without shadowing.

**Comment by wilmanbarrios** [comment]
>I think that's a better approach then somehow making it configurable without shadowing.

I think the same, that would be a win.

**Comment by wilmanbarrios** [comment]
>I can move it into the `src` file if that's an easy win.

Do you need any help @brotzky?

**Comment by brotzky** [comment]
If you'd like to PR it that would be awesome :)

**Comment by wilmanbarrios** [comment]
Awesome i'm on it. :+1:

**Comment by wilmanbarrios** [comment]
I just send the PR #176 take a look.

**Comment by jmigdelacruz** [comment]
Hi @wilmanbarrios has the merged PR fixed this?

I'm trying to do the same as you and update the date format. When i try and shadow the data.query.js file in the same folder you have it on as on your screenshot, still nothing happens even after i do a `gatsby build/develop`

Any ideas?

**Comment by wilmanbarrios** [comment]
@jmigdelacruz no dude.

I ended doing a shadowing of the component that render the published date and then applied my custom format based on the the format of the date that is coming from GraphQL.

I think that is something with the path resolution in the theme itself, but i'm not sure.

**Comment by brotzky** [comment]
Hmmm, im not entirely sure as well. Shadowing is a bit of a blackbox when it doesn't work properly so it's hard for me to fix it.

**Comment by LekoArts** [comment]
This will be fixed by https://github.com/gatsbyjs/gatsby/pull/17681

**Comment by wilmanbarrios** [comment]
Looking forward to that PR, thanks.

**Comment by wilmanbarrios** [comment]
The PR just got merged. But still changing the graphQL query not work.

**Comment by brotzky** [comment]
Maybe we also have to update Novela's Gatsby version?

**Comment by wilmanbarrios** [comment]
I'm not sure, but we could try and see it works.

**Comment by aabosh** [comment]
Any update on this?

**Comment by luisarbezerra** [comment]
Any update?

**Comment by brotzky** [comment]
@aabosh and @luisarbezerra you're both welcome to fix it yourselves and submit a PR ❤️
