### ISSUE TITLE
Shadowing Site Header Metadata

### ISSUE THREAD

**Issue by duncanjbain** [narative/gatsby-theme-novela#161]
Hello,

I'm trying to remove the following from my sites header metadata section:
`shrink-to-fit=no`

I've searched the repository for this piece of code, and it's located in gatsby-theme-novela/www/src/html.tsx. I've tried shadowing this file, but I'm not having any luck. 

What is the purpose of the www folder? I thought shadowing should be done by creating a file in a directory such as site_root/src/@narative/gatsby-theme-novela/components/SEO/SEO.tsx, this file seems to create the rest of the site metadata such as Twitter bookmark data etc.

It looks like that on site build, it takes both www/src/htm.tsx and gatsby-theme-novela/components/SEO/SEO.tsx to build the header section of the page.

Any help is appreciated!

**Comment by brotzky** [comment]
`www` is so we can run it locally and develop the theme against a site that is using it. You can't run only the theme, you have to use it in a site to be able to build it.

Ill check out why shadowing isn't working.

What's the reasoning for removing `shrink-to-fit=no`? Maybe it's worth removing it by default.

**Comment by duncanjbain** [comment]
> `www` is so we can run it locally and develop the theme against a site that is using it. You can't run only the theme, you have to use it in a site to be able to build it.
> 
Aha, that's what I thought, shortly after I posted the question!

> Ill check out why shadowing isn't working.
> 
I can't seem to see why it shouldn't work. But it looks like the theme seems to be using the www/src/html.tsx file for the HTML head element generation, rather than gatsby-theme-novela/src/components/SEO/SEO.tsx. There is no mention of `shrink-to-fit=no` in SEO.tsx, only html.tsx.

> What's the reasoning for removing `shrink-to-fit=no`? Maybe it's worth removing it by default.
>
When running a Lighthouse audit for PWA's I was getting a fail on the viewport being a different size to the window size, one of the suggestions I found was that `shrink-to-fit=no` might be a possible cause. 

https://github.com/h5bp/html5-boilerplate/issues/2102

It looks like it was originally there due to the way Safari handled overflow, but it looks like it's no longer required.

**Comment by brotzky** [comment]
Sounds reasonable to have as a default, although maybe it doesn't do anything as you mentioned. Open to a PR for this ☺️!

**Comment by duncanjbain** [comment]
> Sounds reasonable to have as a default, although maybe it doesn't do anything as you mentioned. Open to a PR for this ☺️!

So turns out the reason I could only find a mention of `shrink-to-fit=no` in the repo was in the www/src/html.tsx file was because it's part of the default Gatsby default-html.jsx file. If I want to open a PR to make the change to remove it, it'll have to be on the Gatsby repo, haha!

**Comment by brotzky** [comment]
No need for PR, maybe.
Check this out: https://www.gatsbyjs.org/docs/custom-html/

**Comment by duncanjbain** [comment]
> No need for PR, maybe.
> Check this out: https://www.gatsbyjs.org/docs/custom-html/

Yeah, that's the link that lead me to looking at my .cache/default-html.js file, which contains the `shrink-to-fit=no`. Issue closed I guess!

**Comment by brotzky** [comment]
Damn :| Well, hope you're able to resolve it eventually on their side! Thanks for the info about that property.
