### ISSUE TITLE
Logo link should go to base path

### ISSUE THREAD

**Issue by bntzio** [narative/gatsby-theme-novela#163]
Let's suppose I set the `basePath` to be `/blog` or `/home` for my site in the `gatsby-config.js` novela theme plugin options.

So my index would be `mysite.com/blog`.

Right now if I navigate through the posts (or any other pages) and then I want to go back to the index (by clicking the logo) I always go to the `/` path, so there's no way to go to the index path by clicking a DOM element in my site.

![novela](https://user-images.githubusercontent.com/3136873/66363363-a9acbd80-e94b-11e9-98b5-15fba59bfa7c.gif)

I think we should query the `@narative/gatsby-theme-novela` plugin options to get the `basePath` and set that path as the link for the logo.

That way we can click on the logo and go to the actual home of the site as defined by the base path :)

**Comment by bntzio** [comment]
I just submitted a PR that solve this (#164)

**Comment by bntzio** [comment]
Although we can let the user define the root or index path of their site by specifying a `rootPath` or `indexPath` option in the theme config.

That way novela can offer the flexibility to choose at what path should the theme be installed (as defined by the `basePath`) and choose the root/index path (defined by `rootPath` or `indexPath`) to set that as the logo link of their site, thus redirecting to that index path instead when clicking on the logo.

Because people may want to have their novela site up at `/blog` and their main site at `/`, and redirecting to `/` when clicking the logo is good for them, but others may want to redirect to `/blog` instead of `/`.

This way we can offer the flexibility to the user to decide what's their root or index path, without strictly forcing them to `/` or the `basePath`.

I can make a change to the PR to use a `rootPath` or `indexPath`, what do you think it's best @brotzky?

**Comment by brotzky** [comment]
Agreed, `rootPath` makes sense to me. Thanks so much for the PR.

**Comment by bntzio** [comment]
Done! 😄
