### ISSUE TITLE
Dynamic logo fill color

### ISSUE THREAD

**Issue by perteraul** [narative/gatsby-theme-novela#165]
Thanks for the amazing work, @brotzky!

I've gone through the documentation and examples and I cannot find a way to use the Theme-UI variables as a fill={'primary'} for the Logo/index.js component shadowing.

What I'm trying to do is to change the fill color of some svg path's when the dark mode kicks in. Is there a way of doing this?

**Comment by perteraul** [comment]
Should also mention that passing the fill={'primary'} doesn't work.

**Comment by perteraul** [comment]
That did it! Thank @jpvalery.

**Comment by brotzky** [comment]
Thanks @jpvalery

**Comment by stanstarks** [comment]
Hi, @jpvalery . I am new to web dev. Could you be so kind to point me to some link about how to generate a Logo.tsx like the one on your site? Thanks in advance!
