### ISSUE TITLE
Change the way that ArticleMeta render the published date and reading time

### ISSUE THREAD

**Issue by wilmanbarrios** [narative/gatsby-theme-novela#167]
Hey folks,

I want to change the way that ArticleMeta render published date and reading time, is there a way to accomplish that? :thinking:

**Comment by brotzky** [comment]
This can be configured within the article MDX if I remember correctly. It's possible reading time can't be manually overriden. What's the reasoning for wanting to change those?

Check this out: https://github.com/narative/gatsby-theme-novela#post

**Comment by wilmanbarrios** [comment]
I wanted to remove de reading time, and then remenbered that i could use component shadowing to adjust that little part.

**Comment by brotzky** [comment]
Awesome! If you have issues shadowing let me know.

**Comment by wilmanbarrios** [comment]
I want to change the date format of the allArticle query, is there a easy way to change that
