### ISSUE TITLE
Custom 404 pages

### ISSUE THREAD

**Issue by jaywick** [narative/gatsby-theme-novela#168]
This is more of a question –

I am trying to extend theNovella theme with a **custom 404 page**. I've tried adding a `404.tsx` which is unfortunately not picked up. I am happy to submit a PR to simplify the process if it requires some coding. But was hoping for some pointers at where to look :)

Apologies if this is the wrong place to post.

**Comment by brotzky** [comment]
Can you link me to the code you're writing?

The 404 page should be handled the same as any Gatsby page. It's not part of Novela on purpose.
