### ISSUE TITLE
[Bug] FooterGradient

### ISSUE THREAD

**Issue by keyfer** [narative/gatsby-theme-novela#17]
Footer gradient causes some unexpected transitions in colour:
![My+first+post+using+Novela+by+Narative+2019-08-04+15-35-33](https://user-images.githubusercontent.com/15006490/62428269-aee05880-b6cd-11e9-8c11-43c90d404a8b.jpg)

**Comment by brotzky** [comment]
Fixed in latest, will release in 1-2 days.

**Comment by brotzky** [comment]
v0.0.4 now fixed gradient issue
