### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by mehrdad-shokri** [narative/gatsby-theme-novela#172]
Thanks for your efforts in building this theme.  
Is there a way to make the theme rtl through configs?  
If not can you give a brief overview of how I can change core codebase to accomplish this?

**Comment by brotzky** [comment]
Thanks so much!
Unfortunately, RTL is not supported right now.
I think a quick win would be inserting text-direction property globally in the CSS. You could even do this without modifying the theme's codebase.
The proper implementation would touch most of the codebase as we'd want to add `dir="rtl"` and a way to configure RTL as an option.

**Comment by mehrdad-shokri** [comment]
Generally adding rtl suuport for a site requires manual iteration of all pages and changing it's design.  
setting ``text-direction`` property ``right`` is not a practical approach. It generally requires changing page layout direction. 
Maybe we can add a ``direction`` option in ``gatsby-config.js`` and I figure out a way to add rtl support for this theme? Would that be good for you? I mean would you accept that pr to add rtl support for this theme?

**Comment by brotzky** [comment]
Would love to learn more about supporting text direction. a PR to allow Novela to support text direction would be really appreciated.

**Comment by mehrdad-shokri** [comment]
Thanks. will try to separate some time to start working on it. Just for a brief overview of styling, what styling strategy have you taken? Do you use JSS?

**Comment by mehrdad-shokri** [comment]
To be more accurate what I'm trying to accomplish is more than text direction, with adding rtl support, for instance most of the ``margin-rights`` turns to ``margin-left`` and so on. So It wouldn't be just text-direction. Would that be ok with you?

**Comment by brotzky** [comment]
Yes, as long as it's properly supporting the feature that's ok.

**Comment by brotzky** [comment]
I'm going to close this issue for now. full RTL support is a large task and we don't have the resources to tackle it right now. If someone reading this needs RTL support I encourage you to fork Novela and try to implement it yourself. Would appreciate a pull request back if it goes well for you :)
