### ISSUE TITLE
Question: How to Centre Site Text and add html underneath it.

### ISSUE THREAD

**Issue by mannp** [narative/gatsby-theme-novela#174]
Great theme, thanks for your work :)

Is it possible to have the site text centered rather than left justified at all? and also where to put additional text below the site title?

I have read this -> https://www.gatsbyjs.org/docs/custom-html/ and it seems snippets of info without any explanation :-/

Thanks in advance

btw your site menu is very cool too :)

Also, I notice from your own website you have fancy react components after the site name text, before getting down to the posts.

I wondered what the best way is to do that (figma?)

**Comment by brotzky** [comment]
I'm not completely following what you'd like to do? What do you mean by "How to Centre Site Text and add html underneath it". Do you have any screenshots or examples of what you'd like to achieve?

Appreciate the kind words about narative.co.
You can see the codebase to our site at https://github.com/narative/narative.co

**Comment by mannp** [comment]
I'd like to center the hero heading text on the main page, just like the text for each individual post.

Ideally I was wanting to add the ability for an mdx file to be displayed under the hero heading text and before the posts start.

I am trying to create a simple landing page, so to have the hero heading and some simple text underneath that, then comes the posts.

**Comment by brotzky** [comment]
There's no way to configure the text to be centered right now. A workaround could be this:


in your `gatsby-config.js`
```    
hero: {
      heading: `<span style="text-align:center">Welcome to Novela, the simplest way to start publishing with Gatsby.</span>`,
      maxWidth: 99999,
    },
```
This may work, but I haven't tested it.

**Comment by mannp** [comment]
> maxWidth: 99999

This has the most impact, albeit not looking as good on the spacing as before, but its an improvement on the text, thanks :)

**Comment by brotzky** [comment]
Great :)))
