### ISSUE TITLE
Highlighted text to share does not carry over to LinkedIn

### ISSUE THREAD

**Issue by aashanand** [narative/gatsby-theme-novela#175]
**Version of Novela you are using** Whichever version is on novela.narative.co

**Number of posts you have and which data source**
(Local, Contentful options) N/A

**Describe the bug**
When text on a blogpost is highlighted and shared to Twitter, the highlighted text carries over into the Twitter window. For share on LinkedIn, the behavior is different. The highlighted text does not make it into the LinkedIn post.

**To Reproduce**
1. Go to https://novela.narative.co/understanding-the-gatsby-lifecycle-with-narative
2. Highlight any text from the post body
3. Click the LinkedIn logo
4. The share to LinkedIn popup that opens does not contain the text

**Expected behavior**
Behavior for sharing to LinkedIn should be similar to behavior for sharing to Twitter. The highlighted text should go in the Share message body.

**Screenshots**
N/A

**Browser**
Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by brotzky** [comment]
This appears to be a limitation of LinkedIn. I can't seem to find a way to carry over and insert the body text for LinkedIn. Do you have any idea how to get pre-fill linkedin text links? If you do I'll reopen this issue and fix it!

**Comment by aashanand** [comment]
Hmm. It does appear to be a limitation of LinkedIn. [This documentation](https://docs.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/plugins/share-plugin) for the LinkedIn Share button doesn't mention anything about passing text over as part of the share itself - only a URL.
