### ISSUE TITLE
Trouble using self-hosted fonts with @font-face

### ISSUE THREAD

**Issue by gizzidan** [narative/gatsby-theme-novela#177]
**Version of Novela you are using**
I forked `gatsby-theme-novela` yesterday (October 16, 2019)

**Number of posts you have and which data source**
Local (only posts are the ones form the fork)

**Describe the bug**
I'm having an issue using a local font. I've tried adding to the `@narative/gatsby-theme-novela/src/styles/global.ts` file:

` @font-face { `
    `font-family: "Arg";`
   ` font-weight: 400;`
   ` font-style: normal;`
   ` src: url("@narative/gatsby-theme-novela/src/static/Aaargh-webfont.woff") format("woff");
  }`

When I launch the development server I get a `Failed to decode downloaded font` error and `OTS parsing error: invalid version tag` on Chrome.

**To Reproduce**
1. Upload font to project folder. I made a `static` folder and added my font there `@narative/gatsby-theme-novela/src/static/`
2. Go to `@narative/gatsby-theme-novela/src/styles/global.ts` and use `@font-face` to add a font.
2. Declare your `body {font-family: FONTNAME}` in `global.ts`
3. Launch development server
4. See how the font doesn't load and observe errors in Chrome

**Expected behavior**
I would like to be able to upload and use local fonts for styling.

**Browser**
Chrome Version 77.0.3865.120 (Official Build) (64-bit)

**Additional context**
This could be a simple error of me not understanding the file structure, but I've been trial-and-error'ing this for a few hours now and can't seem to crack it. I've tried a bunch of different fonts, different locations for uploading the font, etc...

**Comment by brotzky** [comment]
Is the path to the font possibly wrong? I'm not sure this is something wrong with Novela. I don't believe you need to shadow the static folder if you're using Novela theme. You can use the regular gatsby static folder?

**Comment by gizzidan** [comment]
I just fixed it. I didn't realize I had to import the font into `global.ts` first. To fix it, I did the following:

1. add `import Arg from "www/static/fonts/Aaargh-webfont.woff";` to `global.ts`
2.  Add the font with `@font-face` utilizing the Arg import
`@font-face {`
    `font-family: "Arg";`
    `font-weight: 400;`
    `font-style: normal;`
    `src: url(${Arg}) format("woff");`
  }

**Comment by brotzky** [comment]
Fantastic! glad it worked out @gizzidan.
