### ISSUE TITLE
FR Possibility of discrete page selection? Menu / 

### ISSUE THREAD

**Issue by mannp** [narative/gatsby-theme-novela#178]
Needing to add a Private Policy, Legals etc and no easy way to incorporate for a novice 😃 without detracting from the coolness of the theme?

Thanks for any consideration.

**Comment by mabasic** [comment]
You can view my blog's Privacy Notice here: 
https://blog.laravelista.hr/privacy-notice

View the source code here:
https://github.com/laravelista/laravelista.github.io/tree/develop

Also, see here for placing the link in the footer:
https://github.com/laravelista/laravelista.github.io/blob/develop/src/%40narative/gatsby-theme-novela/components/Navigation/Navigation.Footer.tsx#L39

**Comment by mannp** [comment]
Cool, thanks @mabasic will take a look.

Some of your improvements are likely welcome back in this theme...

**Comment by brotzky** [comment]
@mabasic great resource links, thanks!

A more defined menu option may be a great idea.

**Comment by fpigeonjr** [comment]
I second the concept of adding a way to show page links. Maybe on the footer somewhere?

**Comment by bolonio** [comment]
I second the concept of adding a way to show page links as well, but I would prefer to have it in the navigation header (maybe together with the copy/darkmode options). I'm trying to overwrite the "NavigationHeader" component, but I haven't succeed yet. Any help?

**Comment by brotzky** [comment]
@bolonio if you can share your code I can take a quick look to see what's not quite working.

**Comment by PBRT** [comment]
I created a menu for my blog to simplify the navigation between the different many posts. It's not the final design yet, but I'd be happy to send a PR to add it if that's relevant (eventually turned off by default using a config flag or so). 

You can trigger it by clicking on the top-left logo (maybe not the best UX too), here's the link http://trolleytravel.org/

**Comment by bthibault** [comment]
@PBRT can you add a PR for the hamburger menu? I'm going to add a similar menu for mobile should give me a headstart

Thanks

**Comment by PBRT** [comment]
Hi @bthibault, so back in the time I submitted the PR so it's still in the repo in closed state, you can find it here: https://github.com/narative/gatsby-theme-novela/pull/275

Let me know if that's help :)
