### ISSUE TITLE
basePath is not set in GraphQL schema

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#181]
**Version of Novela you are using**
0.9.0

**Describe the bug**
~[The README](https://github.com/narative/gatsby-theme-novela#theme-options) claims that `basePath` comes with a default of `/`. However, that default is never explicitly set.~

`Navigation.Header.tsx` queries for `basePath` in `PluginOptions` but `basePath` must be defined in `PluginOptions` type before use.

**To Reproduce**
1. Create a new `gatsby-theme-novela` project without a `basePath` set in `options`
2. Watch `@narative/gatsby-theme-novela/src/components/Navigation/Navigation.Header.tsx` break with ` - Unknown field 'basePath' on type 'PluginOptions'.` error.

**Expected behavior**
`@narative/gatsby-theme-novela/src/components/Navigation/Navigation.Header.tsx` does not break.

**Screenshots**
<img width="954" alt="Screen Shot 2019-10-19 at 9 22 14 PM" src="https://user-images.githubusercontent.com/8263430/67153405-90463280-f2b6-11e9-8bae-7908d8299661.png">

**Comment by brotzky** [comment]
This could be because of the latest PR we brought in :o as we adjusted the pathing. I would recommend sticking to `0.8.x` until we fix it! Sorry.

**Comment by AryanJ-NYC** [comment]
This'll be one of those bugs that I fix for ya. :)
