### ISSUE TITLE
Git commit issues

### ISSUE THREAD

**Issue by mabasic** [narative/gatsby-theme-novela#189]
**Version of Novela you are using**

0.9.4

**Number of posts you have and which data source**
(Local, Contentful options)

Local

**Describe the bug**

When I try to commit my changes to this repository I get a message saying that a commit requires a subject and type. What am I expected to do?

I usually just do `git commit -m "something"`.

Any help?

**To Reproduce**
1. Type `git commit -m "something"`
4. See error saying that subject and type is required.

**Expected behavior**

Why can't I just commit without subject and type. I don't even know how to enter commit type or what it is.

**Screenshots**

**Browser**
 - Browser [e.g. chrome, safari, iOS safari]

**Additional context**

**Comment by mabasic** [comment]
Figured it out...

https://commitlint.js.org/#/

Haven't heard of this before, but it looks cool.

**Comment by brotzky** [comment]
It's pretty neat and fairly useful for OSS -- wonder if it would be useful to add to the contribution guides as a couple people have been stumped by it.

**Comment by mabasic** [comment]
I will try to write something and send a PR for this. At first I also looked at the contribution guide... so that would be the place for that.

**Comment by jpvalery** [comment]
Done ;)
