### ISSUE TITLE
Copyright line shows current year regardless of actual copyright dates

### ISSUE THREAD

**Issue by MartinRosenberg** [narative/gatsby-theme-novela#192]
**Is your feature request related to a problem? Please describe.**
The copyright line always says the current year, regardless of the actual copyright dates of the material. For example, the content on [my blog](https://github.com/MartinRosenberg/martinbrosenberg.com) using this theme is copyrighted 2017-2019.

**Describe the solution you'd like**
The ability to customize the copyright line in `siteMetadata`.

**Describe alternatives you've considered**
If this remains purely automated, the copyright dates could be gleaned from the earliest and latest post dates. This has the advantage of not requiring further configuration, but the notable disadvantages that it might still be wrong, if:

- non-post content is copyrighted earlier or later than the posts
- content copyright date doesn't align with post publication date
- copyrights belong to different parties

**Additional context**
https://github.com/narative/gatsby-theme-novela/blob/5e78e1c3811766aa1baf715fecc82d367277b01c/%40narative/gatsby-theme-novela/src/components/Navigation/Navigation.Footer.tsx#L39

**Comment by brotzky** [comment]
PR for this would be lovely. Either showing the original date only or a date range is great!

**Comment by MartinRosenberg** [comment]
I'll get started on one pending #191, to avoid merge conflicts. :)

**Comment by brotzky** [comment]
Thanks!
