### ISSUE TITLE
scroll to Top button

### ISSUE THREAD

**Issue by heyAyushh** [narative/gatsby-theme-novela#193]
A scroll to Top button at bottom right.

Also I want to implement this.

Guide me senpai on what to choose as Icon set and Animation

Thanks for making this repo

```
componentDidUpdate() {
  ReactDOM.findDOMNode(this).scrollTop = 0
}
```

**Comment by brotzky** [comment]
I dont think we'll be adding a scroll to top button to Novela at this moment. Sorry!
