### ISSUE TITLE
Youtube embed

### ISSUE THREAD

**Issue by fpigeonjr** [narative/gatsby-theme-novela#195]
**Version of Novela you are using**
0.*

**Number of posts you have and which data source**
Local

**Describe the bug**
When I embed a Youtube video the video breaks the grid and flies left.

**To Reproduce**
1. Go to 'Youtube and copy the embed code'
```html
<iframe width="560" height="315" src="https://www.youtube.com/embed/moTlZBY66Ng" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```
2. Paste into a blog post markdown
3. See error

**Expected behavior**
Youtube video stays in the grid, not fly left.

**Screenshots**

![youtube-embed](https://user-images.githubusercontent.com/4629398/67737660-1a3e7b80-f9da-11e9-8773-0f3c03aad7c7.png)

**Browser**
 - Browser [e.g. chrome, safari, iOS safari]
Firefox
**Additional context**
Thanks love the project!

**Comment by brotzky** [comment]
A quick workaround would be to add a margin: 0 auto to the iframe and adjusting the video to also work on mobile.

Beauty of MDX is you can insert react components into your `.mdx` files :)

In the future we should better support iframes/embeds within Novela.

**Comment by fpigeonjr** [comment]
> 
> 
> A quick workaround would be to add a margin: 0 auto to the iframe and adjusting the video to also work on mobile.
> 
> Beauty of MDX is you can insert react components into your `.mdx` files :)
> 
> In the future we should better support iframes/embeds within Novela.

Yes the work around worked for me. Thanks so much.
