### ISSUE TITLE
multiple instances for the theme

### ISSUE THREAD

**Issue by sw-yx** [narative/gatsby-theme-novela#20]
i want multiple paths: 
![image](https://user-images.githubusercontent.com/6764957/62484035-3b9b1d00-b787-11e9-88ea-d600688c4c02.png)

but the build result gets the content from `content/posts` and outputs them to the path of `/writing/draft` which is real weird

we need to keep em separate somehow.

**Comment by brotzky** [comment]
Interesting, I did some tests and for some reason they have the same `node.id`

```js
{ slug: '/drafts/why-narative-loves-gatsby',
  id: '36b372cf-7420-54b0-90e8-caa006b4752a' }
{ slug: '/why-narative-loves-gatsby',
  id: '36b372cf-7420-54b0-90e8-caa006b4752a' }
```

This is causing Gatsby to override it since they store each node in a flat object based on the an `id` key.

Will investigate a bit more into why this happens and if it's something on our end or within Gatsby internals.

**Comment by sw-yx** [comment]
i fixed it in my thing by essentially forking the whole thing: https://github.com/sw-yx/swyxdotio/commit/ad98a832faf84fe7f4b34b037cef5c2bd61d092b

we just need to remove some of these assumptions like all Articles belonging to the same instance, and also 

```
`content/${source}` === contentPath
```

is a hidden assumption i wasn't aware of that would have messed me up if i were doing some alternative filestructure

**Comment by brotzky** [comment]
Ah right, good catch. I forgot to get back to that one.

Thanks for all the feedback and help so far, @sw-yx.

**Comment by brotzky** [comment]
Fixed contentPath assumption
https://github.com/narative/gatsby-theme-novela/commit/d1da1d7a5aa91cd65f41342bd08acb4e101589ff#diff-b15bca3c1dcd1f4ca9063ebac70e66e1R21

**Comment by ChristopherBiscardi** [comment]
> i want multiple paths:

That doesn't sound like something that should be solved by instancing themes (which implicitly instances styles, logic, etc). That sounds like the theme itself can add two filesystem sources instead.

`contentPosts: []`

**Comment by sw-yx** [comment]
but then its not just filesystem logic, i’d need them to be named differently. maybe one is Article and the other is Drafts and another is Talks and so on? idk thats what i was gonna do on my thing

**Comment by sw-yx** [comment]
closing as low pri, other stuff i've filed is way higher imo
