### ISSUE TITLE
Nested unordered lists are flat

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#200]
**Version of Novela you are using**
0.9.0

**Describe the bug**
* Nested lists
  * for example,
    * like this one

are flat. The example above would be rendered as 
* Nested lists
* for example,
* like this one

**To Reproduce**
1. Consider the MDX at https://raw.githubusercontent.com/AryanJ-NYC/webdev-coach-blog/master/content/posts/2019-04-19-system-design-tinder/index.mdx
2. Look at https://www.thewebdevcoach.com/system-design-tinder
3. Realize the unordered lists are flat

**Expected behavior**
Nested lists are nested

**Browser**
All browsers

**Comment by brotzky** [comment]
Ah that sucks. Looks like we have to handle the nesting better. It won't be fixed in the latest version so it's not worth upgrading for you right now. Will batch this into a bunch of other fixes.

**Comment by AryanJ-NYC** [comment]
Much appreciated. Out of curiosity, what's the best place to look if I wanted to help out in fixing? I tried dissecting the code but I thought `mdx` was in charge of that.

**Comment by brotzky** [comment]
`mdx` would be my initial guess. I'd check that the data passed in is parsing the nested list. googling around shows some MDX issues with nested lists... maybe that's it.
really appreciate any help. thanks!

**Comment by AryanJ-NYC** [comment]
Alright, I'm back with some findings. From https://github.com/mdx-js/mdx/issues/262, MDX takes something like:

```md
* level one
  * level two
```

and makes it:

```html
<ul class="sc-kkGfuU hISnYn" font-size="2">
    <li class="sc-hSdWYo bIQQAp">
            <p class="sc-kEYyzF fhSvky" font-size="2">level one</p>
            <ul class="sc-kkGfuU hISnYn" font-size="2">
                <li class="sc-hSdWYo bIQQAp">level two</li>
           </ul>
    </li>
</ul>
```

This is a feature, not a bug. However, the CSS does not consider this and, in line [49-51 of `List.Unordered.tsx`](https://github.com/narative/gatsby-theme-novela/blob/0535a36ccfedce4b54a5e31b2ba0ef0c0d3602a5/%40narative/gatsby-theme-novela/src/components/Lists/List.Unordered.tsx#L49) (and similarly in `List.Ordered.tsx`), all children of `li` tags are inlined. In our case above, that means the `ul` is also inlined and the `li` would be on the next line (lying flat).

I've went ahead and changed the CSS to rule to _not_ inline nested  `ol` and `ul` tags.
