### ISSUE TITLE
Why I can't find component inside src folder? 

### ISSUE THREAD

**Issue by samleez** [narative/gatsby-theme-novela#201]
Hi guys,

So when I install the starter for the first time I only get uncompleted files and folders, for example, there's no **component** in the **src folder**, there are no files where I can replace my own logo..etc

I installed the starter using this command line: 
`gatsby new novela-site https://github.com/narative/gatsby-starter-novela`

but all that I get is some folders with a lot of files missing but when I run my local server it works just fine, I am new to gatsby and reactjs but I have never encountered an issue like this before! and I tried a lot of starters.

So any help here, please?

**Comment by brotzky** [comment]
This is how themes work!

When you add a theme as a dependency (@narative/gatsby-theme-novela) the whole point is that you don't get direct access to the components and can use Component Shadowing instead. This means all you have to add is data. This also means you're able to compose themes and have more complex sites with multiple themes.

I recommend taking a look at their documentation to get a better idea: https://www.gatsbyjs.org/docs/themes/shadowing/

Hope that helps. I'll close this issue as I don't think it's really an "issue". Feel free to ask more questions even though it's closed.

**Comment by samleez** [comment]
> This is how themes work!
> 
> When you add a theme as a dependency (@narative/gatsby-theme-novela) the whole point is that you don't get direct access to the components and can use Component Shadowing instead. This means all you have to add is data. This also means you're able to compose themes and have more complex sites with multiple themes.
> 
> I recommend taking a look at their documentation to get a better idea: https://www.gatsbyjs.org/docs/themes/shadowing/
> 
> Hope that helps. I'll close this issue as I don't think it's really an "issue". Feel free to ask more questions even though it's closed.

Hi bro, thanks for the info but it still confusing me, let's say I want to modify the logo in novela theme .. should I create the component file in src folder? and that's the deal with each intends modification. first I must create the files from scratch? is that right?

**Comment by brotzky** [comment]
Check this out:
https://github.com/narative/gatsby-theme-novela#adding-your-logo
