### ISSUE TITLE
Support for custom Routes

### ISSUE THREAD

**Issue by misho-har** [narative/gatsby-theme-novela#206]
Hi, 

Thanks for this amazing theme I am in love 😍
I got a question, I am trying to add a intro page to `/` home page and move blogs under `/blog` route? is that possiable?

**Comment by brotzky** [comment]
Yes, you can define the base route that Novela is built into for your site. Define the `basePath` in the theme options

https://github.com/narative/gatsby-theme-novela#theme-options

**Comment by brotzky** [comment]
And thanks :D

**Comment by misho-har** [comment]
Thanks a lot :) and what about if I want to add a new folder in `content/courses` and they create `/courses` and `courses/course-slug` pages is that something doable ? :) @brotzky

**Comment by brotzky** [comment]
I don't believe we support multiple sources for the content right now. :|
Sorry!
