### ISSUE TITLE
Complied large template file blocking home page activities.

### ISSUE THREAD

**Issue by vikingmute** [narative/gatsby-theme-novela#212]
In slow network connection, this compiled article template js file "src-templates-article-template-tsx.js"(about 825 Kb) will take a little while to load, during this time, all the activities on the home page will be blocked, click the article title has no responding. Do we have a dynamic import mechanism  when we actually go to that route? Sceenshots below:

<img width="896" alt="屏幕快照 2019-11-15 上午9 05 20" src="https://user-images.githubusercontent.com/343954/68909085-2bcca500-0788-11ea-9327-f883b48cce4a.png">

![block clicking](https://user-images.githubusercontent.com/343954/68909526-8c101680-0789-11ea-96d4-ed89f462d29c.gif)

**Comment by brotzky** [comment]
This should be handled by Gatsby.

I checked Novela's at novela.narative.co and the largest bundle is about 200KB for the article
http://d.ntve.co/zX91Rs

Are you looking at the development environment or is that production?

**Comment by vikingmute** [comment]
@brotzky  I used the production build , I looked up the public build folder, I found two templates-article-template-tsx.js files with different hash name. one file's bundle size is indeed around 825Kb, and the other is around 200Kb, I think that's because I use Component Shadowing to create my own version of article.template.tsx, I added a custom disqus-react library may increase some file size.

**Comment by brotzky** [comment]
Hmmm, that's probably it. In the original one it's 200KB so I would take a look at your shadowing. Hope that helps.

**Comment by vikingmute** [comment]
@brotzky  Today I did some more research and found the 824Kb file is not caused by Component  Shadowing. I did a **clean install** using `gatsby new novela-site https://github.com/narative/gatsby-starter-novela ` , and in the new project I did `gatsby build` right away. And I found the file (article-template-tsx) size is 824Kb,  my local webpack version is "4.41.2".

**Comment by brotzky** [comment]
Thanks for taking a deeper look. Going to have to investigate this because 824KB is not acceptable in my opinion.

**Comment by vikingmute** [comment]
@brotzky should we reopen this issue?

**Comment by brotzky** [comment]
Hey, I can't reproduce this on novela.narative.co and I cloned down the starter and built it's not loading any large files (~824Kb). I do see that the public folder contains 800k files tho (and some 2.4Mb files).

<img width="1367" alt="Screen Shot 2020-01-04 at 8 02 43 PM" src="https://user-images.githubusercontent.com/8007686/71774958-3ce69680-2f2d-11ea-83ae-21495e85f938.png">
<img width="1473" alt="Screen Shot 2020-01-04 at 8 02 29 PM" src="https://user-images.githubusercontent.com/8007686/71774959-3ce69680-2f2d-11ea-9793-3a0791f5fd9f.png">
