### ISSUE TITLE
Custom comment

### ISSUE THREAD

**Issue by sgorki** [narative/gatsby-theme-novela#213]
How to add custom comment for my blog ?
for example : https://utteranc.es/
i'm beginner

**Comment by brotzky** [comment]
Hey @sgorki, welcome!

Unfortunately, I don't know how to add custom comment for your blog. I believe we've had users add comments with Disqus to their Novela blog.If you dig into the past issues you may be able to find some outlining how to add comments.

A comment system isn't a core feature of Novela that we want to support so you'd have to fork the repo and build it yourself.

Hope that helps :). Good luck!
