### ISSUE TITLE
Native Adsense and Disqus support

### ISSUE THREAD

**Issue by rommelporras** [narative/gatsby-theme-novela#214]
Add native support in Adsense and Disqus just like Google Analytics in `www/gatsby-config.js`.

Is there a way right now to add Disqus comments in every post and Adsense?

**Comment by brotzky** [comment]
There are some Disqus implementations. If you search through the closed issues there should be some examples there!

As for Adsense I'm not sure what you mean. I don't have any experience with that, sorry.

**Comment by brotzky** [comment]
https://github.com/narative/gatsby-theme-novela/issues/34

Check this one out

**Comment by rommelporras** [comment]
> As for Adsense I'm not sure what you mean. I don't have any experience with that, sorry.

I mean how to implement Google Adsense in every post of Novela? 

I think it is nice to have Disqus or any comment service integrated to the core of Gatsby Theme Novela.

Thanks for the link, I will research how to add Disqus in the bottom of every post.

**Comment by brotzky** [comment]
Hey, thanks for the suggestion! Unfortunately, we won't have native support for comments. I hope the link and example repo helps you implement it :)
