### ISSUE TITLE
Shadowing UX

### ISSUE THREAD

**Issue by ChristopherBiscardi** [narative/gatsby-theme-novela#22]
Hey, on stream I dove into [the shadowing issues](https://twitter.com/swyx/status/1157922777992761344) @sw-yx mentioned on twitter. I wasn't able to find anything wrong with shadowing itself (`.tsx` files can be shadowed by `.js` and `.tsx` files). As seen in this screenshot:

![image](https://user-images.githubusercontent.com/551247/62497939-59ba4a80-b792-11e9-9ef1-4e4e5159933b.png)

I did find a UX issue that could explain why he was confused though. The `components/Heading/Heading.tsx` file, when shadowed, does not apply to MDX content. Including the exports as components in the [MDXProvider](https://github.com/narative/gatsby-theme-novela/blob/ed615f1d2a2385d39c588c41c5f1adf182a95c35/src/components/MDX/MDX.tsx#L24) could be one solution to this. I didn't know what the intended effect was, so I'm filing an issue instead of a PR.

**Comment by sw-yx** [comment]
oh nice! idk i dont think that was it, i was trying to get rid of https://github.com/narative/gatsby-theme-novela/blob/master/src/sections/articles/Articles.Grid.Tiles.tsx and i ejected it and it didnt work. i'll try this again when i get back to work on it

**Comment by brotzky** [comment]
Yes, this is very true and a great point. The Headings, Links, etc need to be refactored to be more  `theme` friendly. Right now there are a couple aspects that would be annoying to shadow, but now that I understand themes a lot more and have shadowed it's evident what needs updating.
Will work on that as a priority.

**Comment by brotzky** [comment]
Refactored a lot of the components that are within MDX body. They're now individual components passed in so it's easier to shadow.
Will release in 0.0.6-7

https://github.com/narative/gatsby-theme-novela/commit/83246d7b97f0bc5382e6e9f0b7e4f2285f915759#diff-8dcb7564583b9542657d624cc6bc8c1aR21

**Comment by sw-yx** [comment]
thanks guys. i dont think my shadowing issue is at all to do with MDX. so i'll reopen and tag you and i have a repro now.

**Comment by parimalvyas** [comment]
Waiting for the Navigation Header and Bio section for Shadowing. Also, it will be great if we can just take the current tsx file and modify and apply as a shadow. 

Thank you this thread was really helpful. I was trying to Shadow the Navigation Component, Bio and Article Hero without any luck. 

Looking forward to the use the shadowing feature to the fullest. 

Great work with the theme guys!

**Comment by brotzky** [comment]
Can you share a repository where you're trying to achieve shadowing? I'd love to help you out.

**Comment by parimalvyas** [comment]
Hi Dennis, **thank you** for this.
The link to the repo is: https://github.com/parimalvyas/pvyas-new-site.git

I am trying to Shadow the Header Navigation, Bio Section, Social Links and I plan to add a new About Page going forward. 

Pardon me for the poor code, I am still trying to learn.
