### ISSUE TITLE
How to create multiple post types

### ISSUE THREAD

**Issue by tantrongtt** [narative/gatsby-theme-novela#220]
Hi Narative team,

Thanks for providing a very beautiful site. I'm a designer and really love the design!
I've just known about GatsbyJS last week and used your theme for my website.

I want to set up my website supporting multiple post types, both blog articles and my previous work (Portfolio). This portfolio setup works best for designers who love to write.

I already put a `portfolios` folder under the `/content`. So the structure like this:
--content
   ---authors
   ---portfolios
   ---articles

All post inside `/portfolios` is the same structure as the `/articles`. I want all my posts inside the `/portfolios` to use a different template which is better for a showcase.

I also tried to duplicate all the config you did for `/articles` inside `createPages.js`, `gatsby-config` `onPreBootstrap` file but it doesn't work.

That branch is here: https://github.com/tantrongtt/blog/pull/7/files

I know you guys are busy, but if you read this issue, please give me some advice on how to fix it.

Thanks,
Trong

**Comment by brotzky** [comment]
What exactly doesn't work? Is there an error message? Or it's rendering like the wrong page? I took a look through the PR and it looks like you have the right idea.
Query the content then build pages using the portfolio template.

**Comment by tantrongtt** [comment]
Oh! Thanks so much, @brotzky for the response!

Sorry that I didn't describe it clearly.
There is no error, but it's rendering the wrong page. Now all articles page render my new portfolio template.
I assume that the URL/slug for template and article is the same or the query problem.
I didn't change any query because I don't know about graphQL.

What should I do?

Thanks,
Trong

**Comment by brotzky** [comment]
It looks like this could be the issue: https://github.com/tantrongtt/blog/blob/c0b0ea863fe4b95ab66e5baca6d240fe48ea2786/%40narative/gatsby-theme-novela/src/gatsby/node/createPages.js#L264

You're passing articles in for the edges of the Portfolio.

**Comment by tantrongtt** [comment]
Thanks @brotzky 
I tried to fix it by using the portfolio here. But it stays the same: still run, but using the article template. https://github.com/tantrongtt/blog/blob/0f2dd9935d921fc0906971aa29d2b4f2c27af2e9/%40narative/gatsby-theme-novela/src/gatsby/node/createPages.js#L266

I noticed that all portfolios inside my `content/portfolios` folder haven't created because I can't access it but entering the URL. e.g: `portfolios/trong-tnt-tnt`

This is all URLs
<img width="533" alt="image" src="https://user-images.githubusercontent.com/26541725/69710227-fa65b900-1139-11ea-8eb6-d211a3d4dfc9.png">

Seems like there's no any `portfolios/... ` URL yet.

I really appreciate your help!

Trong

**Comment by tantrongtt** [comment]
As my understanding, if my data inside `content/portfolios` is added, it should appear inside the `http://localhost:8000/___graphql`,  doesn't it? I found nothing relates to portfolio

<img width="291" alt="image" src="https://user-images.githubusercontent.com/26541725/69726893-61946500-115c-11ea-9dbb-9a1a25c65b88.png">

**Comment by brotzky** [comment]
Hey, ill take a better look this weekend (if you still dont solve it) when I have some more time. Ill try cloning it down and seeing what's wrong. 

Yes, the content should appear in graphiql.

**Comment by tantrongtt** [comment]
Thanks so much!

I will try to fix it, but I'm not so confident. I will let you know the update.

**Comment by tantrongtt** [comment]
Hey Brotzky,

I can't solve it. I hope that you can help me!

Thanks

**Comment by tantrongtt** [comment]
Hey Brotzky,

I think did it! :)))))))))))

Thanks so much for all your time!

**Comment by brotzky** [comment]
Awesome :)
