### ISSUE TITLE
Built in Image Gallery

### ISSUE THREAD

**Issue by rommelporras** [narative/gatsby-theme-novela#221]
I think it is nice to have an Image gallery function here in Novela

Something like [Ghost's Image Gallery](https://ghost.org/blog/image-galleries/)

Novela's default implementation of images is good, but it can still be improved with an image gallery with zoom functionality.

[Sample picture of a gallery](https://kinsta.com/wp-content/uploads/2018/02/modula-gallery.jpg)

**Comment by brotzky** [comment]
Would love a PR for this otherwise it's unlikely we'll add it.

**Comment by imprashast** [comment]
Looks interesting, I might work on this :)

**Comment by jpvalery** [comment]
Hi everyone! Doing some housecleaning :) 
Is this still alive or has it become stale?

**Comment by rommelporras** [comment]
I think it become stale? I think this feature is nice to have for Novela theme.
