### ISSUE TITLE
FooterText not showing correct copyright years

### ISSUE THREAD

**Issue by slavakurilyak** [narative/gatsby-theme-novela#224]
**Version of Novela you are using**
0.10.3

**Describe the bug**
The footer shows incorrect dates

**To Reproduce**
1. Publish any content (local or Contentful)
2. Scroll down to the footer
4. See screenshot

**Expected behavior**
When I post content for 2019, I expect 2019 to show up as the copyright year in the footer

**Screenshots**
<img width="676" alt="Screen+Shot+2019-12-02+at+12 00 13+AM" src="https://user-images.githubusercontent.com/6625584/69940635-99bae100-1497-11ea-9a15-170677385426.png">

**Comment by EmaSuriano** [comment]
Yeah, I was having the same issue. I opened a PR to fix it. #225

**Comment by brotzky** [comment]
Merged and fixed. Thanks again @EmaSuriano!
