### ISSUE TITLE
Missing `social` on Author 

### ISSUE THREAD

**Issue by virusvn** [narative/gatsby-theme-novela#228]
**Version of Novela you are using**
0.10.5

**Number of posts you have and which data source**
Local

**Describe the bug**
The directory `content/authors`, `content/posts` is already have good data (same as the example)
But the plugin throw the error `Error: You must have at least one Author and Post.`
The reason is the query is getting `social` on Author, but doesn't have any Social resolver. If I delete the field `social` of the query `module.exports.local.authors` in `src/gatsby/data/data.query.js`, the bug is gone.

**To Reproduce**
Follow the instruction Getting Started from scratch:
https://github.com/narative/gatsby-theme-novela#getting-started-from-scratch

**Expected behavior**
Start the project normally.

**Comment by brotzky** [comment]
Hmmmm, that's strange. We have it working on novela.narative.co based off this file
https://github.com/narative/gatsby-theme-novela/blob/master/www/content/authors/authors.yml

Are you sure it's configured correctly? It's possible we have social documentation incorrect.

**Comment by virusvn** [comment]
@brotzky 
Thank you! I solved the problem by correct `authors.yml`.
The guide is wrong at https://github.com/narative/gatsby-theme-novela#step-4-adding-an-author
