### ISSUE TITLE
Adding LaTeX using gatsby-transformer-remark doesn't work

### ISSUE THREAD

**Issue by kevinra** [narative/gatsby-theme-novela#230]
**Version of Novela you are using**
0.10.5

**Describe the bug**
I'm trying to add LaTeX using [gatsby-remark-katex](https://www.gatsbyjs.org/packages/gatsby-remark-katex/) but the string is treated as a raw string.

**To Reproduce**
1. Install necessary packages specified on the [website](https://www.gatsbyjs.org/packages/gatsby-remark-katex/).
2. Modify gatsby-config.js according to the gatsby-remark-katex documentation
3. Add line `import "katex/dist/katex.min.css";` to either `templates/articles.template.tsx` or `components/MDX/MDX.tsx`
4. Add test equation to a mdx file:
```
$$
a^2 + b^2 = c^2
$$
```
**Expected behavior**
A equation should be rendered properly like below (from https://using-remark.gatsbyjs.org/katex/):
![image](https://user-images.githubusercontent.com/6539629/70596027-e0ed5400-1bb2-11ea-82ce-4a48f80ccacd.png)

**Screenshots**
The equation string was treated as a raw string:
![image](https://user-images.githubusercontent.com/6539629/70596069-00847c80-1bb3-11ea-8f25-e7304eef39cd.png)

Edit: Another sample gatsby website that uses this: https://www.gatsbyjs.org/starters/patricoferris/gatsby-starter-notes/

**Comment by brotzky** [comment]
looks like it'll have to be integrated into the core if we want to support that. A bit strange it's not combining your plugins.

**Comment by kevinra** [comment]
When you say core, is it something achievable by component shadowing or not? If it's possible, could you pinpoint where I should look at?

**Comment by stanstarks** [comment]
I am trying [gatsby-remark-mathjax](https://www.gatsbyjs.org/packages/gatsby-remark-mathjax/). The problem I cannot solve is adding mathjax scripts to head. I tried setHeadComponents with [gatsby-ssr.js](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody) but can't figure out why it does not take place.

**Comment by brotzky** [comment]
you can try placing it directly in the `html.js` file?

**Comment by stanstarks** [comment]
@brotzky Thanks. I can add it directly in the html.js. However, the script does not take effect.

**Comment by jpvalery** [comment]
Hi y'all,

Doing some housecleaning - is this still an issue or has it become stale?

**Comment by hanzhihua1** [comment]
Most of the other gatsby starters have `gatsby-remark-katex` by default. The only way to add KaTeX is to add it to core, under `remarkplugins` under `gatsby-mdx` as it is a remark plugin, it isn't possible to add it otherwise.

**Comment by brotzky** [comment]
@hanzhihua1 did you want to give it a shot? I really don't have time in the up coming weeks to handle this myself.

**Comment by hanzhihua1** [comment]
@brotzky  I made a pull request, however display mode katex doesn't seem to change color when you go into dark mode.

Im not sure how to fix this myself as I'm somewhat inexperienced. But all you need to do is on click, get all html tags with class 'katex-html' (off my head, double check this), and set the color to the theme color along with the color during transition. I think that will work.

**Comment by smartdreams** [comment]
Hi, I am having same issue here. Please let me know any ETA on the fix. Thanks.

**Comment by smartdreams** [comment]
@brotzky I just followed latest pull request and it seems fine now. I am wondering if we would need to do the similar thing, adding to the core, whenever we have to use another plugin. Thanks.

**Comment by brotzky** [comment]
What do you mean @smartdreams? Having configurable plugins you mean?

**Comment by smartdreams** [comment]
@brotzky  What I meant is, whenever I need to use another third party plugins, do I have to edit your theme's core files (gatsby-config files in theme's folder) ? For example, I needed to add this plugin, https://www.gatsbyjs.org/packages/gatsby-remark-draw/, and I did the same way from @hanzhihua1 pull request for Latex plugin fix, and it worked. So, I guess your answer will be yes. And, that's fine for me. Thanks for the great theme.

**Comment by brotzky** [comment]
To be honest we didn't expect people would need plugin customizations when building this theme and clearly that's not the case.

As of right now though we don't plan on adding the feature our selves due to time constraints but would be happy to approve a PR that enables configurable plugins.

Also, thanks for the kind works, @smartdreams <3.
