### ISSUE TITLE
Diverse Language Title is not supported properly.

### ISSUE THREAD

**Issue by mattjogo** [narative/gatsby-theme-novela#232]
**Version of Novela you are using**

0.10.1

**Number of posts you have and which data source**
(Local, Contentful options)

Local

**Describe the bug**

Only an alphabetical title supported properly with a main title page. Like Cyrillic Script, Hangul(Korean Alphabet) and Japanese is not supported properly. Only an un-alphabetical titled language post be in the top position, and redirection function is also not working properly with this.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser**
 - Browser [e.g. chrome, safari, iOS safari]

Safari 12

**Additional context**

**Comment by brotzky** [comment]
I've changed it to use slugify under the hood and it should work properly now on latest release.
(~0.12.2)
