### ISSUE TITLE
How to create a static image folder and use Gatsby image

### ISSUE THREAD

**Issue by tantrongtt** [narative/gatsby-theme-novela#240]
Hi Narative team,

I'm using Novela and want to create many different landing pages that need many images. Now I put all of them to the `static` folder but I don't think it's a good use for Gatsby. Because the images aren't optimized by Gatsby image (I guess so?).

So, I want to create an image folder in which I will store all images for my landing pages there. And apply Gatsby image for them to optimize the size.

What should I do?

Thanks

**Comment by brotzky** [comment]
Hey @tantrongtt,
Have you read through this: https://www.gatsbyjs.org/docs/working-with-images/?
There shouldn't be anything special required to work with Gatsby Image with a theme.

Yes, you can create a folder and query the images for your landing pages.

**Comment by tantrongtt** [comment]
Hey Brotzky,
It took me a couple days to figure out and understand how it works. But I finally be able to do it.

Thanks alot! Sorry to bother day

**Comment by brotzky** [comment]
No problem. Just glad you were able to resolve it :)
