### ISSUE TITLE
[CI/CD] Publish with Lerna not publishing @narative/gatsby-theme-novela

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#242]
**Describe the bug**
The [Publish with Lerna GitHub action](https://github.com/narative/gatsby-theme-novela/commit/eada16c5ce2ce188e349982c8b116efd9dc0cfd7/checks?check_suite_id=372091617) is not publishing correctly when `@narative/gatsby-theme-novela` `package.json` is bumped. Instead, it looks for a bump in the version number of the root `package.json`. This results in a human needing to go back and publish `@narative/gatsby-theme-novela`.

**To Reproduce**
1. Go to https://www.npmjs.com/package/@narative/gatsby-theme-novela and realize only 0.11.x is published.
2. Go to https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/package.json and realize `0.12.x` should be published.
3. Go to https://github.com/narative/gatsby-theme-novela/commit/eada16c5ce2ce188e349982c8b116efd9dc0cfd7/checks?check_suite_id=372091617, expand the `Publish with Lerna` accordion, and realize `lerna success No changed packages to publish` is logged to the terminal.

**Expected behavior**
A bot should publish `@narative/gatsby-theme-novela`.

**Additional Context**
Possibly related to #185.

**Comment by brotzky** [comment]
Yes, you're right that it's currently not working as expected. JP who is responsible for the CI/CD wants to fix this issue after the Holidays. He's been kind enough to let me know he's aware of the issue and wants to fix it when he finds some time.

**Comment by jpvalery** [comment]
Yeah it's been a dumpster fire to do it with GH Actions tbh. I think my latest commit might fix it once and for all.

**Comment by jpvalery** [comment]
Blocked by #249

**Comment by jpvalery** [comment]
Jotting thoughts down: if this still doesn't work once the blocker is lifted and lerna can't publish; I'd be down to try a different route >> https://www.christopherbiscardi.com/post/shipping-multipackage-repos-with-github-actions-changesets-and-lerna/

**Comment by aleccool213** [comment]
Having the Github Action create a pull request makes for a very transparent release process, I like it 👍
