### ISSUE TITLE
I carefully suggest, using forestry.io

### ISSUE THREAD

**Issue by eugenejeonme** [narative/gatsby-theme-novela#245]
I was planning a blog using Hugo.
Then I found the following Novel Theme.
https://github.com/forestryio/novela-hugo-starter

I noticed that Gatsby has the same theme. Is this the original?
And I have confirmed that the themes made with Gatsby are softer.

And I saw an issue card that wanted NetlifyCMS.
So I suggest carefully. What about Forestry.io?

If you don't want it, you can close it.

**Comment by brotzky** [comment]
That Hugo theme was kindly ported over by contributor. 

This is the original theme you're commenting one.

If someone decides to port it to Forestry.io we're all for that :)

**Comment by eugenejeonme** [comment]
> That Hugo theme was kindly ported over by contributor.
> 
> This is the original theme you're commenting one.
> 
> If someone decides to port it to Forestry.io we're all for that :)

OK, Thank you for your comments.
I will close this card.
And if you have a lot of people who want Forestry.io, I'll help you too. :)
