### ISSUE TITLE
Add renovate for automated dependancy upgrades

### ISSUE THREAD

**Issue by aleccool213** [narative/gatsby-theme-novela#246]
**Is your feature request related to a problem? Please describe.**

To keep up with the Gatsby ecosystem, I suggest [renovate](https://github.com/marketplace/renovate) is added to the repo. Makes it very easy to keep up with dependancy upgrades.

**Describe the solution you'd like**

* Install renovate as a github app

**Describe alternatives you've considered**

There are some other solutions which do this, but I find renovate the best because you can configure it pretty extensively.

**Additional context**

**Comment by brotzky** [comment]
We've tried similar stuff and our own site has https://dependabot.com/ but I find it pretty annoying and actually not a lot easier to maintain because you usually blindly update groups of packages.

**Comment by aleccool213** [comment]
I find them annoying as well. The good thing about renovate is the config:

```json
{
  "extends": [
    "config:base",
    "group:allNonMajor",
    "schedule:earlyMondays"
  ]
}
```

* once a week
* groups all non-major upgrades into one pr

> actually not a lot easier to maintain because you usually blindly update groups of packages.

Totally, if you have good test coverage with Cypress or Percy then it aint bad.

> btw: appreciate all the issues you've raised recently :) Nice to have someone bringing up suggestions and questioning what's happening with Novela.

No worries 👍

**Comment by aleccool213** [comment]
Looks like you thought of it before tho. Feel free to re-open if renovate sounds cool.
