### ISSUE TITLE
Lacking support for `gatsby-transformer-remark`

### ISSUE THREAD

**Issue by aleccool213** [narative/gatsby-theme-novela#247]
**Version of Novela you are using**
0.12.2

**Number of posts you have and which data source**
10, local

**Describe the bug**
I am switching my blog from native Gatsby over to this theme and one of the last features I need to get working is embedded content. In the old version of my blog, I have `gatsby-transformer-remark` working with a few plugins to get Vimeo and Instagram content rendering in blog posts. 

When switching to this theme, it seems they do not work out of the box. Either we should add docs on how to get this to work, or fix this. It is pretty important if people are switching from old blog posts.

**To Reproduce**
1. Git clone my blog: https://github.com/aleccool213/blog/tree/novella-theme
2. `npm i`
3. `gatsby develop`
4. Go to `http://localhost:8000/hacking-my-honeymoon-with-javascript` and see that Instagram content isnt rendering.
5. Go to `http://localhost:8000/the-hitchhikers-guide-to-cypress-end-to-end-testing` and notice Vimeo video isnt rendering

*or*

1. Go to `https://deploy-preview-101--wonderful-lichterman-881960.netlify.com/hacking-my-honeymoon-with-javascript` and see that Instagram content isnt rendering.
2. Go to `https://deploy-preview-101--wonderful-lichterman-881960.netlify.com/the-hitchhikers-guide-to-cypress-end-to-end-testing` and notice Vimeo video isnt rendering

**Expected behavior**

`gatsby-transformer-remark` works with plugins.

**Screenshots**
![Screenshot at Jan 17 10-08-37](https://user-images.githubusercontent.com/6475934/72622512-5a463800-3911-11ea-8afd-78d7b18be1ff.png)

![Screenshot at Jan 17 10-08-57](https://user-images.githubusercontent.com/6475934/72622530-6500cd00-3911-11ea-8fe8-001d9ce770dd.png)

**Browser**
 - Browser [e.g. chrome, safari, iOS safari]

**Additional context**

[Link to gatsby-config.js](https://github.com/aleccool213/blog/blob/novella-theme/gatsby-config.js)

**Comment by pierrenel** [comment]
Having the same issue, keeping my eyes on this one 👀

**Comment by pierrenel** [comment]
@aleccool213 I temporarily "fixed" it by adding gatsby-remark-embed-video to @narative/gatsby-theme-novela/gatsby-config.js :

`    },
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.mdx`, `.md`],
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 10000,
              linkImagesToOriginal: false,
              quality: 80,
              withWebp: true,
            },
          },
          {
            resolve: "gatsby-remark-embed-video",
            options: {
              width: 800,
              ratio: 1.77, // Optional: Defaults to 16/9 = 1.77
              height: 400, // Optional: Overrides optional.ratio
              related: false, //Optional: Will remove related videos from the end of an embedded YouTube video.
              noIframeBorder: true, //Optional: Disable insertion of <style> border: 0
              urlOverrides: [
                {
                  id: 'youtube',
                  embedURL: (videoId) => `https://www.youtube-nocookie.com/embed/${videoId}`,
                }
              ] //Optional: Override URL of a service provider, e.g to enable youtube-nocookie support
            }
          },
          { resolve: `gatsby-remark-copy-linked-files` },
          { resolve: `gatsby-remark-numbered-footnotes` },`

**Comment by pierrenel** [comment]
@aleccool213 later today I'll create a PR that adds all the bits we need to Novela - instagram + video embeds etc... hopefully it gets accepted 👍

**Comment by jpvalery** [comment]
@pierrenel looks like this was dealt with in #250 - I'll close this issue and you can reopen if it's not the case :)
