### ISSUE TITLE
Doesn't build on Node 13

### ISSUE THREAD

**Issue by eugenejeonme** [narative/gatsby-theme-novela#248]
I haven't checked where to use the Sharp 0.22.x version. (I'm sorry.)
But, I found it by looking at the issue log below. Using on Sharp 0.22.x somewhere.
![image](https://user-images.githubusercontent.com/36671804/72664183-27e62900-3a3e-11ea-83a8-b5aae3d7ca7c.png)
![image](https://user-images.githubusercontent.com/36671804/72664186-30d6fa80-3a3e-11ea-8dd4-2c60817a1b63.png)

Here is a reference.
-> https://github.com/lovell/sharp/issues/1909

So, It will not build as node 13.
Of course, I use a system like NVM, so I succeeded in building it by lowering the node version. 
I think there will be someone suffering from the same problem as me, so I will tell you the cause. :)

**Comment by NotoriousRebel** [comment]
@eugenejeonme I ran into this same error! I did yarn upgrade --latest although doing yarn upgrade sharp should fix it as well

**Comment by brotzky** [comment]
@eugenejeonme could you confirm @NotoriousRebel's recommendation works? If it does please close this issue. Appreciated!
