### ISSUE TITLE
[Feature request] Code blocks, Tags, and Author's page

### ISSUE THREAD

**Issue by johnletey** [narative/gatsby-theme-novela#25]
I have quite a few new features that I would love to have added!

1. Language titles: Like Gatsby does on their site, I want to be able to have a banner to display the current language of the code block
2. Copy: Again, like Gatsby does on their site, I want to be able to copy the code in a code block with a click of a button!

For the above two points you can refer to this Gatsby PR: https://github.com/gatsbyjs/gatsby/pull/15834

3. Tags: Would love to have tags for posts and tag pages
4. Author pages: Would love to have a link to an author page (e.g. https://example.com/author/john-doe) with all of their posts authored by them

Thanks again for starting work on multiple author support @brotzky!

**Comment by johnletey** [comment]
And also:

5. Code titles: Titles for code blocks

**Comment by brotzky** [comment]
Thanks for the ideas, John. (btw, working towards co-authoring right now)

1, 2 & 5. This is possible and something that would be nice with code blocks.

3 & 4. Tags/Categories & Author pages. As people use the theme and it matures it'll be a good idea to add it in. Will add it to the roadmap. I'm not sure we'll be able to get to immediately.

**Comment by johnletey** [comment]
@brotzky Copy doesn't look very good on mobile:

<img src="https://user-images.githubusercontent.com/30328854/62618265-b55c1380-b90b-11e9-9c23-dbc7282ba05d.png" height="500" />

**Comment by alfieqashwa** [comment]
@johnletey 
I already modified on https://story.alfieqashwa.me/testing
here in https://github.com/alfieqashwa/alfieqashwa.me/blob/master/src/%40narative/gatsby-theme-novela/components/Code/Code.Prism.tsx

I don't know yet how to contribute in github. sorry

**Comment by johnletey** [comment]
@alfieqashwa By modified, do you mean that you fixed the mobile copy button appearance?

**Comment by brotzky** [comment]
Yikes, will update. Moving fast right now.

**Comment by alfieqashwa** [comment]
@johnletey no, not ye. I just added the Language Title.

**Comment by johnletey** [comment]
I see @alfieqashwa ... let's see what @brotzky thinks about the design and whatnot

**Comment by brotzky** [comment]
Wont be adding Language tags. This can be done through shadowing in the future.

Fixing mobile alignment bug.

**Comment by johnletey** [comment]
> Wont be adding Language tags. This can be done through shadowing in the future.

1. Will you be adding the code titles?
2. Is there a way that I can "import" the package code instead of completely overriding everything, so that I don't become so outdated with the package?

> Fixing mobile alignment bug.

Wonderful!

**Comment by brotzky** [comment]
v0.0.9 removes the copy button on mobile.

the default theme for code blocks we want to keep more minimal like those found on https://overreacted.io or http://kentcdodds.com

code titles will not be added by default to the code blocks (html, jsx, js, etc)

**Comment by johnletey** [comment]
Understand ... thanks for working on this @brotzky!

**Comment by tcostaco** [comment]
I'll be working on author's page very soon. We'll keep you posted, @johnletey!

Thanks for all the suggestions, everyone!

**Comment by johnletey** [comment]
awesome ... thank you so much @tcostaco!

**Comment by brotzky** [comment]
I've created a new issue just for Authors.

If you have any more suggestions please open a new issue.

**Comment by chakrihacker** [comment]
Hey, I would like to help on tags/categories. Also I feel adding code title should be fine. what do you think??

**Comment by brotzky** [comment]
Hey, that's awesome! 

Off the top of my head we'd need
- Updated design with tags/categories visible (done by our team)
- New pages that shows a list of specific tags/categories of articles selected
- New Frontmatter with tags/categories and createPages including that logic

Code title might be a good idea. Still on the fence about it.
