### ISSUE TITLE
gatsby-cli 

### ISSUE THREAD

**Issue by SabariVig** [narative/gatsby-theme-novela#251]
**Version of Novela you are using**
gatsby cli [1.3.7]
**Number of posts you have and which data source**
(Local, Contentful options)
local 
**Describe the bug**

**To Reproduce**
when installing from gatsby cli .iget error with sharp package

**Screenshots**

![image](https://user-images.githubusercontent.com/33371586/72677524-4b06ec00-3ac3-11ea-8668-9594ce433f8b.png)

![image](https://user-images.githubusercontent.com/33371586/72677531-565a1780-3ac3-11ea-9a66-b19c9fb85ef7.png)

**OS Tried**
Ubuntu And Windows

**Comment by brotzky** [comment]
Ah, you must be using node 13.  This is a known issue: https://github.com/narative/gatsby-theme-novela/issues/248

Shall work in resolving it.

**Comment by SabariVig** [comment]
I also tried node 12 and node 10 ,sharp throws out an error every time 
![image](https://user-images.githubusercontent.com/33371586/77137280-3c24c180-6a93-11ea-852e-3fcd3f00a664.png)

**Comment by brotzky** [comment]
It's an issue with Gatsby's sharp plugin most likely. Not sure how to get around this specific to each OS but i'd recommend googling around or creating an issue on Gatsby's repo to get better support. Sorry I can't help much with this one.
