### ISSUE TITLE
Highlighting doesn't work on scrollable code blocks

### ISSUE THREAD

**Issue by johnletey** [narative/gatsby-theme-novela#26]
@brotzky I'm running into the same problem outlined here: https://github.com/kentcdodds/kentcdodds.com/pull/116

Fix: https://github.com/kentcdodds/kentcdodds.com/commit/1be8b0b08ab7e55a9658fc86ed5be6599d67c2bf

**Comment by brotzky** [comment]
@johnletey I tried the fix in the PR but doesn't seem to work. Will get back to it some other time.

**Comment by brotzky** [comment]
https://github.com/narative/gatsby-theme-novela/commit/5cb0c25c67b75523988055c45e69b569b8264d2f

Will deploy in latest release
