### ISSUE TITLE
could not find a copy of gatsby to link in

### ISSUE THREAD

**Issue by slorber** [narative/gatsby-theme-novela#260]
Hi,

I'm unable to upgrade my gatsby version to latest, due to this error on yarn install:

```
error An unexpected error occurred: "could not find a copy of gatsby to link in /Users/sebastienlorber/Desktop/projects/sebastienlorber.com/node_modules/@narative/gatsby-theme-novela/node_modules".
info If you think this is a bug, please open a bug report with the information provided in "/Users/sebastienlorber/Desktop/projects/sebastienlorber.com/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I'm using yarn v1.21.1 and here's a repro: https://github.com/slorber/sebastienlorber.com/tree/33d338b785ead5a35c82e81cf95e9439c5156ef1
The repro has latest novela 0.13.2

I'm unable to upgrade to above gatsby ^2.15.37

Also found this issue: https://github.com/Kentico/gatsby-source-kontent/issues/48
It may be because novela does depend on gatsby? don't know.

Has anyone be able to run on latest gatsby so far? Seems the example repository is not on latest for example.

**Comment by jpvalery** [comment]
Seems to be reported also on Gatsby and Yarn
gatsbyjs/gatsby#12019
yarnpkg/yarn#7061

**Comment by jpvalery** [comment]
I'd suggest using a previous version of Gatsby until things get sorted out :)

**Comment by slorber** [comment]
Actually I've deleted my yarn.lock and node_modules, and it seems to work fine now. I'm closing it but feel free to reopen if you feel there's something to fix
