### ISSUE TITLE
Suggest tags for article (It's already applied to my custom version) 

### ISSUE THREAD

**Issue by eugenejeonme** [narative/gatsby-theme-novela#265]
I suggest an article's Tags features.

I got an idea from **[PR#153](https://github.com/narative/gatsby-theme-novela/pull/153)** (; from the **[nnnkit:AN-category](https://github.com/nnnkit/gatsby-theme-novela/tree/AN-category)**, Thank you for your work.)

Also, _[can turn on / off the tags section](#)_ in gatsby-config.js. [_Picture 2_]
_[When clicking a tag](#)_, there is also a screen to view only articles related to the tag.
_[The UI of the tag list can be changed to the desired style](#)_ in one place. [_Picture 3_]

If there are many people who want to, and the owner of this theme allows it, I will create a PR.

Check my Branch now. **[HERE -> my branch link](https://github.com/GHieut/gatsby-theme-novela/tree/%40feature/apply-tags)**
Also, can check my PR on my forked version. **[HERE -> my PR link about apply tags](https://github.com/GHieut/gatsby-theme-novela/pull/1)**

However, they are forked as of @ narative / gatsby-theme-novela @ 0.13.1. _[It is not the latest version](#)_. (Failed to update due to contentful issue.)
 _[Caution! The disqus is applied](#)_.

Oh! I almost forgot.
I haven't used contentful yet. An error occurred and could not be applied. So _[it only applies to local posts](#)_.

**Thank you for reading, your time.**
**And Thanks so much to @narative for making a great theme.**

[Picture 1]
![image](https://user-images.githubusercontent.com/36671804/73342364-bb7eeb80-42c1-11ea-8a6f-af3a7d9b3700.png)

[Picture 2]
![Screen Shot 2020-01-29 at 6 08 34 PM](https://user-images.githubusercontent.com/36671804/73342676-655e7800-42c2-11ea-8ed0-d17d0db5587f.png)

[Picture 3]
![image](https://user-images.githubusercontent.com/36671804/73343345-d7838c80-42c3-11ea-815f-3d9832f502b5.png)

**Comment by brotzky** [comment]
We actually have a branch that supports tags/categories. The only issue is we didn't create the final design for it.

https://github.com/narative/gatsby-theme-novela/tree/%40feature/categories

If you want feel free to open a PR and we can review it and see how the implementation was done.

**Comment by eugenejeonme** [comment]
> We actually have a branch that supports tags/categories. The only issue is we didn't create the final design for it.
> 
> https://github.com/narative/gatsby-theme-novela/tree/%40feature/categories
> 
> If you want feel free to open a PR and we can review it and see how the implementation was done.

Thanks for the comment.
OK, I will try to open PR. 👍

**Comment by eugenejeonme** [comment]
I created [PR#268](https://github.com/narative/gatsby-theme-novela/pull/268/files).
So, I will close this card. thx! :)
