### ISSUE TITLE
"unsupported social link name=dev"

### ISSUE THREAD

**Issue by mjsarfatti** [narative/gatsby-theme-novela#266]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.
_I can but I don't have the time right now, I don't know when I'll be able to :/_

# Description

### Version of Novela you are using
0.13.2

### Number of posts you have and which data source
* [x] Local - 1 post, the default one
* [ ] Contentful

### Describe the bug
When I try to `build` I get the error:  
**WebpackError: unsupported social link name=dev / url=https://dev.to/mjsarfatti**

### To Reproduce
1. Go to `authors.yml`
2. Add a dev.to social URL (eg: `- url: https://dev.to/mjsarfatti`)
3. Run `yarn build`

### Expected behavior
It should build :)

### Additional context
What I think happens is that if `name` is not specified, it tries to infer it from the hostname, which is **dev**. But the key used in `SocialLinks.tsx` is **devto**. Hence it fails.

**Comment by brotzky** [comment]
This is specifically for `authors`.
We've seen the issue appear before: https://github.com/narative/gatsby-theme-novela/pull/235#commitcomment-36795543

Any change you could tackle this one @mjsarfatti? I believe it could be a good first issue :)

**Comment by brotzky** [comment]
Believe this has been fixed.
