### ISSUE TITLE
Mailchimp integration broken, `captcha` error message

### ISSUE THREAD

**Issue by aleccool213** [narative/gatsby-theme-novela#269]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Version of Novela you are using

0.13.2

### Number of posts you have and which data source
* [x] Local
* [ ] Contentful

### Describe the bug

Error when trying to enter email using mailchimp plugin.

### To Reproduce
1. Go to any post

I deployed it here from [this pull-request](https://github.com/aleccool213/blog/pull/107):

https://deploy-preview-107--alec-brunelles-blog.netlify.com/

2. Enter email
3. Error message appears

### Expected behavior

- moves to new tab where mailchimp sub is completed

### Screenshots

![Screenshot at Jan 30 12-56-35](https://user-images.githubusercontent.com/6475934/73478184-9d69c780-4363-11ea-95b2-ccb62ff57e0f.png)

### Browser

Brave MacOSX
Safari Iphone XR

### Additional context

All code to reproduce is here: https://github.com/aleccool213/blog/tree/enable-mailchimp. 

No console messages in the dev tools :/

**Comment by brotzky** [comment]
Maybe related with?
https://github.com/narative/gatsby-theme-novela/issues/121

**Comment by aleccool213** [comment]
@brotzky I thought that but was able to reproduce on Safari for IPhone.

**Comment by jpvalery** [comment]
I'd tend to think this is from MailChimp as there's no mention of captcha in the original code of the plugin. They might have updated their forms. 

I'd suggest opening an issue in the original repo linking back to this one. I know Benjamin was planning on fixing 121 and similar issues by February.

**Comment by aleccool213** [comment]
A work-around which was purposed:

https://github.com/benjaminhoffman/gatsby-plugin-mailchimp/issues/15#issuecomment-433602134

This error stems from the fact I have reCAPTCHA enabled on my email list.

**Comment by brotzky** [comment]
Thanks for updating us @aleccool213
