### ISSUE TITLE
add changelog

### ISSUE THREAD

**Issue by sw-yx** [narative/gatsby-theme-novela#27]
this project is coming along quickly. bit hard to keep track of changes. will you consider adding a changelog? you can use tools like `auto-changelog`, and also only making PR's instead of direct commits may help. totally up to you of course.

**Comment by brotzky** [comment]
Good call. Right now we've bene optimizing for speed since it's still early days and there are a lot of little fixes to be made.
Probably within 1-2 days I'll move to PRs and look into change log tools.
Appreciate all the feedback and suggestions so far.
