### ISSUE TITLE
Dark - Light mode change animation is buggy

### ISSUE THREAD

**Issue by dorukusumezbas** [narative/gatsby-theme-novela#271]
### Version of Novela you are using
0.13.2

### Number of posts you have and which data source
* [1 ] Local
* [0 ] Contentful

### Describe the bug
Dark mode - light mode change animation is buggy, its not like your live demo. I think there is a transition difference between hero and articles sections, which shows a line when swapping between dark and light mode.

### To Reproduce
1. Follow normal installation steps 
2. On terminal cd to directory and: `gatsby develop`
3. Go to localhost:8000 and change from dark mode to light mode repeatedly.

### Expected behavior
It should behave like on your demo: https://novela.narative.co/

### Screenshots
You can clearly see the problem on this video: [https://www.loom.com/share/9dbc0a7178d4440ba59e58836bd7c9f6](https://www.loom.com/share/9dbc0a7178d4440ba59e58836bd7c9f6)

### Browser
Chrome

**Comment by brotzky** [comment]
This is an existing bug that we'd love help on!
The issue arises from trying to animate a CSS linear-gradient which is not possible.

Going to close this one in favour of the original:
https://github.com/narative/gatsby-theme-novela/issues/119
