### ISSUE TITLE
Possible to do a manual release?

### ISSUE THREAD

**Issue by aleccool213** [narative/gatsby-theme-novela#272]
# Description

Is it possible we can get a manual release of the project with recent commits? It doesnt look like the build will be fixed anytime soon.

### What are you trying to achieve?

`canonical_url` support.

### Additional context
_Add any other context about the problem here._

**Comment by brotzky** [comment]
oops, sorry!

published latest to `0.13.3`

**Comment by aleccool213** [comment]
Hmm, seems like the publish didnt work as expected?

The new code hasnt been added.

For this pr, see the cypress tests are failing: https://github.com/aleccool213/blog/pull/113
