### ISSUE TITLE
Add Discord to social site metadata

### ISSUE THREAD

**Issue by Shackless** [narative/gatsby-theme-novela#276]
### Is your feature request related to a problem? Please describe.
I'd like to publish an invite link to my Discord channel on my site. Unfortunately, Discord is not in the list of recognized social providers and there is no icon available.

### Describe the solution you'd like
It should appear next to the other social sites like twitter, linkedin etc. and should also be visualized by an icon.

### Describe alternatives you've considered
I could probably shadow the component and implement the link there but I think this is a rather common feature that others might also like to have.

**Comment by brotzky** [comment]
This would be a great PR.

Here's what needs to be updated (from a previous PR adding an Icon) in order to add a Discord Icon:
https://github.com/narative/gatsby-theme-novela/pull/274

Closing this issue as will only accept PRs for it.
