### ISSUE TITLE
Is there concise documentation on how to deploy this theme?

### ISSUE THREAD

**Issue by NotoriousRebel** [narative/gatsby-theme-novela#277]
# Prerequisites
* [X] Have you searched the issue tracker for similar issues (either past or present)?
* [X] Can you reproduce the issue consistently?

# Description
Is there a blog post or place where there is documentation on how to deploy this theme? This theme looks very interesting and I want to use this for blogging; however, trying to deploy it has been a lackluster time. 

### Version of Novela you are using
Latest
### Number of posts you have and which data source
* [default number] Local
* [0] Contentful

### What are you trying to achieve?
Build site and deploy to github pages.

### What's blocking you?
Did ```yarn workspace www build``` and got this error
```
failed Building static HTML for pages - 3.677s

 ERROR #95312 

"document" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html


  68 |     overlayBgColorStart: overlayBgColorStart,
  69 |     parentRef: wrapRef,
> 70 |     portalEl: portalEl || document.body,
     | ^
  71 |     scrollableEl: scrollableEl || window,
  72 |     transitionDuration: transitionDuration,
  73 |     zoomMargin: zoomMargin,


  WebpackError: ReferenceError: document is not defined
  
  - Controlled.js:70 Controlled
    node_modules/react-medium-image-zoom/dist/esm/Controlled.js:70:1
  
  - Code.Prism.tsx:33 Promise._execute
    @narative/gatsby-theme-novela/src/components/Code/Code.Prism.tsx:33:36
  
  - Anchor.tsx:18 MappingPromiseArray.PromiseArray._iterate
    @narative/gatsby-theme-novela/src/components/Anchor/Anchor.tsx:18:16
  

error Command failed with exit code 1.`
```

### Additional context

When repo was first cloned did yarn upgrade --latest as sharp was breaking due to me using version 13 of node.

**Comment by brotzky** [comment]
@NotoriousRebel we've recently written a post on how to deploy it:
https://www.narative.co/articles/building-your-own-blog-with-gatsby-and-novela

Let me know if you have any more question. For now I'll close this issue.
