### ISSUE TITLE
Shadowing UX Redux

### ISSUE THREAD

**Issue by sw-yx** [narative/gatsby-theme-novela#28]
hey @christopherbiscardi and @brotzky 

so here's my repro: https://github.com/sw-yx/swyxdotio/tree/brokenShadowingReport

(note the branch name)

if you clone that and `yarn` and `yarn start` you'll see

![image](https://user-images.githubusercontent.com/6764957/62591635-3da3cf80-b89e-11e9-92d2-5114127c318c.png)

however i have this exact file ejected using the current `gatsby-theme` version

i think this is true for all *.tsx files except index.ts. this is why i believe something is wrong with the shadowing, that is NOT related to providers for MDX like in #22

**Comment by ChristopherBiscardi** [comment]
This isn't a shadowing issue. some of your content has a `hero` and some of it doesn't, resulting in `null` for `article.hero`.

See here that it happens without shadowing:

![Screen Shot 2019-08-06 at 8 20 43 PM](https://user-images.githubusercontent.com/551247/62592757-345c3800-b889-11e9-9e88-98331baeaf8c.png)

See here the null field in the data:

![Screen Shot 2019-08-06 at 8 27 57 PM](https://user-images.githubusercontent.com/551247/62592758-345c3800-b889-11e9-9e78-b7d241b1e38b.png)

and see here an example of a post that has a hero and one that doesn't.

![Screen Shot 2019-08-06 at 8 30 42 PM](https://user-images.githubusercontent.com/551247/62592759-345c3800-b889-11e9-927e-cf2da31325a0.png)
![Screen Shot 2019-08-06 at 8 30 45 PM](https://user-images.githubusercontent.com/551247/62592761-34f4ce80-b889-11e9-892a-18d03e24ed2a.png)

**Comment by brotzky** [comment]
Nice investigation, Chris. 👌

On a side note, I can allow that code to fail more gracefully if there is no provided hero image.

**Comment by sw-yx** [comment]
you havent told me something i dont know yet. as you can see i shadowed specifically to https://github.com/sw-yx/swyxdotio/blob/brokenShadowingReport/src/%40narative/gatsby-theme-novela/sections/articles/Articles.Grid.Tiles.tsx#L68-L70 get rid of the hero image dependency and expected it to work. why does shadowing in this case not work?

**Comment by brotzky** [comment]
@sw-yx and @ChristopherBiscardi I've tried digging into this deeper this morning.

I've created a repo that shows shadowing working.
_but_ I could only get shadowing to work properly for the Grid and Rows when I removed the `React.context` from `Articles.Grid.js` and shadowed `templates/articles.template.js`

Pull down and run `master`. Shadowing is working here.
https://github.com/brotzky/novela-shadowing-test

git checkout to `broken` and you'll notice shadowing doesn't work. I'm not sure if this is because of `React.context` or `articles.template` being the problem.

**Comment by ChristopherBiscardi** [comment]
> For some reason without restarting gatsby it does not show the new shadowed component..🤪

That's a known issue unfortunately. hot-loading for new files doesn't work because they aren't being watched by webpack. It's on my list and I have some prototype code written for handling this on deletion, etc.

**Comment by brotzky** [comment]
There's some funky stuff going on with shadowing. I'm not entirely sure what's happening but will wait for the spec to mature and revisit the issue with the article sections.
