### ISSUE TITLE
Loading Speed - Mobile

### ISSUE THREAD

**Issue by mostafachatillon** [narative/gatsby-theme-novela#283]
Is loading speed optimized for mobile? the score is only 70 (but desktop is >90)
![pagespeed](https://user-images.githubusercontent.com/8183572/74586264-20d31c00-4fe6-11ea-8bd4-932de22d457c.png)
![pagespeed_desktop](https://user-images.githubusercontent.com/8183572/74586261-1f095880-4fe6-11ea-933b-303447544e11.png)

**Comment by imdigo** [comment]
I think it is caused by first page rendering. 
It renders header and author text first and renders articles later.
It might be take a little long time for rendering index page articles.
