### ISSUE TITLE
Title Text Overflows in Mobile in Other Languages 

### ISSUE THREAD

**Issue by shunkakinoki** [narative/gatsby-theme-novela#285]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Number of posts you have and which data source
* [x] Local
* [ ] Contentful

### Describe the bug

While in mobile, the title overflows to the right in languages other than English, in this case, Japanese.
I believe this could be fixed through css

### Expected behavior

The title text should not overflow in other languages too.

### Screenshots

![image](https://user-images.githubusercontent.com/39187513/74601048-bf41a900-50dc-11ea-8518-a621b3043673.png)

### Browser
Chrome

### Additional context

None

**Comment by chengcyber** [comment]
I run into this issue... after some research, I think the `code`, `a` has style issue in mobile.

such as:

```md
### post content

`a very loooooooooooooooooooooooooooooooooooooooooooooooooong line`

- http://www.example.com/looooooooooooooooooooooooooooooooooooooooooooong-path
```

The line width will exceed the post content width. This leads to an unexpected width in page

**Comment by brotzky** [comment]
fix is merged, to be deployed.
