### ISSUE TITLE
Proxy Redirect 200 - posts do not show

### ISSUE THREAD

**Issue by mostafachatillon** [narative/gatsby-theme-novela#288]
Hi, I am trying to make a 200 redirect to my blog (using Netlify). the blog landing page shows, but nothing else works:  my posts don't show, neither my picture, night mode, or copy link.
![Screenshot from 2020-02-17 12:08:52](https://user-images.githubusercontent.com/8183572/74648963-f10b4c00-517e-11ea-85eb-33ff4ba4dc36.png)

With a 301 redirect, everything works fine.

**Comment by brotzky** [comment]
Likely because it's not setting the cookie/storage properly to show the right type of list?
Im not entirely sure what it could be and quite hard to debug this. What does the console say?

**Comment by mostafachatillon** [comment]
It's a problem with _redirects file. I had to do it manually with my simple landing page, and I made ~20 redirects manually. Doing it with a Novela blog is probably much time-consuming.

I mentioned the feature request in Gatsby:
https://github.com/gatsbyjs/gatsby/issues/21704

**Comment by brotzky** [comment]
Sounds like their solution with the autogenerated redirects makes the most sense. Have you tried that out?

**Comment by mostafachatillon** [comment]
No, I didn't try yet, I made the redirects manually. Will think about it
next time

**Comment by brotzky** [comment]
I would recommend going down that route. A small price to pay for future maintenance.
