### ISSUE TITLE
Hero image doesn't show in social posts except Facebook

### ISSUE THREAD

**Issue by mostafachatillon** [narative/gatsby-theme-novela#293]
Hero image of my blog post doesn't show in most social media posts. I failed with LinkedIn, Twitter and Reddit. Only Facebook worked.

This feature is very important. Without image, a post is almost invisible.

**Comment by brotzky** [comment]
Agreed @mostafachatillon. Any chance you could take a look at the HTML tags in the source and see if you're able to fix it and PR?

**Comment by aleccool213** [comment]
It works for me?

code for reference:

https://github.com/narative/gatsby-theme-novela/blob/8a4a9b145954c2bc92a949d8b04fb95bf2ebdf00/%40narative/gatsby-theme-novela/src/components/SEO/SEO.tsx#L91

**Comment by mostafachatillon** [comment]
@aleccool213 the description works for me too, but not the image, except for Facebook. 

I viewed the html source code, and there's an image path, but no image there:

`<meta data-react-helmet="true" name="twitter:image" content="https://melwy.com/blog/static/ec57331f3770d9abb2f5b030d8189768/3bd88/feedbackdata.jpg"/>`

The hero image got reprocessed and appears with another path and extension:

https://melwy.com/static/ec57331f3770d9abb2f5b030d8189768/05e80/feedbackdata.webp

 here's my blog post: https://melwy.com/blog/car-t-cells-for-solid-cancers-less-risks-by-feeding-back-clinical-data

**Comment by aleccool213** [comment]
@mostafachatillon Tried making the `basepath` empty?

**Comment by mostafachatillon** [comment]
@aleccool213 yes, with `basepath: "/"`, it works.
But I can't do that, because I have another site at the root.

**Comment by dsteenman** [comment]
I have the same issue, but with a contentful post:

if you go to this post: https://dannysteenman.com/how-to-pass-the-advanced-networking-specialty-exam

The twitter imagecard content is the following:
name="twitter:image" content="https://dannysteenman.com/preview.jpg"

while the hero image is: https://images.ctfassets.net/6issw7wxujml/5AqaNNVwTjmarN3Fhp1cBQ/c27a6861937bd1b04f336780fdc1b5e8/matt-ragland-02z1I7gv4ao-unsplash.jpg?w=1888&h=1416&q=100

**Comment by mostafachatillon** [comment]
I solved my problem, it was in gatsby-config.js:
I had to put: `siteUrl: `https://mywebsite.com`,`

instead of: `siteUrl: `https://mywebsite.com/basepath` (which is the real URL of the page)

So that's a problem with `basepath` documentation.
I hope it will not create bugs elsewhere.

**Comment by brotzky** [comment]
thanks for sharing your solutioN @mostafachatillon.
