### ISSUE TITLE
How can I use a URL or SVG as hero image in a post

### ISSUE THREAD

**Issue by Promhize** [narative/gatsby-theme-novela#296]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?

# Description
### Number of posts you have and which data source
1
* [x] Local
* [ ] Contentful

### What are you trying to achieve?
I'm trying to add SVGs or HTTP urls as hero image for a post but that breaks the page
### Additional context
![image](https://user-images.githubusercontent.com/20524675/75112854-63c96b00-5648-11ea-9ace-25c89bb501cd.png)

**Comment by brotzky** [comment]
For post heros they must be relative paths to an image file in the project. This file I believe must be an image file. I'm not sure SVGs work and it seems like they dont from your issue.

Let me know if you have any other question
