### ISSUE TITLE
I am unable to change the logo in my theme. I have used the svg logo and have created the folder structure but my site just won't change the logo. Can you please help?

### ISSUE THREAD

**Issue by persie09** [narative/gatsby-theme-novela#297]
# Prerequisites
* [ ] Have you searched the issue tracker for similar issues (either past or present)?
* [ ] Can you reproduce the issue consistently?

# Description
### Number of posts you have and which data source
* [ ] Local
* [ ] Contentful

### Additional context
_Add any other context about the problem here._

**Comment by brotzky** [comment]
Could you link to your site source code?
It's likely you've created the wrong shadowing structure. Don't forget it goes
`@narative/gatsby-theme-novela/...path/to/Logo.tsx`

**Comment by junctionapps** [comment]
As I just went through this and still have some papercuts:
- make sure your typing muscle memory isn't overzealous and change spelling from narative to narrative in the shadow structure
- the svg may need to be converted (namespaces and unsupported bits removed). Tools like https://github.com/react-native-community/react-native-svg can really help with this. I had used Inkscape originally for the svg, but it needed some manually editing before working properly

**Comment by brotzky** [comment]
Thanks for the helpful tips @junctionapps!
