### ISSUE TITLE
How to see Google Analytics of each separate blog post?

### ISSUE THREAD

**Issue by mostafachatillon** [narative/gatsby-theme-novela#298]
I want to see the traffic statistics of each of my blog posts. 

On Google Analytics, I find general information, but not specific to each blog post.

**Comment by brotzky** [comment]
Google should be able to track this without any configuration from Novela or your site. You can use the official GA plugin for Gatsby:
https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/

**Comment by mostafachatillon** [comment]
Yes, I would like post statistics, like on Medium. Now I only have access
with global traffic

**Comment by mostafachatillon** [comment]
It's ok, it's automatic
![Screenshot_2020-02-27-14-15-03-738_com android chrome](https://user-images.githubusercontent.com/8183572/75448563-ba49e880-596b-11ea-86e0-72a9617c4185.jpg)

**Comment by brotzky** [comment]
awesome, thanks for cleaing that up @mostafachatillon
