### ISSUE TITLE
strict typing

### ISSUE THREAD

**Issue by sw-yx** [narative/gatsby-theme-novela#30]
components cant be ejected properly because the types are way too loose by default. i believe bc youre not using strict mode.  is this something you can do or want help on?

**Comment by brotzky** [comment]
To be honest it's been low on the priority list throughout the project. One of the latest commits fixed some types and your PR definitely fixed a silly mistake.

I'm open to help on the types going forward. Will also try to be more conscious and proactive of it going forward.
