### ISSUE TITLE
URL changes when title changes

### ISSUE THREAD

**Issue by mostafachatillon** [narative/gatsby-theme-novela#301]
When title changes, URL of the post changes. This is not convenient, because it basically freezes post name forever (or break all links).  

In Medium, old links (created from the old title) automatically redirect to the new link. 

This feature should exist in Novela.

**Comment by brotzky** [comment]
You can manually set the URL which I think is a fine workaround.
You can use the `slug` paramter

https://github.com/narative/gatsby-theme-novela#post
