### ISSUE TITLE
All posts' excerpts on the tile grid should be visible at all breakpoints

### ISSUE THREAD

**Issue by junctionapps** [narative/gatsby-theme-novela#303]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description
The excerpts in the right column of the tile grid is not visible due to css at some breakpoints. Seems to be fine in row grid view.

### Version of Novela you are using
0.0.1

### Number of posts you have and which data source
* [x] Local
* [ ] Contentful

### Describe the bug
With tile grid selected the excerpt on the rightmost post disappears. 

### To Reproduce
1. Go to demo site https://novela.narative.co/
2. Change the browser's width below and above 1070px
3. Observe the except on the post "Why we built a company ..."
4. See the display status toggle for the except.

### Expected behavior
I believe the excerpt should show in all cases (and would seem to be the intention).

### Screenshots
![Selection_303](https://user-images.githubusercontent.com/8778630/75736398-7d675400-5cd3-11ea-8227-86f759c5a273.png)

![Selection_304](https://user-images.githubusercontent.com/8778630/75736561-ecdd4380-5cd3-11ea-878d-4614a1974cf8.png)

### Browser
Chrome 80

### Additional context
May be related to #299

**Comment by junctionapps** [comment]
It seems that altering the length of the post title plays a part; in one test the except is suppressed if the post is in the rightmost tile and the title is over 35 characters in length (which doesn't always go to two lines), however, at 35 characters or less the except text appears even when in the rightmost tile.

**Comment by brotzky** [comment]
Yes, we try to smartly adjust the line clamps on the text depending on the length of the title (1 or 2 lines). This is to guarantee the alignment for all sizes. It's possible that it's working 100% of the time as we intended. If that's so PRs are welcome ❤️!
