### ISSUE TITLE
default example post capitalizes slug

### ISSUE THREAD

**Issue by tomByrer** [narative/gatsby-theme-novela#309]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Version of Novela you are using
latest

### Number of posts you have and which data source
* 1 Local
* [ ] Contentful

### Describe the bug
The default install has a page titled "My first post using Novela by Narative" which produces the URL:
http://localhost:8000/My-first-post-using-Novela-by-Narative
In general, especially for SEO, all characters for URLs should be lower cased.

### Expected behavior
All lower case URLs

I tried to fix by `.toLowerCase()` everywhere I saw anything about `slug`, but didn't work.

**Comment by tomByrer** [comment]
On further testing, I found editing the `title` of the [demo post](https://github.com/narative/gatsby-starter-novela/blob/master/content/posts/2020-01-01-my-first-post-using-novela-by-narative/index.md)'s yaml in `gatsby develop` the URL slug does properly change to lower case.  Restoring the title back to "My first post using Novela by Narative" will present a new lower case slug as well.

Strange the initial URL is mixed case.

**Comment by KrisBraun** [comment]
I'm also seeing all posts with mixed-case slugs.

**Comment by slorber** [comment]
I've also found out this behavior annoying, so I'm manually providing lowercase slugs for all my posts.

It's particularly painful when hosting on netlify, as it lowercases any url.
https://community.netlify.com/t/my-url-paths-are-forced-into-lowercase/1659


So you navigate to a mixed-case slug, netlify redirects you to lowercase, and on hydration mixed case comes back. This produces a weird feeling for the end user.

**Comment by dsteenman** [comment]
Issue can be closed, fix is in: https://github.com/narative/gatsby-theme-novela/pull/326

**Comment by tomByrer** [comment]
cheers @dsteenman
