### ISSUE TITLE
[proposal] optional hero images

### ISSUE THREAD

**Issue by sw-yx** [narative/gatsby-theme-novela#31]
i hit a hard stop on my time spent trying and failing to shadow things (as per #28) to remove the image dependency in user land 😅 have to fix in the theme itself.

here is my proposal for optional images:

- user passes in a theme option like `optionalImages: true`
- if `optionalImages: true`, then on the main page, no images are shown, just titles and text. this keeps the design somewhat consistent.
- on the article page, if there is an image, show it, if not, just hide it. easy.

ofc this is adding api surface area you may not want to maintain so i totally respect if you turn this down. just noting that i will have to stop here since i do not want images on every article.

**Comment by brotzky** [comment]
I discussed this with @tcostaco and he said without images the design would have to be re-done. So, for this theme, we don't think it would be realistic to add an `optionalImage` option  at this time -- it compromises design too much.

Something we have spoken about internally creating a simpler blog that's as refined as Novela but without the need for images. Maybe that's in the form of shadowing and paramters or maybe that's another them that sits within the @narative family. Right now our hands are quite full but it's if there's overwhelming demand we may jump on it quicker.

**Comment by sw-yx** [comment]
totally get you. please stick to your vision, dont mind me.

**Comment by AryanJ-NYC** [comment]
In case anyone stumbles upon this via Google, follow this feature here: https://github.com/narative/gatsby-theme-novela/issues/43
