### ISSUE TITLE
Add pageLength option to documentation

### ISSUE THREAD

**Issue by derekphilipau** [narative/gatsby-theme-novela#314]
### Is your feature request related to a problem? Please describe.

Currently it is not immediately clear how to change the number of posts per page (i.e. *pageLength*).

### Describe the solution you'd like

It would be helpful if the *pageLength* theme option were added to both the documentation (https://github.com/narative/gatsby-theme-novela#theme-options) and in `gatsby-theme-novela-example/gatsby-config.js`.

Example:
```
  options: {
    contentPosts: "content/posts",
    contentAuthors: "content/authors",
    basePath: "/",
    authorsPage: true,
    pageLength: 6,
    sources: {
      local: true,
      // contentful: true,
    },
  },
```

**Comment by brotzky** [comment]
Good idea! I've added it to the docs. Thanks for bringing it up.

https://github.com/narative/gatsby-theme-novela/blob/master/README.md#theme-options
