### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dsteenman** [narative/gatsby-theme-novela#315]
There were a lot of changes recently which is good I think! Is there a timeline on when we can expect a new release? Is there something we can help you with to make a new release available?

**Comment by brotzky** [comment]
Really soon -- sorry the automated system is broken and Im too busy to fix it right now. Ill do a manual release sometime today!

If not... please bump this thread ❤️ .

**Comment by brotzky** [comment]
https://www.npmjs.com/package/@narative/gatsby-theme-novela
let me know if this works `0.14.0` published

**Comment by dsteenman** [comment]
Yes it worked perfectly for me! Thanks! If you need help with fixing the release pipeline, the community can help. Is there an open issue for it?

**Comment by brotzky** [comment]
No open issue, but you're (or anyone) welcome to setup a new or fix the existing one!
