### ISSUE TITLE
Request Icon Language on top left of the code 

### ISSUE THREAD

**Issue by alfieqashwa** [narative/gatsby-theme-novela#32]
I see the Copy Icon and it would be perfect if there's also has Language Icon on the top left.

![Firefox_Screenshot_2019-08-07T10-06-51 695Z](https://user-images.githubusercontent.com/15263927/62614821-58c21e00-b936-11e9-9fba-87cdfa66f3b2.png)

I really like to help but i'm still noobs about git and how to conrtibute.
I already customize it at my repo https://github.com/alfieqashwa/alfieqashwa.me

Thank you, Sir.

**Comment by johnletey** [comment]
@alfieqashwa I have already requested this in #25 ... and @brotzky said he will start working on the code block language and also code block title features!
