### ISSUE TITLE
Problem changing the logo

### ISSUE THREAD

**Issue by jorejas** [narative/gatsby-theme-novela#325]
# Prerequisites
* [* ] Have you searched the issue tracker for similar issues (either past or present)?
* [*] Can you reproduce the issue consistently?

# Description
### Version of Novela you are using
0.13.1
### Number of posts you have and which data source
* [1] Local
* [0] Contentful

### What are you trying to achieve?
Change the logo
### What's blocking you?
I changed the logo in the node_module and it works properly when I'm using `yarn dev` for previewing it but when I publish it with netlify it is not showed properly I think it's maybe beacuse the novela theme it uses is the one on node_modules nor the one in src like it is showed in the logo change guide but it is not in my repository.
### Additional context
You can find all my code at my repository [here](https://github.com/jorejas/blog-WWW/)

**Comment by aleccool213** [comment]
Changing the logo is done using Gatsby Theme component shadowing:

example: https://github.com/aleccool213/blog/tree/master/src

docs: https://www.gatsbyjs.org/blog/2019-04-29-component-shadowing/
