### ISSUE TITLE
Bug in the read time

### ISSUE THREAD

**Issue by jorejas** [narative/gatsby-theme-novela#327]
# Prerequisites
* [Yes ] Have you searched the issue tracker for similar issues (either past or present)?
* [Yes ] Can you reproduce the issue consistently?
* [ ] Are you reporting to the correct repository?
* [Maybe ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

The readtime in all the posts is always 1 minute. I also saw this in other novela based blogs.

### Version of Novela you are using
0.13.1
### Number of posts you have and which data source
* [2] Local
* [0] Contentful

### Describe the bug

Readtime is always 1 minute

### To Reproduce
1. Go to [my blog](https://blog.jorgeorejas.com)
### Expected behavior

Vary in the different articles depending o the length

### Screenshots

You can check in both the two posts on my blog

### Browser

Chrome and iOS Safari

### Additional context
_Add any other context about the problem here._

**Comment by brotzky** [comment]
I believe its' a minimum of 1 minute. If you post a longer piece of content it'll reflect it.
The math is based on the global words per minute average. It doesn't take into account code blocks and images, unfortunately.
In your case they're both relatively similar in terms of amount of text and it would be strange to be seconds as reading time imo.

**Comment by jorejas** [comment]
I’ll try with a longer post, If it doesn’t change I will try to look in the code

**Comment by brotzky** [comment]
No problem. Appreciate you bringing it up and asking. Thanks @jorejas.
