### ISSUE TITLE
gatsby-plugin-mdx errors when building

### ISSUE THREAD

**Issue by Tommrodrigues** [narative/gatsby-theme-novela#328]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Version of Novela you are using

0.14.4

### Describe the bug
When building (development or production), I receive two `gatsby-plugin-mdx` errors as seen below:

<img width="682" alt="Screenshot" src="https://user-images.githubusercontent.com/33377034/80840144-ecdac080-8bfc-11ea-8cda-1bb7637ac8fb.png">

When building for development, there no issue with the actual web page itself as I can tell, but when building for production, each page you try and access comes back as `404`.

The issue is the same with both my personal website, and the `gatsby-starter-novela` website. 

The issue has only surfaced in the last few days, which leads me to believe that something was broken in a recent update.

### To Reproduce
1. Run `npm update`
2. Run `gatsby develop` or  `gatsby build`

**Comment by dsteenman** [comment]
Same problem here

**Comment by KrisBraun** [comment]
I saw the same thing after upgrading to `0.14.4`, but no longer see it with `0.14.6`.

**Comment by Tommrodrigues** [comment]
@KrisBraun That's strange, I'm still getting the same errors even when using `0.14.6`. Did you change anything other than the theme version?

**Comment by KrisBraun** [comment]
I did rename my posts from `.mdx` to `.md`. I thought I saw the error go away before making that change, but it's possible they were connected.

**Comment by Tommrodrigues** [comment]
@KrisBraun Very strange, I'm still getting the same errors even though I'm using the latest theme version and my posts are `.md`.

Any thoughts on what might be causing this issue?

**Comment by Tommrodrigues** [comment]
I wasn't able to find what was ultimately causing the issue, but I ended up deleting my `node_modules` folder and `package-lock.json` then running `npm install` again, which seems to have solved the issue.
