### ISSUE TITLE
Logo isn't centred

### ISSUE THREAD

**Issue by johnletey** [narative/gatsby-theme-novela#33]
When I have a logo w/ height 32px, it's not centred with the back arrow, even though it's in the range of recommended heights:

![IMAGE 2019-08-07 11:40:41](https://user-images.githubusercontent.com/30328854/62616727-2f8a9900-b908-11e9-89c2-983a4b9cd09f.jpg)

I had to shrink it down to 23px (the size of your logo in the source code) for it to be centred with the back arrow:

![IMAGE 2019-08-07 11:41:15](https://user-images.githubusercontent.com/30328854/62616767-43ce9600-b908-11e9-906f-33d33dc83f9f.jpg)

Is there a way to fix this so that I can keep the logo at 32px but have it centred with the back arrow? In fact, I would actually love to have the logo be 35px, but that looks even more not-centred than 32px

**Comment by johnletey** [comment]
On second thought though ... the logo looks really good on mobile:

<img src="https://user-images.githubusercontent.com/30328854/62618175-7af27680-b90b-11e9-872f-d3762d889110.png" height="500" />

To me though, it just looks tiny on desktop

**Comment by brotzky** [comment]
Ah, know the reason for this one. Will be up soon.

**Comment by johnletey** [comment]
That's amazing @brotzky ... thanks so much!

**Comment by brotzky** [comment]
v0.0.9 should have a fix for this. Changed the implementation for the back arrow.
Let me know if it works for you.

**Comment by johnletey** [comment]
Will do ... trying it out now!

**Comment by johnletey** [comment]
So much better @brotzky ... thanks so much!

![Shot 2019-08-07 at 17 42 38](https://user-images.githubusercontent.com/30328854/62641178-f6b7e780-b93a-11e9-9c19-a8a061664c7e.jpg)
