### ISSUE TITLE
Auto-newsletter

### ISSUE THREAD

**Issue by jorejas** [narative/gatsby-theme-novela#331]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?

# Description
### Version of Novela you are using
0.13.1
### Number of posts you have and which data source
* [1] Local
* [none] Contentful

### What are you trying to achieve?

Having a mail newsletter

### What's blocking you?

I just doubt if the new posts are auto notified or should i send a mail when i want to notify something. If so there is a way to implement that? I did not found any pull request nor issues asking for it.

### Additional context
_Add any other context about the problem here._

**Comment by brotzky** [comment]
You can add Mailchimp but there's no system for auto-generating emails and sending them as you publish no posts.

https://github.com/narative/gatsby-theme-novela#adding-mailchimp
