### ISSUE TITLE
Adding DEV Account or Mail for an Author Results in a Crash

### ISSUE THREAD

**Issue by gurgunday** [narative/gatsby-theme-novela#338]
Title says it. When a DEV account or mailto is added to _an author_ as a social property, it results in a crash.

**Comment by Ba2dones** [comment]
It works for me. Please use the `Bug report` template and providing more details so we can help you solve this issue.

**Comment by gurgunday** [comment]
Alright, it's just that I was sure there  Will check it out and make a proper report if there is indeed a bug...

**Comment by gurgunday** [comment]
Well, you are right. I was just sure that was a clear bug. Seems like that's wrong, it was probably with my environment.
