### ISSUE TITLE
Contributing: Disqus, Image Zooming

### ISSUE THREAD

**Issue by mwood23** [narative/gatsby-theme-novela#34]
Amazing work on the plugin, seriously. I was able to integrate this into my site in a couple hours, customizations and all. There were a couple missing features I was able to add thanks to Component Shadowing and would be happy to make a PR for them if you're interested in bringing them into the library.

## [Disqus comments](https://github.com/caldera-digital/platform/blob/2a9961d7cc3f84bb2d13c24c1d5c03a519a49fef/projects/caldera-www/src/%40narative/gatsby-theme-novela/templates/article.template.tsx#L110)

Gatsby already has a plugin for this and the component could be conditionally rendered if the user passes the config object in. Here's what it looks like in my app after a little styling:

<img width="1214" alt="Screen Shot 2019-08-07 at 11 57 17 PM" src="https://user-images.githubusercontent.com/13633613/62674147-2254c500-b96f-11e9-94e0-f0f81a1aef8f.png">

## [Image Zooming](https://github.com/caldera-digital/platform/blob/2a9961d7cc3f84bb2d13c24c1d5c03a519a49fef/projects/caldera-www/src/%40narative/gatsby-theme-novela/components/Media/Media.RichText.tsx#L17)

I like to zoom in photos when I read them and there's a nifty React library that does all the magic for you. I have it turned on in my app to replace all `img` tags with that component in the MDX.

![2019-08-08_00-02-42 (1)](https://user-images.githubusercontent.com/13633613/62674334-eff79780-b96f-11e9-8ac9-2a26264e4dc8.gif)

I also noticed that when you create the URLs for title that have an apostrophe in there it kebabs between them. Maybe that's expected functionality. 
> https://www.calderadigital.com/blog/the-non-techie-s-guide-to-creating-a-successful-app

Thank you again! If you'd like for me to PR the two features I added let me know how I can run everything locally. If not, all good! Here's a [link to the website](https://www.calderadigital.com/blog) if you want to test them in action.

**Comment by brotzky** [comment]
Wow! I love the site. I've shared it with our team and we're all really impressed.

I'll take a look through the examples. Right now Image Zooming looks really appealing. There's quite a bit I want to do with images within articles and zoom feels like a great addition.

As for Disqus, I think it would be great to have an option or component you can add to your site and it automatically integrates nicely.

ps: you make also want to check out new version of Novela ;) There's quite a bit refactored and I hope it's a seamless transition for you. If not, feel free to reach out and we'll work together to solve it.

**Comment by tcostaco** [comment]
Whoa, this is amazing! I love how nicely everything integrates with your existing brand, too.

Thanks for the great suggestions, both Image Zooming and Disqus are 👌

Nice job!

**Comment by brotzky** [comment]
Image zooming in next release: https://github.com/narative/gatsby-theme-novela/pull/36

Disqus still needs more consideration. Looking at a possible config option. Don't think we will build it into core.

**Comment by chakrihacker** [comment]
Another alternative to disqus https://staticman.net
