### ISSUE TITLE
RSS content for local posts is unprocessed

### ISSUE THREAD

**Issue by KrisBraun** [narative/gatsby-theme-novela#340]
# Prerequisites
* [X] Have you searched the issue tracker for similar issues (either past or present)?
* [X] Can you reproduce the issue consistently?
* [X] Are you reporting to the correct repository?
* [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Version of Novela you are using

0.14.6

### Number of posts you have and which data source
* [X] Local
* [ ] Contentful

### Describe the bug
_A clear and concise description of what the bug is._

`content:encoded` in the generated `rss.xml` is raw Javascript and JSON. See https://useplot.com/rss.xml as an example.

### To Reproduce
1. Create posts locally in Markdown.
2. `gatsby build`
3. Look at `rss.xml`

### Expected behavior
Formatted post content in the `content:encoded` field.

**Comment by KrisBraun** [comment]
I'm happy to help with a PR for this. I can see the issue is in `gatsby-config.js`:

```
                      custom_elements: [{ "content:encoded": edge.node.body }],
```

Replacing `body` with `except` renders reasonable excerpt entries. I'm unsure how to generate full entries. I've played with the query and node elements, but haven't found a way to get the the rendered html.

**Comment by matthewcmckenna** [comment]
I'm experiencing this as well after updating from 0.13.3 to 0.15.6. Came up with the same idea to replace with excerpt, but would prefer using full content text

**Comment by KrisBraun** [comment]
In 0.13.3, I'm guessing only titles were included, and no body? Looking at the history, I see that decision was made here: https://github.com/narative/gatsby-theme-novela/pull/106/files#r319259418

Then, in https://github.com/narative/gatsby-theme-novela/commit/533d71d79128d43827b270e5bb4965b3bad7a3d3#diff-d2a841326f45fc47afc5450fcfea90d1 a commented-out line was uncommented, probably by accident.

**Comment by matthewcmckenna** [comment]
Yea that is correct.

**Comment by KrisBraun** [comment]
Okay, I'll put up a PR. Any objections to me using the excerpt if it's set? i.e. I'll change

```
custom_elements: [{ "content:encoded": edge.node.body }],
```

to

```
custom_elements: [{ "content:encoded": edge.node.excerpt }],
```

**Comment by matthewcmckenna** [comment]
Sounds great to me. It's better than the output we see now.
