### ISSUE TITLE
SEO image URLs double-prefix site URL

### ISSUE THREAD

**Issue by KrisBraun** [narative/gatsby-theme-novela#341]
# Prerequisites
* [X] Have you searched the issue tracker for similar issues (either past or present)?
* [X] Can you reproduce the issue consistently?
* [X] Are you reporting to the correct repository?
* [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Version of Novela you are using

0.14.6

### Number of posts you have and which data source
* [X] Local
* [ ] Contentful

### Describe the bug
_A clear and concise description of what the bug is._

The image path in SEO tags is double-prefixed with the site URL. For example:

```
<meta property="og:image" content="https://useplot.comhttps://useplot.com/static/bd327be4b86de1bc20c6ab3203472998/0ff54/hustle.jpg" data-react-helmet="true">
```

### To Reproduce
1. Create posts locally in Markdown, with a local image specified in the `hero` frontmatter.
2. `gatsby build`
3. Look at the generated page and see `meta` tags like above.

### Expected behavior
The siteUrl is only added once.

**Comment by KrisBraun** [comment]
I verified removing `${site.siteUrl}` from `fullURL` in `SEO.tsx` fixes the issue for me. If this is the proper fix for all situations, I can put up a PR.

**Comment by brotzky** [comment]
go for it <3

**Comment by dsteenman** [comment]
I got the fix up in: https://github.com/narative/gatsby-theme-novela/pull/353, please review 👍

**Comment by KrisBraun** [comment]
Thanks for getting to this first, @dsteenman!
