### ISSUE TITLE
Request to add structured data JSON-LD for SEO improvement.

### ISSUE THREAD

**Issue by dsteenman** [narative/gatsby-theme-novela#346]
Structured data are complementary to meta tags, they describe precisely what is the content of your website. You can, for example, describe an article, a product, some reviews, some books, or even just breadcrumbs.

This structured data gives the opportunity for Google to generate widgets which are displayed in search results. These widgets are always displayed at the top of results, which puts your website in top position!

Google's documentation on structured data: https://developers.google.com/search/docs/data-types/article

Some references with examples of implementation:
https://khalilstemmler.com/articles/how-to-optimize-your-gatsby-blog-for-seo/

I think we can take over the following code (schema.org in JSONLD format):
https://github.com/LekoArts/gatsby-starter-prismic/blob/master/src/components/SEO/SEO.jsx

Google testing tool for structured data using the url (https://prismic.lekoarts.de):
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fnystudio107.com%2Fblog%2Fimplementing-custom-json-ld-structured-data

Who can help or has experience implementing this in gatsby?

**Comment by brotzky** [comment]
If anyone would like to give this a shot, here's a small snippet of how we handle it on for our articles https://narative.co.
The code is a bit old, but the general point is there:

https://github.com/narative/narative.co/blob/master/src/sections/article/Article.Microdata.tsx#L85
