### ISSUE TITLE
Post cards [ 3 posts per row ]

### ISSUE THREAD

**Issue by Nishchit14** [narative/gatsby-theme-novela#348]
### Is your feature request related to a problem? Please describe.
No, It's related to the design and experience.

### Describe the solution you'd like
The home page with postcards (3 posts per row) looks very professional and it gives more readability to pick a good title for a user. If it looks fine then we can design this feature with a configuration option. 

![image](https://user-images.githubusercontent.com/5078921/81254473-c7a8e080-9048-11ea-9c22-5c2da9384473.png)

**Comment by brotzky** [comment]
Hey, this isn't a feature we'll support out of the box, unfortunately. This would be a fork and making your own.

Right now we provide Rows or Grid as the two options.

Appreciate the idea and hope you're enjoying Novela otherwise <3.

**Comment by Nishchit14** [comment]
Thanks @brotzky, I really enjoy this theme. Is there any professional support available for customization?

**Comment by brotzky** [comment]
No, sorry. We struggle to keep up with the bugs reports, feature requests and pull requests as it is. We don't have time to take on paid support right now.
