### ISSUE TITLE
[Refactor] quick idea to make the articles.grid.tiles component not assume 6-8 nodes

### ISSUE THREAD

**Issue by sw-yx** [narative/gatsby-theme-novela#35]
```js
function ArticlesGridTiles({ talks }) {
  if (!talks) return null
  let bisectTalks = []
  let pair = null
  talks.forEach((t) => {
    if (pair) {
      bisectTalks.push([pair, t])
      pair = null
    } else {
      pair = t
    }
  })
  return bisectTalks.map((talkPair) => (
    <Grid>
      <GridItem article={talkPair[0]} />
      <GridItem article={talkPair[1]} narrow />
    </Grid>
  ))
}
```

**Comment by brotzky** [comment]
This is on my list of todos. I want to update how all the Templating works for the article lists.

```
Aritcles.Grid.Rows.tsx
Aritcles.Grid.Tiles.tsx
Aritcles.Grid.tsx
Aritcle.Next.tsx
```
Need to be refactored and made dynamic.
Awesome suggestion <3

**Comment by sw-yx** [comment]
ya tbh i dont even like `<Grid>`. i would use grid row span {1 or 2} to assign grid item width, and then let css grid layout for you.

**Comment by brotzky** [comment]
Refactored quite a bit and used the bisect code you posted here.
Gracias!

Also, author pages can now be enabled in v0.2.0
