### ISSUE TITLE
Unable to change styles & add logo

### ISSUE THREAD

**Issue by gupta-ji6** [narative/gatsby-theme-novela#351]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?

# Description
### Number of posts you have and which data source
* [x] Local - 3 posts
* [ ] Contentful - 0 posts

### What are you trying to achieve?
I'm trying to [change the styles](https://github.com/narative/gatsby-theme-novela#changing-styles) & [logo](https://github.com/narative/gatsby-theme-novela#adding-your-logo) as described in docs.

### What's blocking you?
I tried to follow docs but **neither the styles nor the logo** is updating.

I'm getting the error below when I locally run the site.

```
TypeError: Cannot read property 'colors' of undefined

blog/src/@narative/gatsby-theme-novela/gatsby-plugin-theme-ui/index.js:6

  3 | export default {
  4 |   ...novelaTheme,
  5 |   initialColorMode: `dark`,
> 6 |   colors: {
  7 |     ...novelaTheme.colors,
  8 |     primary: "#000",
  9 |     secondary: "#73737D",

```

### Additional context

My folder structure is as mentioned in docs.

```
blog
  └── src
    └── @narative
      └── gatsby-theme-novela
        └── components
          └── Logo
            └── index.js
      └── gatsby-plugin-theme-ui
        └── index.js
  
```

The content of `gatsby-plugin-theme-ui/index.js` is same as mentioned [here](https://github.com/narative/gatsby-theme-novela#changing-styles)

What am I doing wrong?

**Comment by nicolai92** [comment]
To update the logo, change the following file to your liking:

`src/@narative/gatsby-theme-novela/components/Logo/Logo.tsx`

Colors can be changed by modifying:

`src/@narative/gatsby-theme-novela/gatsby-theme-ui/colors.ts`

Hint: Copy the original files and start modifiying them. I hope that helps! :)

**Comment by ximet** [comment]
@nicolai92 I have the same issue, I tried to change file inside this path: `src/@narative/gatsby-theme-novela/components/Logo/Logo.tsx` but nothing happen.

<img width="616" alt="Screen Shot 2020-09-23 at 6 03 20 PM" src="https://user-images.githubusercontent.com/3358977/94031126-35229700-fdc7-11ea-8a1d-2491c60ad943.png">


And also, what if I want to change some page, templates or some graphQL requests. What I need to do?

**Comment by nicolai92** [comment]
@ximet 

I'd suggest reading through [Gatsby's shadowing functionality](https://www.gatsbyjs.com/docs/themes/shadowing/) first. You should be able to do the necessary changes on your own then. 😉

**Comment by ximet** [comment]
@nicolai92 but I shadowed using right path, `src/@narative/gatsby-theme-novela/components/Logo/Logo.tsx` and nothing happen. Maybe path not correct?

**Comment by nicolai92** [comment]
@ximet 

I think, you missed the `className` inside the SVG definition. If you have a look at the `const LogoContainer = styled.div (...)` right after the `export default Logo;` you see, that the logo is referenced by its `className`. 😇

**Comment by ximet** [comment]
@nicolai92 yes, you're right! My fail! Thank you
