### ISSUE TITLE
unsupported social link name=notionso / url=https://notion.so

### ISSUE THREAD

**Issue by joeljacobdev** [narative/gatsby-theme-novela#356]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description
notionso key was not present in icons in `SocialLinks.tsx`, so Icon was not found resulting in throwing of error.

### Version of Novela you are using
0.15.5

### Number of posts you have and which data source
* [x] Local - 18
* [ ] Contentful

### Describe the bug
Icon for notionso key was not found.

### To Reproduce
1. Pull the latest changes of gatsby-theme-novela
2. gatsby develop in www/
3. You will get Error: unsupported social link name=notionso / url=https://notion.so at localhost:8000/

### Expected behavior
Without specifying the name key for notion, should work without any error.

### Browser
Chrome

### Additional context
Problem occured as replace regex didn't handle .so domain in `getHostname(url)`.

**Comment by brotzky** [comment]
Appreciate the fix on your own issue. ❤️
