### ISSUE TITLE
Landing page

### ISSUE THREAD

**Issue by mostafachatillon** [narative/gatsby-theme-novela#359]
### Describe the solution you'd like
I want to add a landing page, like the Novela company landing page. A blog is great, but a blog+landing page is even better. 
_A clear and concise description of what you want to happen._

### Describe alternatives you've considered
- I considered other blog+landing page themes, but their blog is not as good as Novela
- I hacked together a landing page theme and a blog theme, but it was a nightmare to install (I have 2 Neltlify instances...), and at the end, design is not consistent. See my landing page: www.melwy.com and blog: www.melwy.com/blog

**Comment by brotzky** [comment]
Hey, we won't be implementing this in core and recommend forking. Related issue: https://github.com/narative/gatsby-theme-novela/issues/369.
Good luck!
