### ISSUE TITLE
@narative/gatsby-theme-novela threw an error while running the onCreateNode lifecycle

### ISSUE THREAD

**Issue by codesandtags** [narative/gatsby-theme-novela#362]
# Prerequisites
* [X] Have you searched the issue tracker for similar issues (either past or present)?
* [X] Can you reproduce the issue consistently?
* [X] Are you reporting to the correct repository?
* [X] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Version of Novela you are using
```
    "@narative/gatsby-theme-novela": "0.15.7",
    "gatsby": "^2.22.9",
    "gatsby-plugin-google-analytics": "^2.3.2",
    "gatsby-plugin-mailchimp": "^5.1.2",
    "gatsby-plugin-manifest": "^2.4.9",
    "gatsby-plugin-netlify-cms": "^4.1.40",
    "gh-pages": "^2.2.0",
    "netlify-cms-app": "^2.11.23",
    "netlify-cms-proxy-server": "^1.1.4",
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
```

### Number of posts you have and which data source
* [X] Local
* [ ] Contentful

### Describe the bug

I did an update to the 0.15.7 version, and I have for about 4 posts published successfully before. However, after I ran the build command I started to get this error.

```
"@narative/gatsby-theme-novela" threw an error while running the onCreateNode lifecycle:

Cannot read property 'match' of undefined

  TypeError: Cannot read property 'match' of undefined

  - onCreateNode.js:21 generateArticlePermalink
    [final-blog]/[@narative]/gatsby-theme-novela/src/gatsby/node/onCreateNode.js:21:37

  - onCreateNode.js:93 Object.module.exports [as onCreateNode]
    [final-blog]/[@narative]/gatsby-theme-novela/src/gatsby/node/onCreateNode.js:93:9

  - api-runner-node.js:256 runAPI
    [final-blog]/[gatsby]/dist/utils/api-runner-node.js:256:37

  - api-runner-node.js:375 Promise.catch.decorateEvent.pluginName
    [final-blog]/[gatsby]/dist/utils/api-runner-node.js:375:15

  - debuggability.js:384 Promise._execute
    [final-blog]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [final-blog]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [final-blog]/[bluebird]/js/release/promise.js:103:10

  - api-runner-node.js:374
    [final-blog]/[gatsby]/dist/utils/api-runner-node.js:374:12

  - util.js:16 tryCatcher
    [final-blog]/[bluebird]/js/release/util.js:16:23

  - reduce.js:166 Object.gotValue
    [final-blog]/[bluebird]/js/release/reduce.js:166:18

  - reduce.js:155 Object.gotAccum
    [final-blog]/[bluebird]/js/release/reduce.js:155:25

  - util.js:16 Object.tryCatcher
    [final-blog]/[bluebird]/js/release/util.js:16:23

  - promise.js:547 Promise._settlePromiseFromHandler
    [final-blog]/[bluebird]/js/release/promise.js:547:31

  - promise.js:604 Promise._settlePromise
    [final-blog]/[bluebird]/js/release/promise.js:604:18

  - promise.js:649 Promise._settlePromise0
    [final-blog]/[bluebird]/js/release/promise.js:649:10

  - promise.js:729 Promise._settlePromises
    [final-blog]/[bluebird]/js/release/promise.js:729:18


not finished source and transform nodes - 2.281s
```

### To Reproduce
1. Get the latest version of @narative/gatsby-theme-novela or this project. 
2. Get this repo https://github.com/codesandtags/blog
3. Install dependencies
4. Run `npm run build` and get the error.

### Expected behavior
Should perform the build successfully.

### Screenshots
_If applicable, add screenshots to help explain your problem._

### Browser
N/A

### Additional context
I just updated the dependencies for my repo.

**Comment by codesandtags** [comment]
Alright, guys!  after debugged in details I figure out that I was having an issue given one blank line in one post. The empty blank line (by accident) was responsible for this disaster.

![image](https://user-images.githubusercontent.com/5404833/82709399-2162fa80-9c46-11ea-8fa1-5190255e1324.png)

![image](https://user-images.githubusercontent.com/5404833/82709458-40fa2300-9c46-11ea-9a15-3c5d97880fc2.png)

So I think the bug is a false positive. I don't know if there is another way to give more information (verbose) when the build fails?, Really the description was not enough.

Thanks! for a good job with this Gatsby project 💪🏼

Cheers!

**Comment by akufta** [comment]
You helped me figure out my problem!!
