### ISSUE TITLE
secret posts should have noindex metadata

### ISSUE THREAD

**Issue by slorber** [narative/gatsby-theme-novela#363]
Hi,

Currently, a post with `secret: true` in frontmatter can get indexed by search engines, despite nor appearing on the home page.

This particularly happens if we are using a plugin like gatsby sitemaps etc...

That would be nice to add `<meta name="robots" content="noindex">` in secret posts, so that even if the sitemap references the post, it is not indexed.

**Comment by mako-tos** [comment]
Hi. I'm interested in this issue.
I started GatsbyJS recently, and I want to do something for OSS.
Could I try this issue?

**Comment by slorber** [comment]
yes nobody forbids you to open a PR :)

**Comment by mako-tos** [comment]
Thank you for your reply. I send a PR.
