### ISSUE TITLE
Infinite unsaved changes using Netlify CMS

### ISSUE THREAD

**Issue by IamBlueSlime** [narative/gatsby-theme-novela#368]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [x] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Version of Novela you are using
0.13.3

### Number of posts you have and which data source
* [x] Local 1
* [ ] Contentful

### Describe the bug
Using Netlify CMS, when saving a post, the `Authors` fields refresh so this trigger unsaved changes. We cannot move the post to `In Review` for instance. There is constantly unsaved changes.

### To Reproduce
1. Create a new post using Netlify CMS in editorial mode
2. Try to save

### Expected behavior
The post should save correctly.

### Browser
Chrome, Safari.

**Comment by JoseJesusOchoaTorres** [comment]
Hey @IamBlueSlime did you fix your problem?
I have the same issue, could you please help me?
