### ISSUE TITLE
Add new custom pages

### ISSUE THREAD

**Issue by Nancy-Chauhan** [narative/gatsby-theme-novela#369]
It would be nice to have feature support for adding new pages like `about` or `projects`

**Comment by cr7yash** [comment]
You can take some inspiration from this repo: https://github.com/sadanand-singh/reckoning.dev

Amazing work from him!

**Comment by brotzky** [comment]
Thanks for the share @cr7yash!

We wont support that feature as a default in Novela for the time being and recommend a fork if you want the functionality.
