### ISSUE TITLE
Grid and List Icon are reversed

### ISSUE THREAD

**Issue by kaseyhinton** [narative/gatsby-theme-novela#37]
The List and Grid Icons are reversed. See the image below.

I have selected the grid icon but it is displaying the items in a list format.

![wrongicon](https://user-images.githubusercontent.com/20712428/62741211-612e5d80-b9f7-11e9-869c-fdec967b17d1.PNG)

**Comment by kaseyhinton** [comment]
#38 Fixed

**Comment by brotzky** [comment]
Yeah, small mishap in development. Fixed the icons :)

Thanks for the issues and PR! Appreciate the help.
