### ISSUE TITLE
[Feature] Author's page

### ISSUE THREAD

**Issue by brotzky** [narative/gatsby-theme-novela#39]
Continues out of https://github.com/narative/gatsby-theme-novela/issues/25

- Author pages: Would love to have a link to an author page (e.g. https://example.com/author/john-doe) with all of their posts authored by them

Design preview: https://www.figma.com/file/FifDf1g8AKnrmJvCMqKY95/Gatsby-Theme-%E2%80%93-Novela?node-id=1202%3A1162

**Comment by kaseyhinton** [comment]
Is this being worked already? Really cool page idea. What are you thinking for the route? /author/:id or /author/:name or something else?

**Comment by brotzky** [comment]
Most likely: `/authors/:name`
but will also be able to set an `authorsPath` maybe.

**Comment by brotzky** [comment]
@kaseyhinton @johnletley

You can now enable Authors page via theme options in `v.0.2.0`+

`authorsPage: true`

**Comment by johnletey** [comment]
wonderful! thank you so much @brotzky!
