### ISSUE TITLE
Sitemap feature.

### ISSUE THREAD

**Issue by woosungchoi** [narative/gatsby-theme-novela#399]
I found the RSS function in /rss.xml. 

However, /sitemap.xml was not found.

It would be nice if the sitemap function was added.

**Comment by sarthakmalik** [comment]
That'd be a nice to have out of the box. Gatsby does provides a flexible foundation, just resolve ``gatsby-plugin-sitemap`` in ``gatsby-config.ts`` and set any excludes or outpath opts. 

The declarative approach to content will automatically generate ``<loc>{domain}/{post_path}</loc>`` format for posts and author endpoints.

**Comment by woosungchoi** [comment]
> That'd be a nice to have out of the box. Gatsby does provides a flexible foundation, just resolve `gatsby-plugin-sitemap` in `gatsby-config.ts` and set any excludes or outpath opts.
> 
> The declarative approach to content will automatically generate `<loc>{domain}/{post_path}</loc>` format for posts and author endpoints.

@sarthakmalik  Great! Thx.
