### ISSUE TITLE
module resolution error etc (shadowing)

### ISSUE THREAD

**Issue by webiroha** [narative/gatsby-theme-novela#403]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?

# Description
### Version of Novela you are using
"^0.16.5"

### Number of posts you have and which data source
2
* [x] Local
* [ ] Contentful

### What are you trying to achieve?
ts problem has been appeared on VScode and wants to remove them.
I tried shadowing and I could display the change.
I referred to the article below.
https://github.com/narative/gatsby-theme-novela/issues/257

e.g.
1.Cannot find module '@components/Navigation/Navigation.Footer' or its corresponding type declarations.ts(2307)
<img width="377" alt="Screen Shot 2020-07-29 at 19 49 17" src="https://user-images.githubusercontent.com/24987971/88791475-be0cc000-d1d4-11ea-9824-ffd2d8f6f78a.png">

2.Property 'theme' is missing in type '{ children: (string | number | boolean | {} | ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)>) | (new (props: any) => Component<...>)> | ReactNodeArray | ReactPortal | Element)[]; }' but required in type '{ theme: object; }'.

#### Folder structure
<img width="267" alt="Screen Shot 2020-07-29 at 19 52 11" src="https://user-images.githubusercontent.com/24987971/88791671-104de100-d1d5-11ea-88fe-a30933fb21eb.png">

### What's blocking you?
I can not find out the reason why the error appears.
I guess I need to put something additional file.

Thank you in advance :)

**Comment by Chris927** [comment]
In my understanding, there is no TypeScript config (`./tsconfig.json`), so the path references using scopes (`@components/...`) won't resolve for the TypeScript compiler.

I did the following, which seems to have fixed it (but this may not be the right thing to do in a Gatsby theme):

(all done in `./@narative/gatsby-theme-novela`)

1. Install TypeScript

```bash
npm i typescript --save-dev
```

2. Initialise TypeScript:

```bash
npx tsc --init
```

3. Declare the paths:

```patch
diff --git a/@narative/gatsby-theme-novela/tsconfig.json b/@narative/gatsby-theme-novela/tsconfig.json
index 5dcbbbc..6f1222c 100644
--- a/@narative/gatsby-theme-novela/tsconfig.json
+++ b/@narative/gatsby-theme-novela/tsconfig.json
@@ -4,12 +4,12 @@
 
     /* Basic Options */
     // "incremental": true,                   /* Enable incremental compilation */
-    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
+    "target": "ES2020",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017', 'ES2018', 'ES2019', 'ES2020', or 'ESNEXT'. */
     "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', 'es2020', or 'ESNext'. */
     // "lib": [],                             /* Specify library files to be included in the compilation. */
     // "allowJs": true,                       /* Allow javascript files to be compiled. */
     // "checkJs": true,                       /* Report errors in .js files. */
-    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
+    "jsx": "react",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
     // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
     // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
     // "sourceMap": true,                     /* Generates corresponding '.map' file. */
@@ -43,8 +43,12 @@
 
     /* Module Resolution Options */
     // "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
-    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
-    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
+    "baseUrl": "./src",                       /* Base directory to resolve non-absolute module names. */
+    "paths": {
+      "@components/*": ["components/*"],
+      "@styles/*": ["styles/*"],
+      "@types/*": ["types/*"],
+    },
     // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
     // "typeRoots": [],                       /* List of folders to include type definitions from. */
     // "types": [],                           /* Type declaration files to be included in compilation. */
```

My version of `@narative/gatsby-theme-novela` is `0.18.4`, but there is probably no difference on that.

Does this help?

**Comment by webiroha** [comment]
Thank you @Chris927 !
Tried what you wrote but the errors are still appearing...
I am considering to create a blog myself so it is alright.
Thank you again🙏
