### ISSUE TITLE
Egg shaped crop around author icon

### ISSUE THREAD

**Issue by Michael-Equi** [narative/gatsby-theme-novela#416]
### Description
I have noticed that the author images using the following image gets cropped out in an egg like shape that can be seen below. Note that this occurs with everything else configured to its default presets.

Icon Image: https://drive.google.com/file/d/1NS2qsWRRZ1XjccxvrgT21arpcCRcdcRs/view?usp=sharing

Egg like crop: https://drive.google.com/file/d/1ELlVVMJctw8TD1TbTQ3TqDXsBUEN5YX_/view?usp=sharing

### Version of Novela you are using
1.6.6

### Number of posts you have and which data source
* [x] Local - 1

### To Reproduce
1. With the default novela theme place the image linked above into the content/authors/avatars folder and give the image the appropriate name so that it is used for one of the authors.
2. run the webpage

### Expected behavior
The crop should be uniformly circular and not egg shaped.

### Screenshots
See above

### Browser
Chrome and Safari

### Additional context
I was able to solve the egg crop issue on the home screen by turning 50% to 25% in the Bio.tsx at the following lines. I am not sure why this is the case.

```
const RoundedImage = styled(Image)`
  border-radius: 25%; // changed from 50%
`;
```

**Comment by davinchee** [comment]
I had the exact same problem, but I tried changing border-radius and it didn't work for me. I added `height: 100%;` in `Author.Hero.tsx`
```
const RoundedImage = styled(Image)`
  border-radius: 50%;
  height: 100%;
`;
```

**Comment by vladpasculescu** [comment]
@Michael-Equi @davinchee try using a square image that you've already cropped to fit a 1:1 aspect ratio. If you inspect the image used for Dennis's profile in the theme, the original is square.

**Comment by mabasic** [comment]
@jpvalery @brotzky This can be closed.
