### ISSUE TITLE
White lip on mobile dark mode article page

### ISSUE THREAD

**Issue by Michael-Equi** [narative/gatsby-theme-novela#417]
# Description
On the mobile version of the theme there is a visible white lip when in dark mode on the top of the article page that should not exist. Here is a link to a screen shot showing the issue https://drive.google.com/file/d/1yYlUgHd6orIZ3aW2Bju0GRxVvCfBkyjP/view?usp=sharing

### Version of Novela you are using

1.6.6

### Number of posts you have and which data source
* [x] Local - 1

### To Reproduce
1. Deploy website using the getting started template 
2. open up the webpage on a mobile device
3. click on the article to go to its page
4. Go into dark mode

### Expected behavior
There should be no white bar at the top of the page.

### Screenshots
See description

### Browser
iOS Safari and iOS Chrome

**Comment by JoseJesusOchoaTorres** [comment]
Hey @Michael-Equi this is not a bug. It is part of the design, you can see in my personal blog how it looks if we are not using the dark mode:

https://josejesus.dev/crea-tu-propio-grid-system

![image](https://user-images.githubusercontent.com/8441759/96927568-dbbc8f00-147c-11eb-86e4-4c30d0d46e58.png)


That background color will be the positive of the active theme color (dark/normal mode)

**Comment by mabasic** [comment]
@brotzky @jpvalery This can be closed.
