### ISSUE TITLE
Change gatsby-mdx to gatsby-plugin-mdx

### ISSUE THREAD

**Issue by deadcoder0904** [narative/gatsby-theme-novela#42]
I forked this repo & tried `yarn` & it threw this warning

```js
warning gatsby-mdx@1.0.0: Please install gatsby-plugin-mdx instead
```

I think I also heard somewhere they are moving from `gatsby-mdx` to `gatsby-plugin-mdx` slowly but surely :)

**Comment by brotzky** [comment]
https://github.com/narative/gatsby-theme-novela/blob/master/package.json#L46

We're using `gatsby-plugin-mdx` but forgot to remove gatsby-mdx. Thanks for the reminder and appreciate the issue.

**Comment by deadcoder0904** [comment]
Ohh! Thanks for the theme. Finally, I don't have a reason to not start a blog 😄

**Comment by brotzky** [comment]
This has been fixed in latest PR. Thanks for using Novela. Let us see your blog when you get it live!
