### ISSUE TITLE
Logo changes not building on Gatsby Cloud

### ISSUE THREAD

**Issue by nifl** [narative/gatsby-theme-novela#420]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?

# Description
### Version of Novela you are using
0.17.0
### Number of posts you have and which data source
* [1] Local
* [ ] Contentful

### What are you trying to achieve?
I updated Logo.tsx with my own SVG data. It's working locally but not on Gatsby Cloud. GC displays the default Narative logo.

### What's blocking you?
Adding Logo.tsx to version control breaks the Gatsby Cloud build altogether.

### Additional context
_Add any other context about the problem here._

**Comment by nifl** [comment]
I figured out shadowing and I'm good now

**Comment by dsfrederic** [comment]
> I figured out shadowing and I'm good now

@nifl What did you change to make it work? 

Same story here locally it's working but not via netlify build. I tried removing cache as well...

**Comment by nifl** [comment]
The documentation gives describes how to shadow the logo. https://github.com/narative/gatsby-theme-novela#component-shadowing and https://github.com/narative/gatsby-theme-novela#adding-your-logo. I also found this helpful example https://github.com/aleccool213/blog/blob/master/src/%40alec.brunelle/gatsby-theme-novela/components/Logo/index.js

The issue I had that prevented me from initially succeeding in shadowing the logo was that I had the wrong path. The docs indicate the correct path.

**Comment by dsfrederic** [comment]
I've double checked my path and it seems correct. Locally it builds correctly with the new svg. Any help anyone? Please reopen this issue.
