### ISSUE TITLE
Contentful Media Is Modifying How Content Is Presented

### ISSUE THREAD

**Issue by slavakurilyak** [narative/gatsby-theme-novela#421]
# Prerequisites
* [x] Have you searched the issue tracker for similar issues (either past or present)?
* [x] Can you reproduce the issue consistently?
* [x] Are you reporting to the correct repository?
* [ ] Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome.

# Description

### Number of posts you have and which data source
* [ ] Local
* [x] Contentful

### Describe the bug
It seems that Contentful is properly displaying content when using the "Insert Media" button.

### To Reproduce
1. Login to Contentful
2. Create a new Content
3. In the Body section, click the "Insert Media" button
4. Add content before and after media
5. Click Publish
6. Review the published page and notice how body content (before or after the media) is not properly aligning

### Expected behavior
I expect all paragraphs to be properly aligned with the rest of the body

### Screenshots
![screen](https://user-images.githubusercontent.com/6625584/93146850-bfbb1600-f6a4-11ea-99c9-372d5cd610dc.jpg)
![screen 2](https://user-images.githubusercontent.com/6625584/93140992-3d2c5980-f698-11ea-816d-5df0245d54fd.jpg)

### Browser
Chrome, Firefox, Brave

### Additional context
This issue exists when deploying Novela on Contentful. 
This issue does not exist when running Novela on localhost via `yarn dev`.

**Comment by vladpasculescu** [comment]
@slavakurilyak  check your paragraph indentation in the Contentful markdown editor. I've had this issue in the past with another project.
