### ISSUE TITLE
[Bug] Post not change in webpage when write post

### ISSUE THREAD

**Issue by quaj** [narative/gatsby-theme-novela#44]
When i had changed a post (index.mdx) gatsby noti rebuild. but go to webpage, nothing happend, affect to title, author, content, date

looks like the post was built once times.

can't debug so i make a issue

log terminal look like below
```
 DONE  Compiled successfully in 387ms                                                                      5:57:50 PM
⠀
ℹ ｢wdm｣:
ℹ ｢wdm｣: Compiled successfully.






—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
5 pages                                                                                                          site


```

**Comment by brotzky** [comment]
I believe this known limitation of Gatsby right now. You may want to double check directly with Gatsby. https://github.com/gatsbyjs/gatsby 

https://github.com/narative/gatsby-theme-novela/issues/28#issuecomment-519313076

**Comment by bravo-kernel** [comment]
@quay I had similar problems today (with the hot loading not working). Were you also using the novela starter?  If so I think the starter needs to be fixed or perhaps even re-created so it uses the most recent gatsby starter.

**Comment by quaj** [comment]
argree with @bravo-kernel

**Comment by bravo-kernel** [comment]
@brotzky to be complete, I was encountering problems with hot-reload not working for **existing pages** (on Windows 10). After that I also checked [this theme](https://github.com/ryanwiemer/gatsby-theme-amsterdam) and the hot-loading is no problem there. Perhaps it can be used for inspiration, I especially like the yarn workspace structure, it makes developing (and PRing) so simple. 

If I am missing the point here or doing something silly please let me know, just starting on Gatsby.

**Comment by brotzky** [comment]
I've got lie reloading for me locally. Going to be hard to debug this one.

**Comment by quaj** [comment]
anyway, tested /www and worked now, need move to narative/gatsby-starter-novela
close issue, tks @brotzky

**Comment by quaj** [comment]
and publish too 🙀

**Comment by brotzky** [comment]
Will do, soon!

**Comment by bravo-kernel** [comment]
@quaj could you try the starter again? The hot reloading should work now.

```bash
gatsby new novela-site https://github.com/narative/gatsby-starter-novela
```

**Comment by quaj** [comment]
> @quaj could you try the starter again? The hot reloading should work now.
> 
> ```shell
> gatsby new novela-site https://github.com/narative/gatsby-starter-novela
> ```

looks like it works well 👍

**Comment by brotzky** [comment]
thanks for the help, @bravo-kernel.

and glad it's resolved.
