### ISSUE TITLE
Translate texts-strings

### ISSUE THREAD

**Issue by raulsperoni** [narative/gatsby-theme-novela#449]
# Prerequisites
* [ x] Have you searched the issue tracker for similar issues (either past or present)?
* [ ] Can you reproduce the issue consistently?

# Description
0.18.4 Version of Novela you are using

### Number of posts you have and which data source
* [ 0] Local
* [25 ] Contentful

### What are you trying to achieve?

I want to translate some strings to spanish, like "5 min read", or dates.

### What's blocking you?

I've found out how to shadow components but can't find were these strings are defined.

### Additional context
Thank you!

**Comment by nicolai92** [comment]
@raulsperoni 

Please check the `Article.Hero.tsx` file:

```js
const ArticleHero: React.FC<ArticleHeroProps> = ({ article, authors }) => {
  const hasCoAUthors = authors.length > 1;
  const hasHeroImage =
    article.hero &&
    Object.keys(article.hero.full).length !== 0 &&
    article.hero.full.constructor === Object;

  return (
    <Hero>
      <Header>
        <HeroHeading>{article.title}</HeroHeading>
        <HeroSubtitle hasCoAUthors={hasCoAUthors}>
          <ArticleAuthors authors={authors} />
          <ArticleMeta hasCoAUthors={hasCoAUthors}>
            {article.date} · {article.timeToRead} min read
          </ArticleMeta>
        </HeroSubtitle>
      </Header>
      <HeroImage id="ArticleImage__Hero">
        {hasHeroImage ? (
          <Image src={article.hero.full} />
        ) : (
            <ImagePlaceholder />
          )}
      </HeroImage>
    </Hero>
  );
};
```

**Comment by raulsperoni** [comment]
Perfect thank you! missed that.
