### ISSUE TITLE
Add ability to zoom in on clicked images without opening new tabs

### ISSUE THREAD

**Issue by nikitavoloboev** [narative/gatsby-theme-novela#46]
It's not best UX as now when you click on an image it will open the image in a new tab.

I quite like what Medium has where if you click on an image it will zoom into the image but still let you stay on the page and fade the background. Click again and go back to reading.

There is even a [library](https://github.com/francoischalifour/medium-zoom) that does this effect although it's probably bloated.

If this won't affect the loading speed and the current speed and feel of the theme, it would be awesome to add a feature like this.

**Comment by brotzky** [comment]
This has been updated in the latest release already. (v0.1.0)

Click an imagine in this article
https://novela.narative.co/understanding-the-gatsby-lifecycle-with-narative

**Comment by nikitavoloboev** [comment]
Beautiful. Thank you.
