### ISSUE TITLE
Replace prism with gatsby-remark-vscode?

### ISSUE THREAD

**Issue by bravo-kernel** [narative/gatsby-theme-novela#51]
Are you folks open to replacing prism with https://github.com/andrewbranch/gatsby-remark-vscode? There is a very good [side-by-side comparison of the benefits](https://github.com/andrewbranch/gatsby-remark-vscode#why-gatsby-remark-vscode) of which the two most important ones for me are:

- correct highlighting of highly complex code
- out-of-the-box support for languages as Powershell

**Comment by brotzky** [comment]
I haven't seen that package before. The comparison looks quite solid.
Ill investigate how much work it is but it might not be worth it right now if it's a major rewrite. Would be great if it's a simple swap of plugins.

**Comment by bravo-kernel** [comment]
Thanks, really appreciate the fact that you are open to considering the option and.. no rush, this is not blocking anything. It’s no blocker so no rush. Perhaps this could even be done by somebody contributing. Awesome job on the theme btw, will be migrating soon.

**Comment by brotzky** [comment]
Would love if this was from a contributor.

Did some investigation tonight and it seems like a bit of work to get it to replace Prism. Right now Prism has a lot of momentum and seems to work nicely good enough.

If anyone wants to preserve the current code theme style we have in Novela and migrate to `gatsby-remark-vscode` that would be apprecaited!

**Comment by brotzky** [comment]
I've started on this implementation but ran into some issues with gatsby-plugin-mdx and potentially vscode plugin. Will see when it's all resolved.
