### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by bravo-kernel** [narative/gatsby-theme-novela#52]
Would you folks like me to set up CI for this repo so we can start quality checking the contributions.? If so, I would like to suggest [Github workflows](https://developer.github.com/actions/managing-workflows/) as this will become the de-facto standard IMO. I think you might [need to register here](https://github.com/features/actions) first.

If we do this the PR can be used to preview the result which can then be used to discuss the definitive workflow (build, linting, test, etc.) in more detail. FYI this would be an incremental process so we will start simple, then improve from there. Once it is perfect we could even consider Continuous Deployment for automated releases.

Taken from another repo but to give an idea of what I mean:

![image](https://user-images.githubusercontent.com/230500/62852894-0f355280-bceb-11e9-992e-24d06e0dacaf.png)

**Comment by brotzky** [comment]
This was on my mind, especially now that the initial release has been refactored as is more stable.
CI for automated releases would be fantastic. Netlify for deploy previews built in.
Would really appreciate the help on this one.

**Comment by bravo-kernel** [comment]
It looks like GH Actions is not being enabled for organizations yet. How about we start with Travis for now so we can get things like linting started? **If you agree** I can start work on this today and probably finish it as well. Features will become visible with each commit so you can follow and provide feedback where needed.

To give you an idea I just did the exact same for my new module https://github.com/alt3/sequelize-to-json-schemas, I will use that as a basis.

**Comment by bravo-kernel** [comment]
Closing as a PR is now open
