### ISSUE TITLE
Add Support for YouTube object in `social` array of gatsby-config.js

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#53]
# User Story
As a user, I want to be able to add my YouTube channel as a `SocialIcon` to `Navigation.Footer`.

# Acceptance Criteria
A user can add

```
{
  name: `youtube`,
  url: `https://www.youtube.com/c/thewebdevcoach`,
},
```

to `gatsby-config.js` and a YouTube `SocialIcon` will display on the `Navigation.Footer`.

**Comment by brotzky** [comment]
This is a solid suggestion. Will have it added shortly. Thanks, Arjan.

**Comment by brotzky** [comment]
@AryanJ-NYC you can now use `youtube` as a social icon and link in `v0.2.2`.
