### ISSUE TITLE
Only 2 posts are shown in index page

### ISSUE THREAD

**Issue by dennismorello** [narative/gatsby-theme-novela#54]
Hi,

am I missing something or is it an issue that only the 2 most recent posts are rendered on the index page? The other post pages are generated but they are not reachable from the index page.

**Comment by brotzky** [comment]
Hey Dennis, thanks for the report. Will be on this one right away.

**Comment by brotzky** [comment]
@dennismorello could you tell me the version you're running and how many posts you have? I can't seem to recreate this in latest.

**Comment by dennismorello** [comment]
I have 3 posts and I am using version 0.2.2

**Comment by dennismorello** [comment]
Thank you Dennis!

**Comment by dennismorello** [comment]
> @dennismorello could you tell me the version you're running and how many posts you have? I can't seem to recreate this in latest.
> 
> edit: I've found an issue if you have 3 posts. Thanks for bringing this to our attention, Dennis.

Thank you Dennis!

**Comment by brotzky** [comment]
@dennismorello upgrade to v0.2.3 and it should work.

**Comment by dennismorello** [comment]
Yes the issue has been fixed, thank you!
