### ISSUE TITLE
Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by dennismorello** [narative/gatsby-theme-novela#55]
When starting the dev server, the following error is raised:

> Warning: Each child in a list should have a unique "key" prop.
> 
> Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
>     in InitializeColorMode

<img width="1402" alt="Schermata 2019-08-13 alle 11 34 50" src="https://user-images.githubusercontent.com/19588613/62931328-77089d80-bdbe-11e9-8f32-2b4af89869e7.png">

**Comment by dennismorello** [comment]
I have 3 posts and I am running `gatsby` v2.13.61 and `gatsby-theme-novela` v0.2.2 (both are the latest versions).

**Comment by AryanJ-NYC** [comment]
This'd likely be fixed by upgrading to gatsby-plugin-theme-ui v0.2.23: https://github.com/gatsbyjs/gatsby/issues/16196#issuecomment-516194257

**Comment by brotzky** [comment]
Tested upgrade locally and it doesn't seem to work.
I wouldn't stress too much about the warning, but will keep the issue open and monitor possible solutions.

**Comment by dennismorello** [comment]
Ok, thank you Dennis 👌🏻

**Comment by brotzky** [comment]
This doesn't appear to be happening anymore. I'm going to close it.
Not sure how it was resolved so feel free to reopen if you see it again.
