### ISSUE TITLE
[Proposal] Post links open in new tab

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#58]
**Is your feature request related to a problem? Please describe.**
Nothing is broken. However, as a content creator that wants to keep their tab open in the browser (instead of having links open in the current tab), I believe it'd be nice for all links to open in a new tab.

**Describe the solution you'd like**
I would like a `gatsby-transformer-remark` options property that looks like [this](https://github.com/AryanJ-NYC/webdev-coach-blog/blob/move-to-narrative/gatsby-config.js#L32).

**Describe alternatives you've considered**
I've tried extending the gatsby-config.js: https://github.com/AryanJ-NYC/webdev-coach-blog/blob/move-to-narrative/gatsby-config.js#L32

**Additional context**
I've asked why extending `novela`'s `gatsby-config.js` does not work:
https://github.com/gatsbyjs/gatsby/issues/15549#issuecomment-520958930

Additionally, note that I want input from the community. I'm not demanding a feature change (just yet at least 😏).

**Comment by brotzky** [comment]
Links in the article should open in a new tab by default. agreed.
This should be quite simple to setup. Hopefully it's added by end of day.

**Comment by AryanJ-NYC** [comment]
@brotzky Are you open to open-source help? If so, have you started this yet? If not, I'd love to contribute.

**Comment by brotzky** [comment]
yes, definitely open. this can probably be done by modifying the Anchor component that's passed into MDX.

**Comment by AryanJ-NYC** [comment]
Ah, I was thinking of using https://www.gatsbyjs.org/packages/gatsby-remark-external-links/ to have it in the config rather than in code. Thoughts?

**Comment by brotzky** [comment]
I'm okay with that. Try it out, see if it works. If not, we can always do it the other way.
