### ISSUE TITLE
[Feature] Default hero image

### ISSUE THREAD

**Issue by bravo-kernel** [narative/gatsby-theme-novela#61]
When a user wants to start writing the most probable flow would be:

1. user creates an `index.mdx`
2. user starts typing away on the post
3. user wants to check the results

Currently the creative moment is kind of force stopped because a missing image will:

1. prevent the post from rendering
2. throw an error
3. force the user into first fixing the image (losing focus on content)

**Describe the solution you'd like**

Implement a fallback mechanism like e.g.

- render a default placeholder image if frontmatter variable `hero` is missing/null
- render a default placeholder if  frontmatter variable `hero` is pointing to a non-existing file
- as a bonus... log a warning if the option directly above occurs

This could be a first step into making the theme more defensive when it comes to catching/preventing errors. IMO the end-user should never see an error messages or experience a broken site (unless she really broke something). Preventing the `author` tag breaking the site would be the most logical second step.

ps: I tried to implement this feature myself but no luck so far and thus creating this Request
ps: perhaps the placeholder could be an opportunity to promote the theme/narative as well

**Comment by brotzky** [comment]
I love this idea, will be done today @bravo-kernel. Most likely the implementation will simply have a grey colored background with CSS until the user adds in an image source.

**Comment by bravo-kernel** [comment]
Awesome, I’m very curious how this will be done 👍🏼

**Comment by brotzky** [comment]
published update `v0.3.0`, includes Contentful data source option and optional hero.
may include some minor breaking changes with `social`, but should still work backwards compatible. 

ps: great issue writeup -- appreciate it.

**Comment by ryanwiemer** [comment]
@brotzky I'm also interested in this type of workflow to include logical fallbacks to make the authoring experience better for users. I actually implemented something very similar to this last week for my theme but I used a [placeholder component](https://github.com/ryanwiemer/gatsby-theme-amsterdam/blob/master/theme/src/components/Hero.js#L71). 

https://amsterdam.netlify.com/placeholder-example/

Looks like this work might already be complete but I thought I would share. Let me know if there are other fallback patterns you are considering that you want help with.

**Comment by brotzky** [comment]
I was on the fence about adding a placeholder image, but I do agree it's a better authoring experience to see the missing image. I opted for a warning in the console to avoid downloading any extra packages or including an image as a reference.

I think the placeholder component is the right move afterall.

**Comment by brotzky** [comment]
v0.3.6

I added an Image Placeholder component that renders the dimensions of the image location.

https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/src/components/Image/Image.Placeholder.tsx

http://d.ntve.co/j6mprz

**Comment by bravo-kernel** [comment]
@brotzky awesome implementation, the video says it all :100. Compliments and a big thanks, this sure adds a lot to the overall feeling of "solidity" of the theme.
