### ISSUE TITLE
[Idea] Boolean for dark posts (hidden on the homepage)

### ISSUE THREAD

**Issue by jpvalery** [narative/gatsby-theme-novela#63]
This is something I've implemented on https://github.com/jpvalery/portfolio to hide some pages from the home page.

Basically, it's a boolean property for a post `DisplayHomepage` that either includes the post in the list of posts or doesn't. 

Use case: as a user, I want to have a page accessible but not visible / as a user, I want to have posts only accessible for people with the URL.  

Similar to #43 - Probably something to edit in https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/gatsby/node/createPages.js ?

**Comment by brotzky** [comment]
Quite straight forward to add and I think it's reasonable. Brb

**Comment by brotzky** [comment]
this can now be set with `secret: true` or in Contentful `secret: yes`
`v0.3.2`

**Comment by jpvalery** [comment]
You rock 🤘!
Quick question: how do you then find the URL for the post?

**Comment by brotzky** [comment]
you can define the `slug` or it's the slug-ified version of the title

This Is My Post TItle
`/this-is-my-post-title`

**Comment by bravo-kernel** [comment]
Very nice, this also works perfectly for articles that are still work-in-progress 💯

**Comment by mabasic** [comment]
I've just noticed that the secret post is still displayed in "more articles" section at the bottom of some other post. I'll try to figure it out and send a PR.
