### ISSUE TITLE
[Feature] Adding a subscribe field for an email list?

### ISSUE THREAD

**Issue by jpvalery** [narative/gatsby-theme-novela#69]
I'm considering working on a fork to add a field allowing visitors to subscribe to an email list and I could use some brainstorm/feedback/guidance 😇 

**Why is this important**
_As an author, I'd like to be able to build a list of people interested in what I'm writing so I can notify them when a new post is live (or else)._

_As a visitor, I'd like to subscribe to a blog I like_

**Feature** 
Add a subscribe field on the homepage and/or at the end of the post.

**AC**
* Add two options in the `gatsby-config.js` 
* Add field on homepage
* Add field at the end of post page

**How to build it?** 
My first reflex would be to leverage https://github.com/benjaminhoffman/gatsby-plugin-mailchimp but maybe it'd be better to do something more generic? 
Or leverage the Netlify Forms add-on?

**Comment by brotzky** [comment]
I've seen examples of this on blogs 
- https://overreacted.io/why-do-we-write-super-props/
- https://kentcdodds.com/

They're both using:
https://convertkit.com/

I think it's probably the cheapeast and easiest solution.

Implementation:
- Either an option on each Post or a global option to add it to all posts?
- MDX component you can add to a blog at any point?

Solid idea. We've also had requests for a Comment section with Disqus or similar but refrained from implementing it right away.

**Comment by jpvalery** [comment]
The only issue I see with convertkit is that they don't offer any free tier (starts at $30 a month) :/

My thinking was : 
* From my experience, MailChimp is the go-to solution for small lists.
* Or we could leave the option to the user to choose their preferred solutions by using Netlify forms.

I was considering adding it to all posts as a global option, but maybe it'd be better to have it as a per-post option (either activate or override the global setting) 🤔 

Could the MDX component be added to the homepage description as well?

I'll start tinkering with that over the next few days 🤓

**Comment by jpvalery** [comment]
Closing as it's done in #75

**Comment by brotzky** [comment]
@jpvalery thanks so much!!!!!!!
