### ISSUE TITLE
Unable to stand up Novela development environment due to missing Contentful variables

### ISSUE THREAD

**Issue by AryanJ-NYC** [narative/gatsby-theme-novela#72]
**Version of Novela you are using**
Latest
**Number of posts you have and which data source**
Using Novela's www example

**Describe the bug**
Contentful environment variables `CONTENTFUL_SPACE_ID` and `CONTENTFUL_ACCESS_TOKEN` are required to stand up development environment:
```
Problems with gatsby-source-contentful plugin options:
spaceId: undefined - "spaceId" is required
accessToken: undefined - "accessToken" is required
host (default value): "cdn.contentful.com"
environment (default value): "master"
downloadLocal (default value): false
localeFilter (default value): [Function]
forceFullSync (default value): false
```

**To Reproduce**
1. Clone https://github.com/narative/gatsby-theme-novela
2. Nullify `CONTENTFUL_SPACE_ID` and `CONTENTFUL_ACCESS_TOKEN`
3. `yarn && yarn start`

**Expected behavior**
Build succeeds.

**Comment by brotzky** [comment]
Oooof, that's not good. Will check this out today.

**Comment by brotzky** [comment]
Contentful is now only injected if you've set both `CONTENTFUL_SPACE_ID` and `CONTENTFUL_ACCESS_TOKEN`. Sorry about that! I've also removed gatsby-source-contentful form the project deps sinice there's a bug with it.
