### ISSUE TITLE
Could we get a new release to add Mailchimp to the plugin? 

### ISSUE THREAD

**Issue by jpvalery** [narative/gatsby-theme-novela#77]
From what I see in my yarn.lock, the latest version is 0.3.7 from Aug 15th and so it's missing the subscription (and everything since then)? 

Or am I missing something / doing something wrong? 

Thanks for everything!

**Comment by brotzky** [comment]
Yes, will release!

**Comment by brotzky** [comment]
v0.4.0

includes all latest.
sidenote: I should automate this... :D

**Comment by jpvalery** [comment]
👀  Thanks for the fast reply @brotzky!
