### ISSUE TITLE
Component shadowing doesn't work on Articles.Hero.tsx

### ISSUE THREAD

**Issue by jpvalery** [narative/gatsby-theme-novela#78]
**Version of Novela you are using**
0.4.0

**Number of posts you have and which data source**
1 post local

**Describe the bug**
I've tried to set up component shadowin on Articles.Hero.tsx to change a bit how it's displayed (basically adding a sub header under the hero and down the road a subscription field).

I've followed the doc but couldn't get it to work. Despite being added at the (what I think to be the) right place and with the right name:
![image](https://user-images.githubusercontent.com/4112343/63456347-b0738580-c41c-11e9-88b5-566bd1ec7f28.png)

Tried to yarn clean and yarn dev and the issue persists.

**To Reproduce**
1. Create a Articles.Hero.tsx file
2. Copy the content from the original
3. Make some changes
4. See that the changes are not there.

**Expected behavior**
Component should be shadowed and changes reflected

**Screenshots**

**Browser**
 - Firefox

**Additional context**
Will reference this issue in a commit with the tentative component shadowing.

**Comment by brotzky** [comment]
Will tackle this on the weekend. Ran into a lot of work this week.

**Comment by jpvalery** [comment]
No worries! Get some rest as well ;)

**Comment by brotzky** [comment]
I shall get some rest. Early this week I'll tackle this. You're not the first person to run into shadowing issues.

**Comment by mabasic** [comment]
I have found a design bug in that file, fixed it, but shadowing does not work for this file also. I'll send a PR.

**Comment by mabasic** [comment]
Fixed with #97
