### ISSUE TITLE
Trying to use Novela but are having a hard time? We're here to help!

### ISSUE THREAD

**Issue by brotzky** [narative/gatsby-theme-novela#8]
Feel free to ask any general questions you have about Novela here and we'll be sure to answer it.

**Comment by johnletey** [comment]
@brotzky I love the Novela theme and I absolutely can't wait to use it for my blog! I was just curious, do you happen to support co-authoring in Novela? I know that you have support for different authors for different posts, but can you pass an array of names to the frontmatter?

**Comment by brotzky** [comment]
@johnletey, yes, for sure.

Check out the example repository
https://github.com/narative/gatsby-theme-novela-example

Define multiple authors
https://github.com/narative/gatsby-theme-novela-example/blob/master/content/authors/authors.yml

and then reference them by `name` in articles!

https://github.com/narative/gatsby-theme-novela-example/blob/master/content/posts/2017-04-28-understanding-the-gatsby-lifecycle/index.mdx
https://github.com/narative/gatsby-theme-novela-example/blob/master/content/posts/2017-04-30-why-we-built-a-company-before-a-product/index.mdx

and the result will be:
https://novela.narative.co/understanding-the-gatsby-lifecycle
https://novela.narative.co/why-we-built-a-company-before-building-a-product

Remember, one Authors required `featured: true` and will show up on the homepage.

**Comment by johnletey** [comment]
@brotzky So just to clarify ... in my front matter I'd have: `author: Dennis Brotzky, Thiago Costa`?

**Comment by brotzky** [comment]
Ohhh, sorry. You mean applying multiple authors to a single post. I misunderstood your question.
This is not possible right now, but something we can introduce.

**Comment by johnletey** [comment]
> This is not possible right now, but something we can introduce.

Would definitely love to have this feature!

**Comment by mabasic** [comment]
I love this theme, but I am having issues finding the best way to use it.

I've done:

```
gatsby new blog
yarn add @narative/gatsby-theme-novela
```

Then I ran into issue #11 

Then I studied the [example repository](https://github.com/narative/gatsby-theme-novela-example) and I got it working by changing a lot of things in the starter template.

Now I am stuck at trying to change the logo.

Can the documentation be better? If I figure out how to change the logo I will send a PR to improve the documentation.

**Comment by brotzky** [comment]
Hey @mabasic! We were really constrained on time as we wanted to submit this by August 1st to qualify for a Gatsby Theme Jam competition.

I'm working on ironing out the initial setup issues and better documentation.

I'll also create better documentation on how to customize
- components (specifically logo)
- styles

**Comment by mabasic** [comment]
@brotzky I see, I did not know that. Congrats on the theme btw. It is the best that I have seen so far.

**Comment by brotzky** [comment]
@mabasic I've added instructions on how to add you own logo (along with better getting started instructions)

https://github.com/narative/gatsby-theme-novela#adding-your-logo

Let me know if you need help or have any questions! Thanks for using Novela.

**Comment by brotzky** [comment]
Going to close the general questions thread and kindly ask everyone to create individual issues if they run into something or have a question.
