### ISSUE TITLE
[Bug] Hero Image being cut off with no way to recover

### ISSUE THREAD

**Issue by C-Rodg** [narative/gatsby-theme-novela#81]
Novela Version: 0.3.7

Locally source

Issue:
On all of my article pages, the `article.hero.full` image that is being produced inside Article.Hero.tsx results in a cut off image.  This is the result of gatsby/data/data.query.js file specifying a maxHeight property inside of the query.  Unfortunately it doesn't look like there is currently a way to overwrite the graphql queries provided.

Expected Behavior:
The entire image should be displayed.  If it is really necessary to cap it with a max-height of 425px, I feel like this should either be on the user to properly resize their image or done through CSS so that the entire image is still available to be properly scaled. 

If you are okay with this change I will happily open a PR.

Thanks!

<img width="1031" alt="cutoff_screen" src="https://user-images.githubusercontent.com/8096996/63641640-8ca38000-c666-11e9-80f4-1d9d5447a4d1.png">

**Comment by brotzky** [comment]
Removed hero limit height. Please note the progress bar is 425px so it's suggested to keep hero images to 944x245px

Now supported in v0.4.2
