### ISSUE TITLE
Table style is not working

### ISSUE THREAD

**Issue by alfieqashwa** [narative/gatsby-theme-novela#82]
**Novela version: 0.3.7**

**Data source: Local**

**Describe the bug**
Table style is not working

**Screenshots**
![sc-from-novela-theme](https://user-images.githubusercontent.com/15263927/63642195-0fb7eb00-c6e6-11e9-8bd9-30e1b86d0e69.png)

**Expected behavior**
![sc-from-github](https://user-images.githubusercontent.com/15263927/63642207-34ac5e00-c6e6-11e9-880a-e59c3dc48611.png)

**Browser**
 - chrome
 - mozilla

**Comment by brotzky** [comment]
This is true. Need to support Table styling.
Great report and thanks.

**Comment by brotzky** [comment]
@tcostaco can we grab the table styles we've made before in some proposals?
Will use those in article.

**Comment by tcostaco** [comment]
Thanks for the report @alfieqashwa! I'll look into it this week. 👀

**Comment by brotzky** [comment]
Latest has basic styling.
