### ISSUE TITLE
isDark() in component does not work as expected. 

### ISSUE THREAD

**Issue by tiddler** [narative/gatsby-theme-novela#83]
**Version of Novela you are using**
0.4.0

**Describe the bug**
In commit `83246d7`: 

> Moving components into MDX Provider for easier Shadowing

`isDark` is put in the MDXRenderer props in MDX.tsx file.
```Html
    <MDXProvider components={components}>
      <MDXBody>
        <MDXRenderer isDark={colorMode === "dark"} {...props}>
          {content}
        </MDXRenderer>
        {children}
      </MDXBody>
    </MDXProvider>
```
However, in the actual component, when trying to fetch the mode by
```JavaScript
${p => p.isDark}
```
the `props` here only contains `children` and `theme` without the prop : `isDark`.

Tracing the code, I found in the `@gatsby-plugin-mdx/mdx-renderer.js`, it does pass the correct props to React.createElement.
But later when update the styles when toggling Dark mode, in `@emotion/styled-base/dist/styled-base.browser.esm.js`:70 line, the code says
```JavaScript
        var mergedProps = props;

        if (props.theme == null) {
          mergedProps = {};

          for (var key in props) {
            mergedProps[key] = props[key];
          }

          mergedProps.theme = theme;
        }
```
The `props` here doesn't contain `isDark`, as a result, all the components won't be able to fetch the current color mode.

I could not track the reason for it. Please confirm the bug and provide some help.

> As my temporary solution, I use this function as the substitution (it is not a correct fix, just for reference):
```JavaScript
function isDark(p) {
  return p.theme.colors.articleText === p.theme.colors.modes.dark.articleText;
}
```

To reproduce it, all MDX components with `p.isDark` do not work as expected, for example, `HorizontalRule` component won't change color when toggling the color mode.

**Comment by brotzky** [comment]
Hmmm, I wonder if this is an issue with `gatsby-plugin-mdx`. According to their docs we're doing exactly what it says and you're right, the prop is not being passed down into the component.

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#mdxrenderer

I've tried tested this in the code:

```js
function Test(props) {
  console.log(props)
  return null
}

const components = {
  p: Test,
};



function MDX({ content, children, ...props }) {
  const [colorMode] = useColorMode();

  return (
    <MDXProvider components={components}>
      <MDXBody>
        <MDXRenderer isDark={colorMode === "dark"} {...props}>
          {content}
        </MDXRenderer>
        {children}
      </MDXBody>
    </MDXProvider>
  );
}
```

And it only logs out `props.children` out.
