### ISSUE TITLE
Potential UI bug in Article.Hero.tsx

### ISSUE THREAD

**Issue by tiddler** [narative/gatsby-theme-novela#84]
**Version of Novela you are using**
0.4.0

**Describe the bug**
Adjust the width of the browser to this range ( 540px < x < 960px), say 800px.

![image](https://user-images.githubusercontent.com/9299201/63644425-d3b96180-c6b6-11e9-86eb-450bd169faab.png)

Remove this line in `Article.Hero.tsx` can fix the UI bug.

```JavaScript
...
const HeroImage = styled.div`
  position: relative;
  z-index: 1;
  width: 100%;
  height: 424px; /* remove this line. */
...
```

**Expected behavior**
The UI bug fixed with this removal.

![image](https://user-images.githubusercontent.com/9299201/63644490-28111100-c6b8-11e9-8fa4-c320b1cf9c1a.png)

**Comment by brotzky** [comment]
Thanks Tiddler. Will work on this today.

**Comment by brotzky** [comment]
height removed. note the progress bar is 425px so it's recommend to post hero images at that height.

v0.4.2
