### ISSUE TITLE
Bad author page slug

### ISSUE THREAD

**Issue by slorber** [narative/gatsby-theme-novela#86]
https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/gatsby/node/createPages.js#L29

This slugify function is a bit too simple:

```js
function slugify(str, base) {
  const slug = str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)+/g, "");

  return `${base}/${slug}`.replace(/\/\/+/g, "/");
}
```

This lead to `"/authors/s-bastien-lorber"` for my author page

I suggest using a technique to replace accents with non-accent chars before replacing by -. Also using a dedicated slugification package could do the job
https://stackoverflow.com/a/37511463/82609

Eventually having the ability to choose my own slug could be handy

**Comment by brotzky** [comment]
Will add a package to handle this and have it the same as articles where you can define an optional `slug` that overrides the generated one.

**Comment by brotzky** [comment]
Special characters and custom slug now supported for authors.
v0.4.2

**Comment by slorber** [comment]
Thanks :)

**Comment by jpvalery** [comment]
Same issue for posts title `métro` becomes `m-tro` - could we get the same fix there?

**Comment by brotzky** [comment]
great idea. will port it to handle Posts as well.

**Comment by brotzky** [comment]
This should already be handled actually! at least locally. maybe I need to publish the update :)

**Comment by jpvalery** [comment]
That's probably going to help 😛
