### ISSUE TITLE
Can we have releases on github also?

### ISSUE THREAD

**Issue by mabasic** [narative/gatsby-theme-novela#89]
**Is your feature request related to a problem? Please describe.**
In the issues on this repository I could see people talking about version 0.4.0, 0.4.1, 0.4.2, but the latest release on github is 0.2.0. At first I was puzzled until I checked on NPM and there are the correct versions and the latest version is 0.4.3. It is very hard to see if there is a new release if I have to check on NPM, but the code and issues are on github.

**Describe the solution you'd like**
Push release tags to github.

btw. The theme is improving daily. Love it. Are you open for a RSS feed PR?

**Comment by mabasic** [comment]
I also have added icons for patreon and paypal. Do you want me to send a PR for that also?

**Comment by bravo-kernel** [comment]
@mabasic when CI/CD is done the releases will be automated, keeping both npm and github release versions identical. Should become real soon.

**Comment by brotzky** [comment]
This is work in progress and follow this issue for more details: https://github.com/narative/gatsby-theme-novela/issues/109
