### ISSUE TITLE
Line Highlighting is not working

### ISSUE THREAD

**Issue by alfieqashwa** [narative/gatsby-theme-novela#9]
novela-theme does not have line-highlight like ==> https://twitter.com/kentcdodds/status/1110276893293473792
could you add that? or show me how to customize using theme-ui ?

thanks

**Comment by brotzky** [comment]
Nice catch, and definitely need to integrate this.

**Comment by brotzky** [comment]
v0.0.4 now has syntax highlighting

Thanks @alfieqashwa.
