### ISSUE TITLE
Add an optional caption under images

### ISSUE THREAD

**Issue by freddydumont** [narative/gatsby-theme-novela#96]
It'd be nice to have to credit the photo author or just to add context to the image. Like this on medium:

![image](https://user-images.githubusercontent.com/15388588/63765090-962c2280-c8c8-11e9-9ae7-3383c129052d.png)

**Comment by johnletey** [comment]
Would also be nice to support markdown as well

**Comment by brotzky** [comment]
I think this will be implemented through MDX. Originally I thought of pulling the alt tag but there are cases where you want links and other features to to work within that description.

**Comment by kevinra** [comment]
I'm not sure if this is the right way but here's how I implemented the image caption.
1. Create `Figcaption.tsx` under `src/@narative/gatsby-theme-novela/components/Figcaption/`
Its content can look something like this:
```javascript
import styled from "@emotion/styled";

const Figcaption = styled.figcaption`
  padding: 0 10px;
  color: ${p => p.theme.colors.grey};
  font-size: 14px;
`;

export default Figcaption;
```
2. Create `MDX.tsx` under `src/@narative/gatsby-theme-novela/components/MDX/` to shadow MDX component. Add these two lines somewhere in the code:
```javascript
import Figcaption from "@components/Figcaption/Figcaption.tsx"
...
figcaption: Figcaption, // Note that this should be under components definition block
```
3. Use `figcaption` element inside image div like this to achieve the effect:
```html
<div className="Image__Small">
  <img
    src="./images/article-image-2.jpg"
    title="Logo Title Text 1"
    alt="Alt text"
  />
  <figcaption>This is example image caption. Nice picture by the way!</figcaption>
</div>
```
This will make it look like this in the example first post in the theme:
![image](https://user-images.githubusercontent.com/6539629/69117206-fa402c00-0a5c-11ea-8380-a5a038ad70f2.png)

**Comment by brotzky** [comment]
I think that's the best way to implement it as well, @kevinra. Gives you full customizability and takes advantage of the beauty of MDX.

**Comment by EmaSuriano** [comment]
@brotzky do you think this feature should be implemented using shallowing by each developer or if it should be part of the official theme?

**Comment by brotzky** [comment]
In this instance you're not shadowing as you're creating the component yourself and not overriding anything from Novela.

The component seems quite simple so maybe it's best to keep it outside and have userland do it like they want :)

**Comment by kevinra** [comment]
I think it's a good idea to have an image caption feature on Novela theme. An experienced dev can always tweak existing tools like this to fit their needs because they understand the framework. On the other hand, people like me who have limited front end development experience, it's hard to implement such features on their own without lots of Googling and help. Our life can be easier if such features are provided with an example so that we can decide whether to use them or not. After all, I think image caption is commonly seen on any online article.

I can create PR if you guys are interested.

**Comment by brotzky** [comment]
PR is welcomed <3

**Comment by kevinra** [comment]
When an image fits the paragraph width, it's fine. There's a problem when the image is narrower. It looks ugly when the text spans wider than the image its describing.

I want to make the `figcaption` to have the same width as the image but don't know how. Is there a way to match the width of `gatsby-resp-image-wrapper` on figcaption style?

**Comment by brotzky** [comment]
I believe we have a set of widths defined here. You could re-use the image classes if you wanted to:
https://github.com/narative/gatsby-theme-novela/blob/master/%40narative/gatsby-theme-novela/src/components/MDX/MDX.tsx#L210

It's not the cleanest implementation right now, but there you should be able to see the breakpoints and max-widths of each image variation.

**Comment by kevinra** [comment]
Hmm I don't understand your solution. the max-width in `MDX.tsx` files are the max-width of `Image__*` container meaning `figcaption` inherits the same width.

Here's a detailed example of the problem. The small image (let's say A) I have has a width of 360. `Image__Small` is set to have `max-width` of 680. Image A is contained by `gatsby-resp-image-wrapper` with `max-width=360px`. Now `figcaption` must have max-width of 360, not 680. How do I achieve this by modifying `MDX.tsx`?

I was thinking solutions like this but no luck:
https://stackoverflow.com/questions/30686191/how-to-make-image-caption-width-to-match-image-width
https://stackoverflow.com/questions/37442430/limiting-caption-to-width-of-the-image

**Comment by imprashast** [comment]
> When an image fits the paragraph width, it's fine. There's a problem when the image is narrower. It looks ugly when the text spans wider than the image its describing.
> 
> I want to make the `figcaption` to have the same width as the image but don't know how. Is there a way to match the width of `gatsby-resp-image-wrapper` on figcaption style?

What do you mean narrower than paragraph? I style the css like this for the class `Image__Small` and it looks absolutely fine: 
<img width="358" alt="Screen Shot 2019-11-26 at 11 22 06 PM" src="https://user-images.githubusercontent.com/21952706/69677683-bcb65100-10a3-11ea-9399-7bd8d13eb8a6.png">

This is my css:
```
  color: ${p => p.theme.colors.grey};
  font-size: 14px;
  text-align: center;
  width: 100%;
```

**Comment by kevinra** [comment]
@imprashast Is the image width greater or equal to paragraph width? If not, try expanding the browser width. Please refer to the image below for the problem I'm facing.

![example](https://user-images.githubusercontent.com/6539629/69780120-54856f00-1178-11ea-9f8a-4495324f46b3.png)


Of course,
 a workaround is to avoid using small image but what if I need to place such square image?

**Comment by imprashast** [comment]
Well, my css still works:
<img width="380" alt="Screen Shot 2019-11-30 at 12 28 30 PM" src="https://user-images.githubusercontent.com/21952706/69899908-fd94bb00-136c-11ea-8a0c-6b08855d7a53.png">
<img width="796" alt="Screen Shot 2019-11-30 at 12 28 17 PM" src="https://user-images.githubusercontent.com/21952706/69899909-fd94bb00-136c-11ea-9602-9b67fad41971.png">

Do you want me to send the PR?

**Comment by kevinra** [comment]
Interesting. I wonder why my implementation doesn't work :( 
Yes it would be great if everyone can benefit from this feature!

**Comment by imprashast** [comment]
@brotzky Can you give me access to push to the repo?

**Comment by brotzky** [comment]
@imprashast make a PR, should be the easiest way :)
https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

(also, we'll want a bit of spacing under the image. From the screenshots it looks a bit too close. mybe 6px)

**Comment by imprashast** [comment]
Can be closed now 😄
