### ISSUE TITLE
Reading time does not take code into account

### ISSUE THREAD

**Issue by slorber** [narative/gatsby-theme-novela#99]
I have an article which is 5min read according to Novela, but in practice it's more 15-20min, due to many code fragments and MDX demo components.

I think it would be nice to word count code or something (eventually with a different word/min ratio), and eventually let ability to the user to specify reading time through frontmatter so that we can hardcode a time according to concrete reader's feedback

**Comment by brotzky** [comment]
This has already been opened with Gatsby and is a duplicate
https://github.com/gatsbyjs/gatsby/issues/16760

**Comment by slorber** [comment]
hi

I understand this one might be hard to solve and anyway it's quite hard to tell how much time an image or a code block takes to read anyway...

I would be fine if there was just an ability to override this reading time with frontmatter data. I'm not sure we can compute a perfect value automatically anyway

**Comment by brotzky** [comment]
Yes, overriding with custom reading time might be the way to go.

**Comment by brotzky** [comment]
You should be able to override with `timeToRead` set on an article. If it's no possible please reopen the issue <3

**Comment by slorber** [comment]
Great thanks 😉

Le dim. 5 janv. 2020 à 04:35, Dennis Brotzky <notifications@github.com> a
écrit :
